questions = {
    "名词与冠词": [
        {"question": "affect和effect的区别在于", "options": ["affect是动词，effect是名词", "affect是名词，effect是动词", "两者相同", "没有区别"], "answer": 0, "解析": "affect是动词，effect是名词"},
        {"question": "下列词语中，与\"economic\"意思相近的是", "options": ["经济的", "节约的", "生态的", "教育的"], "answer": 0, "解析": "economic意为\"经济的\""},
        {"question": "固定搭配\"look forward to\"后面接", "options": ["动名词", "动词原形", "不定式", "过去式"], "answer": 0, "解析": "\"look forward to\"后面接动名词"},
        {"question": "下列属于近义词的是", "options": ["big和large", "big和small", "fast和slow", "hot和cold"], "answer": 0, "解析": "big和large都表示\"大的\""},
        {"question": "下列属于反义词的是", "options": ["happy和sad", "happy和glad", "sad和unhappy", "以上都不对"], "answer": 0, "解析": "happy和sad是反义词"},
        {"question": "I have _____ apple. _____ apple is red.", "options": ["a; The", "an; The", "an; A", "the; An"], "answer": 1, "解析": "apple以元音音素开头，不定冠词用an；第二次提到用the"},
        {"question": "_____ Smiths are going to visit China next month.", "options": ["The", "A", "An", "不填"], "answer": 0, "解析": "the+姓氏复数表示一家人"},
        {"question": "We need to buy some _____ for the party.", "options": ["furniture", "furnitures", "a furniture", "piece furniture"], "answer": 0, "解析": "furniture是不可数名词"},
        {"question": "There are two _____ in the hospital.", "options": ["women doctors", "woman doctors", "women doctor", "woman doctor"], "answer": 0, "解析": "复合名词变复数，man和woman与后面名词都变"},
        {"question": "He gave me _____ useful advice.", "options": ["a piece of", "an", "a", "many"], "answer": 0, "解析": "advice不可数，a piece of advice表示一条建议"},
    ],
    "代词": [
        {"question": "\"break down\"的意思是", "options": ["分解、崩溃", "打破", "爆发", "中断"], "answer": 0, "解析": "break down表示分解、崩溃"},
        {"question": "（2023全国甲卷）The word \"unprecedented\" in the passage is closest in meaning to", "options": ["never happened before", "happening very often", "happening every day", "happening once a year"], "answer": 0, "解析": "unprecedented意为\"史无前例的\""},
        {"question": "（2022全国甲卷）Which of the following words can replace \"significant\" in the sentence?", "options": ["important", "small", "unimportant", "difficult"], "answer": 0, "解析": "significant意为\"重要的\"，与important意思相近"},
        {"question": "（2021全国乙卷）The word \"sustainable\" in the passage probably means", "options": ["able to continue for a long time", "able to be destroyed easily", "able to be changed quickly", "able to be forgotten soon"], "answer": 0, "解析": "sustainable意为\"可持续的\""},
        {"question": "（2020全国III卷）What does the word \"vulnerable\" mean?", "options": ["easily hurt or attacked", "very strong and powerful", "completely safe", "always happy"], "answer": 0, "解析": "vulnerable意为\"脆弱的、易受伤害的\""},
        {"question": "_____ is important to learn English well.", "options": ["It", "This", "That", "What"], "answer": 0, "解析": "it作形式主语，真正主语是不定式短语"},
        {"question": "The book on the desk is _____. I wrote my name on it.", "options": ["mine", "my", "me", "myself"], "answer": 0, "解析": "物主代词后无名词，用名词性物主代词"},
        {"question": "Help _____ to some fish, children.", "options": ["yourselves", "yourself", "you", "yours"], "answer": 0, "解析": "children是复数，反身代词用yourselves"},
        {"question": "_____ of the students has a dictionary.", "options": ["Each", "Every", "All", "Both"], "answer": 0, "解析": "each可以作代词，谓语动词用单数；every不能作主语"},
        {"question": "I have two brothers. _____ of them are doctors.", "options": ["Both", "All", "Either", "Neither"], "answer": 0, "解析": "both用于两者，谓语用复数"},
    ],
    "数词": [
        {"question": "There are _____ days in a year.", "options": ["three hundred sixty-five", "three hundred and sixty-five", "three hundreds and sixty-five", "three hundreds sixty-five"], "answer": 1, "解析": "百位数与十位数之间用and连接，hundred不加s"},
        {"question": "He lives on _____ floor.", "options": ["the ninth", "ninth", "the nineth", "nine"], "answer": 0, "解析": "序数词前加the，ninth是nine的序数词"},
        {"question": "_____ of the students in our class are girls.", "options": ["Two thirds", "Two third", "Second three", "Twos thirds"], "answer": 0, "解析": "分数表达：分子用基数词，分母用序数词，分子大于1分母加s"},
        {"question": "He was _____ to win the game.", "options": ["the first", "first", "one", "the one"], "answer": 0, "解析": "序数词前通常加the"},
        {"question": "The river is about _____ long.", "options": ["five hundred meters", "five hundreds meters", "five-hundred-meter", "five hundreds meter"], "answer": 0, "解析": "hundred表示确数不加s"},
    ],
    "形容词与副词": [
        {"question": "（2019全国III卷）The phrase \"take into account\" is closest in meaning to", "options": ["consider", "ignore", "forget", "remember"], "answer": 0, "解析": "take into account意为\"考虑到\""},
        {"question": "（2018全国III卷）What is the meaning of \"enormous\"?", "options": ["very large", "very small", "very beautiful", "very ugly"], "answer": 0, "解析": "enormous意为\"巨大的\""},
        {"question": "（2017全国III卷）The word \"diverse\" in the passage means", "options": ["different", "similar", "same", "unknown"], "answer": 0, "解析": "diverse意为\"多样的、不同的\""},
        {"question": "（2016全国III卷）Which word is closest in meaning to \"abundant\"?", "options": ["plenty of", "little", "no", "few"], "answer": 0, "解析": "abundant意为\"丰富的、大量的\""},
        {"question": "This book is _____ than that one.", "options": ["more interesting", "most interesting", "interesting", "the most interesting"], "answer": 0, "解析": "多音节形容词比较级用more"},
        {"question": "She sings _____ in our class.", "options": ["the best", "best", "better", "well"], "answer": 0, "解析": "副词最高级前the可以省略，但作主语补足语时保留"},
        {"question": "The weather is getting _____ and _____.", "options": ["warmer; warmer", "warm; warm", "more warm; more warm", "warm; warm"], "answer": 0, "解析": "比较级+and+比较级表示\"越来越…\""},
        {"question": "He is _____ of the two boys.", "options": ["the taller", "taller", "the tallest", "tall"], "answer": 0, "解析": "两者中较…的一个用the+比较级"},
        {"question": "I have never seen _____ film before.", "options": ["such an interesting", "so an interesting", "such interesting a", "so interesting"], "answer": 0, "解析": "such修饰名词，such+a/an+adj+n"},
    ],
    "介词": [
        {"question": "I usually go to school _____ bus.", "options": ["by", "on", "in", "with"], "answer": 0, "解析": "by+交通工具表示方式"},
        {"question": "He is interested _____ music.", "options": ["in", "on", "at", "for"], "answer": 0, "解析": "be interested in固定搭配"},
        {"question": "The meeting will be held _____ May 15th.", "options": ["on", "in", "at", "for"], "answer": 0, "解析": "具体某一天用介词on"},
        {"question": "She is good _____ playing the piano.", "options": ["at", "in", "on", "of"], "answer": 0, "解析": "be good at固定搭配"},
        {"question": "_____ the help of my teacher, I made great progress.", "options": ["With", "Under", "By", "For"], "answer": 0, "解析": "with the help of固定搭配"},
    ],
    "连词": [
        {"question": "Study hard, _____ you will pass the exam.", "options": ["and", "but", "or", "so"], "answer": 0, "解析": "祈使句+and+陈述句，表示\"如果…就…\""},
        {"question": "He is rich _____ he is not happy.", "options": ["but", "and", "or", "so"], "answer": 0, "解析": "but表示转折关系"},
        {"question": "_____ you work hard, you will succeed.", "options": ["If", "Though", "Because", "Unless"], "answer": 0, "解析": "if引导条件状语从句"},
        {"question": "She got up early _____ she could catch the first bus.", "options": ["so that", "such that", "in order to", "for"], "answer": 0, "解析": "so that引导目的状语从句"},
        {"question": "_____ it rained heavily, they still went out.", "options": ["Although", "Because", "Since", "If"], "answer": 0, "解析": "although引导让步状语从句"},
    ],
    "动词分类": [
        {"question": "下列动词中，属于及物动词的是", "options": ["love", "sleep", "cry", "arrive"], "answer": 0, "解析": "love后面可直接跟宾语，是及物动词"},
        {"question": "系动词后常接", "options": ["形容词作表语", "副词修饰", "动词原形", "过去分词"], "answer": 0, "解析": "系动词后接形容词作表语"},
        {"question": "\"I can swim\"中的\"can\"是", "options": ["情态动词", "实义动词", "系动词", "助动词"], "answer": 0, "解析": "can表示能力，是情态动词"},
        {"question": "助动词do在否定句中的作用是", "options": ["帮助构成否定", "表示强调", "表达时态", "替代实义动词"], "answer": 0, "解析": "do作为助动词帮助一般现在时的否定和疑问"},
        {"question": "下列动词中，既是及物又是不及物动词的是", "options": ["study", "die", "rise", "happen"], "answer": 0, "解析": "study可以是及物（学习某物）也可以是不及物（学习）"},
    ],
    "动词时态": [
        {"question": "He suggested that we _____ early the next day.", "options": ["start", "started", "starting", "to start"], "answer": 0, "解析": "suggest后接虚拟语气，用动词原形"},
        {"question": "She _____ to school every day.", "options": ["goes", "go", "going", "went"], "answer": 0, "解析": "主语是第三人称单数，动词加s"},
        {"question": "She usually _____ up at 6 o'clock.", "options": ["gets", "got", "getting", "get"], "answer": 0, "解析": "usually表示经常性动作用一般现在时"},
        {"question": "They _____ football when it began to rain.", "options": ["were playing", "played", "have played", "play"], "answer": 0, "解析": "过去进行时表示过去某个时刻正在发生的事"},
        {"question": "I _____ the book yet.", "options": ["haven't finished", "didn't finish", "don't finish", "won't finish"], "answer": 0, "解析": "yet用于现在完成时否定句"},
        {"question": "By next year, he _____ here for 10 years.", "options": ["will have lived", "has lived", "will live", "is living"], "answer": 0, "解析": "by+将来时间，用将来完成时"},
        {"question": "She _____ to Beijing twice.", "options": ["has been", "has gone", "went", "goes"], "answer": 0, "解析": "has been to表示去过某地"},
    ],
    "被动语态": [
        {"question": "The book _____ by many students.", "options": ["is read", "reads", "read", "reading"], "answer": 0, "解析": "被动语态：be+过去分词"},
        {"question": "I have been studying English _____ three years.", "options": ["for", "since", "in", "at"], "answer": 0, "解析": "for+时间段"},
        {"question": "A new bridge _____ in my hometown next year.", "options": ["will be built", "is built", "was built", "has been built"], "answer": 0, "解析": "next year将来时，桥被建用被动"},
        {"question": "This book _____ by many students.", "options": ["is often read", "often reads", "often read", "is often reading"], "answer": 0, "解析": "书被读用被动语态"},
        {"question": "The window _____ by the boy yesterday.", "options": ["was broken", "broke", "is broken", "breaks"], "answer": 0, "解析": "yesterday用一般过去时被动"},
        {"question": "Vegetables must _____ before eating.", "options": ["be washed", "wash", "washed", "be washing"], "answer": 0, "解析": "情态动词被动：must+be+过去分词"},
        {"question": "（2023全国甲卷）The experiment _____ when the power went out.", "options": ["was being conducted", "conducted", "was conducting", "has conducted"], "answer": 0, "解析": "实验被进行，过去进行时被动"},
    ],
    "非谓语动词": [
        {"question": "It's important _____ English well.", "options": ["to learn", "learning", "learn", "learned"], "answer": 0, "解析": "it作形式主语，不定式作真正主语"},
        {"question": "I enjoy _____ to music.", "options": ["listening", "to listen", "listen", "listened"], "answer": 0, "解析": "enjoy后接动名词"},
        {"question": "The boy _____ in the room is my brother.", "options": ["playing", "plays", "played", "to play"], "answer": 0, "解析": "现在分词短语作定语修饰名词"},
        {"question": "He went to the library _____ some books.", "options": ["to borrow", "borrowing", "borrow", "borrowed"], "answer": 0, "解析": "不定式作目的状语"},
        {"question": "（2022全国甲卷）_____ from the top, the city looks beautiful.", "options": ["Seen", "Seeing", "To see", "See"], "answer": 0, "解析": "过去分词作状语，表示被看"},
    ],
    "句子成分与句型": [
        {"question": "（2019全国III卷）By the time he arrived, we _____ the work.", "options": ["had finished", "finished", "have finished", "finish"], "answer": 0, "解析": "过去完成时表示过去的过去"},
        {"question": "（2018全国III卷）She told me that she _____ to the USA the next day.", "options": ["would go", "will go", "goes", "went"], "answer": 0, "解析": "过去将来时"},
        {"question": "句子\"I love you\"的结构是", "options": ["S+V+O", "S+V", "S+V+P", "S+V+O+OC"], "answer": 0, "解析": "主谓宾结构：S+V+O"},
        {"question": "句子\"He is a teacher\"中的\"a teacher\"是", "options": ["表语", "宾语", "宾补", "定语"], "answer": 0, "解析": "系动词后成分是表语"},
        {"question": "定语是用来修饰", "options": ["名词或代词", "动词", "介词短语", "状语"], "answer": 0, "解析": "定语修饰名词或代词"},
        {"question": "英语中，表示地点和时间的状语位置通常是", "options": ["地点在前、时间在后", "时间在前、地点在后", "地点在前、地点在后", "任意位置"], "answer": 0, "解析": "英语中地点状语先于时间状语"},
        {"question": "句子\"She gave me a book\"的间宾和直宾分别是", "options": ["me是间宾，a book是直宾", "me是直宾，a book是间宾", "都是宾语", "没有区别"], "answer": 0, "解析": "双宾语中，人（me）是间接宾语，物（book）是直接宾语"},
    ],
    "定语从句": [
        {"question": "（2023全国甲卷）If I _____ you, I would take the job.", "options": ["were", "was", "am", "be"], "answer": 0, "解析": "虚拟语气条件句中，be动词用were"},
        {"question": "（2022全国甲卷）The project _____ by the end of next month.", "options": ["will have been completed", "has completed", "is completed", "completes"], "answer": 0, "解析": "将来完成时被动语态"},
        {"question": "The man _____ spoke to you is my teacher.", "options": ["who", "whom", "whose", "which"], "answer": 0, "解析": "先行词是人，关系代词在从句中作主语用who/that"},
        {"question": "This is the book _____ I bought yesterday.", "options": ["which", "who", "whom", "whose"], "answer": 0, "解析": "先行词是物，关系代词用which/that"},
        {"question": "I know the girl _____ mother is a doctor.", "options": ["whose", "who", "whom", "which"], "answer": 0, "解析": "关系代词whose表示所属关系"},
        {"question": "This is the house _____ I lived two years ago.", "options": ["where", "which", "that", "when"], "answer": 0, "解析": "先行词是地点，关系副词用where"},
        {"question": "（2023全国乙卷）The reason _____ he was late is unknown.", "options": ["why", "which", "that", "where"], "answer": 0, "解析": "先行词reason，关系副词why引导定语从句"},
    ],
    "状语从句": [
        {"question": "He was doing his homework _____ his mother came in.", "options": ["when", "while", "as", "since"], "answer": 0, "解析": "when表示\"正在做某事时突然…\""},
        {"question": "I will wait _____ you come back.", "options": ["until", "since", "because", "though"], "answer": 0, "解析": "until表示\"直到…\""},
        {"question": "_____ there is a will, there is a way.", "options": ["Where", "When", "If", "Because"], "answer": 0, "解析": "where引导地点状语从句"},
        {"question": "She studies hard _____ she can get good grades.", "options": ["so that", "such that", "in order to", "as if"], "answer": 0, "解析": "so that引导目的状语从句"},
        {"question": "_____ it was raining, they went on working.", "options": ["Though", "Because", "Since", "When"], "answer": 0, "解析": "though引导让步状语从句"},
    ],
    "名词性从句": [
        {"question": "_____ he will come to the party is still unknown.", "options": ["Whether", "If", "That", "What"], "answer": 0, "解析": "whether引导主语从句，句首不用if"},
        {"question": "I don't know _____ he said.", "options": ["what", "that", "which", "who"], "answer": 0, "解析": "what引导宾语从句，在从句中作宾语"},
        {"question": "The problem is _____ we can get there on time.", "options": ["whether", "if", "that", "what"], "answer": 0, "解析": "表语从句中，whether表示\"是否\""},
        {"question": "The news _____ he won the game is exciting.", "options": ["that", "which", "what", "whether"], "answer": 0, "解析": "that引导同位语从句"},
        {"question": "_____ he needs is more time.", "options": ["What", "That", "Which", "Whether"], "answer": 0, "解析": "what引导主语从句，在从句中作宾语"},
    ],
    "虚拟语气": [
        {"question": "This is the house _____ I lived.", "options": ["where", "which", "that", "what"], "answer": 0, "解析": "定语从句修饰地点，用where引导"},
        {"question": "If I _____ you, I would study harder.", "options": ["were", "was", "am", "be"], "answer": 0, "解析": "虚拟语气条件句中，be动词用were"},
        {"question": "If I _____ you, I would accept the offer.", "options": ["were", "was", "am", "be"], "answer": 0, "解析": "与现在事实相反的虚拟语气，be用were"},
        {"question": "I wish I _____ fly to the moon.", "options": ["could", "can", "will", "may"], "answer": 0, "解析": "wish后接could/were等表示与事实相反的愿望"},
        {"question": "He suggested that we _____ early.", "options": ["start", "started", "starting", "to start"], "answer": 0, "解析": "suggest表示建议后接虚拟语气，用(should)+动词原形"},
        {"question": "If it _____ tomorrow, the picnic would be cancelled.", "options": ["rained", "rains", "will rain", "has rained"], "answer": 0, "解析": "与将来事实可能相反，条件从句用一般过去时"},
        {"question": "It is time that we _____ to bed.", "options": ["went", "go", "should go", "going"], "answer": 0, "解析": "It is time that后从句用一般过去时虚拟"},
    ],
    "情态动词": [
        {"question": "You _____ return the book on time.", "options": ["must", "can", "may", "need"], "answer": 0, "解析": "must表示必须"},
        {"question": "He _____ be at home. The light is on.", "options": ["must", "can't", "may", "need"], "answer": 0, "解析": "must表示肯定推测"},
        {"question": "_____ I use your pen?", "options": ["May", "Must", "Need", "Will"], "answer": 0, "解析": "may表示请求许可"},
        {"question": "You _____ have told me earlier.", "options": ["should", "must", "can", "may"], "answer": 0, "解析": "should have done表示本应该做某事"},
        {"question": "He _____ be in the classroom. I saw him go out.", "options": ["can't", "mustn't", "needn't", "may not"], "answer": 0, "解析": "can't表示否定推测"},
    ],
    "主谓一致": [
        {"question": "（2017全国III卷）The book, _____ I bought yesterday, is very interesting.", "options": ["which", "that", "what", "who"], "answer": 0, "解析": "非限制性定语从句用which"},
        {"question": "（2016全国III卷）Not only _____ good at English, but also she is good at math.", "options": ["is she", "she is", "does she", "she does"], "answer": 0, "解析": "not only位于句首，主谓倒装"},
        {"question": "The teacher with his students _____ going to the museum.", "options": ["is", "are", "were", "have"], "answer": 0, "解析": "主语是The teacher，with结构是修饰语，谓语用单数"},
        {"question": "Either you or he _____ wrong.", "options": ["is", "are", "were", "have"], "answer": 0, "解析": "就近原则，谓语与he一致，用单数"},
        {"question": "The news _____ very exciting.", "options": ["is", "are", "were", "have"], "answer": 0, "解析": "news是不可数名词，谓语用单数"},
        {"question": "Physics _____ my favorite subject.", "options": ["is", "are", "were", "have"], "answer": 0, "解析": "学科名词作主语，谓语用单数"},
        {"question": "There _____ a book and two pens on the desk.", "options": ["is", "are", "were", "have"], "answer": 0, "解析": "there be句型就近原则，a book是单数"},
    ],
    "阅读理解·主旨大意": [
        {"question": "阅读理解中，主旨大意题的解题关键是", "options": ["找主题句", "找细节", "翻译全文", "猜测词义"], "answer": 0, "解析": "主旨大意题的关键是找主题句"},
        {"question": "细节理解题需要", "options": ["回到原文定位", "凭记忆作答", "主观推断", "忽略原文"], "answer": 0, "解析": "细节理解题需要回到原文定位"},
        {"question": "推理判断题的特点是", "options": ["答案不在原文直接出现", "答案在原文直接出现", "不需要推理", "凭感觉"], "answer": 0, "解析": "推理判断题需要根据原文进行推断"},
        {"question": "The main idea of a passage is usually found in the _____ paragraph.", "options": ["first or last", "middle", "second", "every"], "answer": 0, "解析": "文章主旨通常在首段或末段"},
        {"question": "When asked about the \"best title\" of a passage, you should", "options": ["choose the most general and inclusive one", "choose the most detailed one", "choose a title with numbers", "choose a long title"], "answer": 0, "解析": "最佳标题应最能概括全文"},
    ],
    "阅读理解·细节理解": [
        {"question": "词义猜测题常用的方法是", "options": ["结合上下文", "查字典", "猜测", "忽略"], "answer": 0, "解析": "词义猜测需要结合上下文"},
        {"question": "作者态度题需要", "options": ["分析作者的用词和语气", "看文章长度", "数段落数", "看标题"], "answer": 0, "解析": "作者态度需要通过分析用词和语气判断"},
        {"question": "What is the main idea of the passage? 这类问题考查的是", "options": ["主旨大意", "细节理解", "推理判断", "词义猜测"], "answer": 0, "解析": "main idea表示主旨大意"},
        {"question": "细节理解题的最佳解题方法是", "options": ["先读题再回原文定位", "先通读全文再做题", "凭印象选答案", "先看选项再读文章"], "answer": 0, "解析": "先读题找出关键词，再到原文定位"},
        {"question": "Which of the following is TRUE according to the passage? 属于什么题型", "options": ["细节判断题", "主旨大意题", "推理判断题", "词义猜测题"], "answer": 0, "解析": "true/not true/except判断属于细节理解题"},
    ],
    "阅读理解·推理判断": [
        {"question": "（2023全国甲卷）What is the main purpose of the passage?", "options": ["To introduce a new technology", "To describe a historical event", "To argue for a new policy", "To tell a personal story"], "answer": 0, "解析": "文章主要介绍了一项新技术"},
        {"question": "（2022全国甲卷）According to the passage, which of the following is true?", "options": ["The new method is more efficient", "The old method is better", "Both methods are equally good", "Neither method works"], "answer": 0, "解析": "根据原文，新方法更高效"},
        {"question": "（2021全国乙卷）What can we infer from the passage?", "options": ["The project will be successful", "The project will fail", "The project is impossible", "The project is too expensive"], "answer": 0, "解析": "从文章可以推断项目会成功"},
        {"question": "推理判断题的标志词是", "options": ["infer/imply/suggest", "main idea", "meaning", "title"], "answer": 0, "解析": "infer/imply/suggest等词提示是推理判断题"},
        {"question": "进行推理判断时，应", "options": ["基于原文信息合理推断", "凭主观想象", "忽略文章内容", "只看标题"], "answer": 0, "解析": "推理判断必须基于原文信息"},
    ],
    "阅读理解·词义猜测": [
        {"question": "（2020全国III卷）What is the author's attitude towards the new plan?", "options": ["Supportive", "Opposed", "Neutral", "Uninterested"], "answer": 0, "解析": "作者对新计划持支持态度"},
        {"question": "（2019全国III卷）Which of the following best describes the main idea of the passage?", "options": ["The importance of environmental protection", "The history of environmental protection", "The methods of environmental protection", "The future of environmental protection"], "answer": 0, "解析": "文章主要讲环境保护的重要性"},
        {"question": "（2018全国III卷）According to the passage, what is the main cause of the problem?", "options": ["Human activity", "Natural disasters", "Climate change", "Pollution"], "answer": 0, "解析": "根据原文，问题的主要原因是人类活动"},
        {"question": "猜测生词词义时，最有效的线索是", "options": ["上下文语境", "词根词缀", "单词长度", "单词位置"], "answer": 0, "解析": "结合上下文语境是词义猜测最有效的方法"},
        {"question": "\"The word 'phenomenon' in paragraph 2 probably means\" 属于", "options": ["词义猜测题", "细节理解题", "推理判断题", "主旨大意题"], "answer": 0, "解析": "考查单词/短语含义属词义猜测题"},
    ],
    "完形填空·语境理解": [
        {"question": "完形填空的解题技巧不包括", "options": ["逐字翻译", "语境分析", "固定搭配", "逻辑推理"], "answer": 0, "解析": "逐字翻译不是完形填空的解题技巧"},
        {"question": "完形填空中，连接词的选择主要看", "options": ["上下文逻辑关系", "单词长度", "字母数量", "读音"], "answer": 0, "解析": "连接词的选择取决于上下文的逻辑关系"},
        {"question": "The weather was cold, _____ he wore a thick coat.", "options": ["so", "but", "and", "or"], "answer": 0, "解析": "前后句是因果关系，用so连接"},
        {"question": "完形填空需要注意", "options": ["上下文连贯", "语法正确", "词汇辨析", "以上都对"], "answer": 3, "解析": "完形填空需要注意上下文连贯、语法正确和词汇辨析"},
        {"question": "做完形填空的步骤是", "options": ["通读全文→逐句填空→检查", "直接填空", "先看选项", "翻译选项"], "answer": 0, "解析": "正确步骤是先通读全文，再逐句填空"},
        {"question": "I like reading, _____ my brother likes playing basketball.", "options": ["but", "so", "and", "or"], "answer": 0, "解析": "前后句是转折关系，用but连接"},
        {"question": "（2023全国甲卷）The old man walked slowly, _____ he was still able to reach the top of the mountain.", "options": ["but", "so", "and", "or"], "answer": 0, "解析": "前后句是转折关系，用but连接"},
        {"question": "（2022全国甲卷）She studied hard _____ she could pass the exam.", "options": ["so that", "because", "although", "when"], "answer": 0, "解析": "目的状语从句，用so that"},
        {"question": "（2021全国乙卷）_____ he is young, he knows a lot.", "options": ["Although", "Because", "If", "When"], "answer": 0, "解析": "让步状语从句，用although"},
        {"question": "（2020全国III卷）The more you practice, _____ you will become.", "options": ["the better", "better", "best", "the best"], "answer": 0, "解析": "the more...the more...结构"},
        {"question": "（2019全国III卷）He asked me _____ I had finished my homework.", "options": ["if", "that", "what", "which"], "answer": 0, "解析": "宾语从句，表示\"是否\"用if"},
        {"question": "（2018全国III卷）It is important _____ us to learn English well.", "options": ["for", "to", "of", "with"], "answer": 0, "解析": "It is important for sb to do sth"},
        {"question": "（2017全国III卷）She is good _____ playing the piano.", "options": ["at", "in", "on", "with"], "answer": 0, "解析": "be good at doing sth"},
        {"question": "（2016全国III卷）The book is different _____ what I expected.", "options": ["from", "to", "with", "for"], "answer": 0, "解析": "be different from"},
    ],
    "写作·应用文": [
        {"question": "英语书信的格式不包括", "options": ["标题", "称呼", "正文", "结尾"], "answer": 0, "解析": "英语书信通常没有标题"},
        {"question": "英语作文的评分标准包括", "options": ["内容、语言、结构", "字数、字体、标点", "词汇量、语法、拼写", "以上都对"], "answer": 3, "解析": "作文评分包括多个方面"},
        {"question": "邀请信的开头常用", "options": ["I'm writing to invite you...", "I have a good news...", "How are you?", "Long time no see"], "answer": 0, "解析": "邀请信常用I'm writing to invite you开头"},
        {"question": "英文通知通常以什么开头", "options": ["Notice/Attention", "Dear Sir", "How are you", "Hello"], "answer": 0, "解析": "通知以Notice或Attention开头"},
        {"question": "申请信的正文应包含", "options": ["自我介绍和申请理由", "只有申请职位", "个人爱好", "家庭情况"], "answer": 0, "解析": "申请信应包含自我介绍和申请理由"},
    ],
    "写作·议论文": [
        {"question": "英语作文中，句型应", "options": ["多样化", "单一", "简单", "复杂"], "answer": 0, "解析": "作文句型应多样化"},
        {"question": "英语作文的结尾常用", "options": ["Looking forward to your reply", "Thank you", "Best wishes", "以上都对"], "answer": 3, "解析": "这些都是常用的结尾表达"},
        {"question": "英语议论文的三要素是", "options": ["论点、论据、论证", "开头、正文、结尾", "时间、地点、人物", "原因、过程、结果"], "answer": 0, "解析": "议论文的三要素是论点、论据、论证"},
        {"question": "议论文的段落结构一般为", "options": ["主题句—论证—结论", "铺垫—高潮—结局", "开头—经过—结尾", "问题—原因—结果"], "answer": 0, "解析": "议论文段落：主题句引出观点，论证支持，结论总结"},
        {"question": "议论文中，举例论证的作用是", "options": ["使论点更有说服力", "增加字数", "美化语言", "引入新话题"], "answer": 0, "解析": "举例论证使论点更具体、更有说服力"},
    ],
    "写作·记叙文": [
        {"question": "（2023全国甲卷）假定你是李华，你的英国朋友Peter来信询问你校近期举办的读书活动情况。请你回信介绍活动的时间、内容和意义。", "options": ["书信格式+活动介绍", "记叙文格式", "议论文格式", "说明文格式"], "answer": 0, "解析": "根据要求，应采用书信格式介绍活动"},
        {"question": "（2022全国甲卷）假定你是校广播站英语节目\"Talk and Talk\"的负责人李华。请你给外教Mr. Brown写一封邮件，邀请他参加节目。", "options": ["邀请信格式", "感谢信格式", "投诉信格式", "建议信格式"], "answer": 0, "解析": "根据要求，应写邀请信"},
        {"question": "（2021全国乙卷）你校正在组织英语作文比赛。请以\"Be smart online learners\"为题写一篇短文参赛。", "options": ["议论文格式", "记叙文格式", "说明文格式", "应用文格式"], "answer": 0, "解析": "以\"Be smart online learners\"为题写议论文"},
        {"question": "记叙文的六要素是", "options": ["时间、地点、人物、起因、经过、结果", "开头、正文、结尾", "论点、论据、论证", "引言、正文、结论"], "answer": 0, "解析": "记叙文六要素：5W1H"},
        {"question": "记叙文写作中，时间顺序的常用连接词是", "options": ["first, then, finally", "however, therefore", "because, since", "although, though"], "answer": 0, "解析": "first/then/finally表示时间先后顺序"},
    ],
    "写作·图表作文": [
        {"question": "（2020全国III卷）假定你是李华，你校将举办音乐节。请写一封邮件邀请你的英国朋友Allen参加，内容包括：时间、地点、活动安排。", "options": ["邀请信格式", "感谢信格式", "投诉信格式", "建议信格式"], "answer": 0, "解析": "根据要求，应写邀请信"},
        {"question": "（2019全国III卷）假定你是李华，你校英语俱乐部将举办\"读一本好书\"活动。请你用英语写一则通知。", "options": ["通知格式", "书信格式", "日记格式", "演讲稿格式"], "answer": 0, "解析": "根据要求，应写通知"},
        {"question": "（2018全国III卷）假定你是李华，你的英国朋友Peter想了解中国的传统节日。请你给他写一封信，介绍一个你最喜欢的传统节日。", "options": ["书信格式+节日介绍", "记叙文格式", "议论文格式", "说明文格式"], "answer": 0, "解析": "根据要求，应采用书信格式介绍节日"},
        {"question": "描述图表变化时，常用", "options": ["increase/decrease/remain stable", "good/bad", "big/small", "fast/slow"], "answer": 0, "解析": "描述数据变化用increase/decrease/remain stable"},
        {"question": "图表作文的结尾应", "options": ["总结趋势并分析原因", "重复开头内容", "罗列所有数据", "发表个人感慨"], "answer": 0, "解析": "图表作文结尾应总结趋势并简要分析原因"},
    ],
    "there be句型": [
        {"question": "There _____ a lot of people in the park.", "options": ["are", "is", "were", "was"], "answer": 0, "解析": "people是复数，be动词用are"},
        {"question": "There _____ some milk in the glass.", "options": ["is", "are", "were", "have"], "answer": 0, "解析": "milk不可数，be用is"},
        {"question": "There _____ a meeting tomorrow afternoon.", "options": ["will be", "is going to have", "has", "are"], "answer": 0, "解析": "there be的将来时用there will be"},
        {"question": "There used to _____ a temple here.", "options": ["be", "being", "been", "have"], "answer": 0, "解析": "there used to be结构表示\"过去有…\""},
        {"question": "_____ there any water in the bottle?", "options": ["Is", "Are", "Has", "Have"], "answer": 0, "解析": "water不可数，be用Is"},
    ],
    "直接引语与间接引语": [
        {"question": "He said, \"I am tired.\" → He said that he _____ tired.", "options": ["was", "is", "were", "had been"], "answer": 0, "解析": "间接引语中，一般现在时变为一般过去时"},
        {"question": "She asked, \"Do you like music?\" → She asked _____ I liked music.", "options": ["if", "that", "what", "when"], "answer": 0, "解析": "一般疑问句变间接引语用if/whether引导"},
        {"question": "He asked, \"Where are you going?\" → He asked where I _____ going.", "options": ["was", "am", "were", "had been"], "answer": 0, "解析": "时态倒退，are变was"},
        {"question": "She said, \"I will come tomorrow.\" → She said that she _____ come the next day.", "options": ["would", "will", "could", "might"], "answer": 0, "解析": "将来时will变would"},
        {"question": "He said, \"I have finished my homework.\" → He said that he _____ his homework.", "options": ["had finished", "has finished", "finished", "was finishing"], "answer": 0, "解析": "现在完成时变过去完成时"},
    ],
    "祈使句": [
        {"question": "_____ late for class again.", "options": ["Don't be", "Not be", "Don't", "No"], "answer": 0, "解析": "祈使句否定式：Don't+动词原形"},
        {"question": "_____ quiet, please.", "options": ["Be", "Being", "To be", "Are"], "answer": 0, "解析": "祈使句以动词原形开头"},
        {"question": "_____ the door, please.", "options": ["Please open", "Opening", "Opens", "To open"], "answer": 0, "解析": "祈使句用动词原形"},
        {"question": "Let's _____ shopping this afternoon.", "options": ["go", "going", "went", "to go"], "answer": 0, "解析": "Let's+动词原形表示建议"},
        {"question": "_____ afraid of making mistakes.", "options": ["Don't be", "Not be", "Don't", "Never"], "answer": 0, "解析": "祈使句否定：Don't be+形容词"},
    ],
    "倒装与强调": [
        {"question": "（2021全国乙卷）It is the first time that I _____ to Beijing.", "options": ["have been", "had been", "was", "am"], "answer": 0, "解析": "It is the first time that后接现在完成时"},
        {"question": "（2020全国III卷）He insisted that the meeting _____ held as scheduled.", "options": ["be", "was", "is", "would be"], "answer": 0, "解析": "insist表示\"坚持要求\"时，后接虚拟语气"},
        {"question": "Not until he came back _____ I know the truth.", "options": ["did", "do", "had", "was"], "answer": 0, "解析": "Not until位于句首，主句部分倒装"},
        {"question": "Only in this way _____ solve the problem.", "options": ["can we", "we can", "we could", "we will"], "answer": 0, "解析": "Only+状语位于句首，主句倒装"},
        {"question": "_____ beautiful the flowers are!", "options": ["How", "What", "What a", "So"], "answer": 0, "解析": "How+形容词引导感叹句"},
        {"question": "It is I who _____ responsible for this.", "options": ["am", "is", "are", "was"], "answer": 0, "解析": "强调句中，谓语与I一致用am"},
        {"question": "Hardly had I arrived home _____ it began to rain.", "options": ["when", "than", "then", "while"], "answer": 0, "解析": "hardly...when...固定搭配"},
    ],
    "语音基础": [
        {"question": "下列单词中，划线部分发音不同的是", "options": ["cake", "cat", "face", "name"], "answer": 1, "解析": "cat中的a发/æ/，其余发/eɪ/"},
        {"question": "英语音节的核心是", "options": ["元音", "辅音", "重音", "语调"], "answer": 0, "解析": "元音是音节的核心"},
        {"question": "下列单词重音在第一个音节的是", "options": ["'student", "to'day", "a'bout", "a'go"], "answer": 0, "解析": "student重音在第一个音节"},
        {"question": "升降调中，一般疑问句通常用", "options": ["升调", "降调", "平调", "升降调"], "answer": 0, "解析": "一般疑问句通常用升调"},
        {"question": "下列单词中s发音为/z/的是", "options": ["dogs", "cats", "books", "maps"], "answer": 0, "解析": "dogs中s在浊音后发/z/，其余在清音后发/s/"},
    ],
    "语法综合运用": [
        {"question": "下列句子中，语法正确的是", "options": ["He is taller than I.", "He is more taller than I.", "He is tall than me.", "He is more tall than me."], "answer": 0, "解析": "比较级taller前不加more，than后可用主格"},
        {"question": "\"Neither he nor I _____ right\"中应填", "options": ["am", "is", "are", "were"], "answer": 0, "解析": "就近原则，与I一致用am"},
        {"question": "下列句子中，属于复合句的是", "options": ["I think that he is right.", "I love you.", "He came and left.", "She sings well."], "answer": 0, "解析": "含that宾语从句是复合句"},
        {"question": "\"It is no use crying over spilt milk\"中的\"crying\"是", "options": ["动名词作主语", "现在分词", "过去分词", "不定式"], "answer": 0, "解析": "it作形式主语，动名词是真正主语"},
        {"question": "下列表示\"虽然\"的连词使用正确的是", "options": ["Although he is old, he works hard.", "Although he is old, but he works hard.", "Though old, but he works hard.", "He is old, although he works hard."], "answer": 0, "解析": "Although不与but连用"},
    ],
}


def get_questions():
    return questions

def get_kp_names():
    return list(questions.keys())

def get_question_count():
    return sum(len(v) for v in questions.values())
