# -*- coding: utf-8 -*-
"""一轮自检题种子（方案 5.3 来源约束）。

全部 source_type='自主命题练习'——自编诊断题，永不带年份卷别，
不冒充真题。每个知识点 2—3 题，用于当天学完后的即时自检：
合上书能不能做对，比"看懂了"诚实得多。

题量不大是故意的：一轮的目标是唤醒框架，不是刷题量。
真正的练习量在第二阶段（教辅+真题，届时批量录入）。
"""
from __future__ import annotations

import sqlite3

from core import db

# (kp_id, [ {qtype, difficulty, stem, options, answer, analysis}, ... ])
SELF_QUIZ: list[tuple[str, list[dict]]] = [
    # ---------------- 数学 ----------------
    ("mat_jr_num", [
        dict(qtype="填空题", difficulty=2,
             stem="计算：√18 − 2√8 + |1−√2| = ＿＿＿＿",
             answer="√2 − 1",
             analysis="√18=3√2，2√8=4√2，|1−√2|=√2−1，合计 (3−4+1)√2−1=√2−1。"),
        dict(qtype="选择题", difficulty=2,
             stem="下列各数：π/2，√16，0.3̇，22/7，∛9，其中无理数的个数是",
             options=["A. 1个", "B. 2个", "C. 3个", "D. 4个"],
             answer="B",
             analysis="π/2 与 ∛9 是无理数；√16=4、22/7、循环小数均为有理数。"),
    ]),
    ("mat_jr_alg", [
        dict(qtype="填空题", difficulty=2,
             stem="因式分解：x³ − 4x = ＿＿＿＿；a² − 2ab + b² − 9 = ＿＿＿＿",
             answer="x(x+2)(x−2)；(a−b+3)(a−b−3)",
             analysis="先提公因式再用公式；第二题分组：(a−b)²−3²。"),
        dict(qtype="选择题", difficulty=3,
             stem="若 x²+mx+6 可分解为两个一次整式之积，则整数 m 的值共有",
             options=["A. 2个", "B. 4个", "C. 6个", "D. 无数个"],
             answer="B",
             analysis="6=1×6=2×3=(−1)(−6)=(−2)(−3)，m=±7、±5 共 4 个。"),
    ]),
    ("mat_jr_frac", [
        dict(qtype="填空题", difficulty=3,
             stem="化简：(1/x − 1) ÷ (x²−1)/x = ＿＿＿＿（x≠0, ±1）",
             answer="−1/(x+1)",
             analysis="通分得 (1−x)/x，乘 x/[(x−1)(x+1)]，约去 (1−x)=−(x−1)。"),
        dict(qtype="填空题", difficulty=2,
             stem="使二次根式 √(x−3) 有意义的 x 取值范围是 ＿＿＿＿；√(12) 化为最简根式是 ＿＿＿＿",
             answer="x≥3；2√3",
             analysis="被开方数非负；12=4×3 提出平方因子。"),
    ]),
    ("mat_jr_eq", [
        dict(qtype="填空题", difficulty=2,
             stem="解方程：2/(x−1) = 3/x，x = ＿＿＿＿",
             answer="3",
             analysis="交叉相乘 2x=3(x−1)，x=3，验根分母不为零。"),
        dict(qtype="选择题", difficulty=3,
             stem="不等式 3x−7 ≥ 2(x+1) 的最小整数解是",
             options=["A. 8", "B. 9", "C. 10", "D. 11"],
             answer="B",
             analysis="3x−7≥2x+2 → x≥9。"),
    ]),
    ("mat_jr_func1", [
        dict(qtype="填空题", difficulty=3,
             stem="一次函数 y=kx+b 过点 (0,−1) 与 (2,3)，则 k=＿＿，b=＿＿；该直线与 x 轴交点为＿＿",
             answer="k=2, b=−1；(1/2, 0)",
             analysis="待定系数法；令 y=0 解 x。"),
        dict(qtype="选择题", difficulty=3,
             stem="反比例函数 y=6/x 的图象上一点 P 到两坐标轴距离之和为 5，则 P 的横坐标为",
             options=["A. 2 或 3", "B. 仅 2", "C. 6 或 −1", "D. 1 或 6"],
             answer="A",
             analysis="|x|+|6/x|=5，同号时 x+6/x=5 → x=2 或 3。"),
    ]),
    ("mat_jr_quad", [
        dict(qtype="填空题", difficulty=3,
             stem="抛物线 y=x²−4x+3 的顶点坐标是＿＿，与 x 轴交点是＿＿",
             answer="顶点(2,−1)；(1,0) 与 (3,0)",
             analysis="配方 (x−2)²−1；因式分解 (x−1)(x−3)。"),
        dict(qtype="选择题", difficulty=4,
             stem="二次函数 y=ax²+bx+c 图象开口向下、对称轴 x=1、过点(3,0)，则 y>0 时 x 的范围是",
             options=["A. −1<x<3", "B. x<−1 或 x>3", "C. 0<x<3", "D. −3<x<1"],
             answer="A",
             analysis="对称性：另一零点为 x=−1，开口向上区间在两根之间。"),
    ]),
    ("mat_jr_geo", [
        dict(qtype="填空题", difficulty=2,
             stem="直角三角形两直角边为 6 和 8，斜边上的高为＿＿，斜边长为＿＿",
             answer="斜边 10，高 4.8",
             analysis="勾股定理；面积法 h=6×8/10。"),
        dict(qtype="选择题", difficulty=3,
             stem="一个等腰三角形的两边长为 3 和 7，则它的周长为",
             options=["A. 13", "B. 17", "C. 13 或 17", "D. 21"],
             answer="B",
             analysis="3+3<7 不成立，只能 7+7+3=17。分类讨论必须验三角形不等式。"),
    ]),
    ("mat_jr_sim", [
        dict(qtype="填空题", difficulty=3,
             stem="sin30° + cos60° − tan45° = ＿＿＿；在 Rt△ABC 中 ∠C=90°，AC=4，BC=3，则 sinA=＿＿",
             answer="0；3/5",
             analysis="0.5+0.5−1=0；斜边 5，sinA=对边/斜边=BC/AB。"),
        dict(qtype="选择题", difficulty=3,
             stem="两相似三角形相似比为 2:3，则面积比为",
             options=["A. 2:3", "B. 4:9", "C. 3:2", "D. 8:27"],
             answer="B",
             analysis="面积比等于相似比平方；体积比才是立方。"),
    ]),
    ("mat_jr_circle", [
        dict(qtype="填空题", difficulty=3,
             stem="半径为 2 的圆中，60° 圆心角所对弧长为＿＿，扇形面积为＿＿",
             answer="2π/3；2π/3",
             analysis="l=θr=π/3×2；S=½lr。"),
        dict(qtype="选择题", difficulty=3,
             stem="同圆中，一条弦所对的圆周角是 40°，则这条弦所对的圆心角是",
             options=["A. 20°", "B. 40°", "C. 80°", "D. 140°"],
             answer="C",
             analysis="圆周角定理：同弧所对圆心角是圆周角的 2 倍。"),
    ]),
    ("mat_jr_stat", [
        dict(qtype="填空题", difficulty=2,
             stem="数据 2, 3, 5, 5, 7 的平均数是＿＿，中位数是＿＿，众数是＿＿",
             answer="4.4；5；5",
             analysis="平均=22/5；排序居中为 5；出现次数最多为 5。"),
        dict(qtype="选择题", difficulty=3,
             stem="同时掷两枚均匀硬币，恰有一枚正面朝上的概率是",
             options=["A. 1/4", "B. 1/2", "C. 3/4", "D. 1"],
             answer="B",
             analysis="样本空间 4 种，符合 2 种（正反、反正）。"),
    ]),
    ("mat_set", [
        dict(qtype="填空题", difficulty=2,
             stem="设 A={x | x²−3x+2=0}，B={1,2,3}，则 A∩B=＿＿，A∪B=＿＿",
             answer="{1,2}；{1,2,3}",
             analysis="A={1,2}。"),
        dict(qtype="选择题", difficulty=3,
             stem="“p: x>1” 是 “q: x²>x” 的",
             options=["A. 充分不必要条件", "B. 必要不充分条件", "C. 充要条件", "D. 既不充分也不必要"],
             answer="A",
             analysis="x>1⇒x²>x 成立；x²>x 解为 x<0 或 x>1，推不回 x>1。"),
    ]),
    ("mat_func", [
        dict(qtype="填空题", difficulty=3,
             stem="函数 f(x)=√(x+1)+1/(x−2) 的定义域是＿＿",
             answer="[−1,2)∪(2,+∞)",
             analysis="x+1≥0 且 x−2≠0。"),
        dict(qtype="选择题", difficulty=4,
             stem="下列函数中，既是奇函数又在 (0,+∞) 上单调递增的是",
             options=["A. y=x²", "B. y=x³", "C. y=1/x", "D. y=x+1"],
             answer="B",
             analysis="x³ 奇函数且递增；1/x 在正半轴递减；x² 偶；x+1 非奇非偶。"),
    ]),
    ("mat_exp_log", [
        dict(qtype="填空题", difficulty=3,
             stem="计算：log₂8 + lg25 + lg4 + 2^(log₂3) = ＿＿＿",
             answer="3+2+3=8",
             analysis="log₂8=3；lg25+lg4=lg100=2；a^(log_a N)=N。"),
        dict(qtype="选择题", difficulty=4,
             stem="设 a=0.3², b=2^0.3, c=log₂0.3，则 a, b, c 的大小关系是",
             options=["A. a<b<c", "B. c<a<b", "C. c<b<a", "D. a<c<b"],
             answer="B",
             analysis="c<0<a<1<b。与 0、1 比较是通法。"),
    ]),
    ("mat_trig", [
        dict(qtype="填空题", difficulty=3,
             stem="已知 sinα=3/5 且 α 是第二象限角，则 cosα=＿＿，tanα=＿＿",
             answer="−4/5；−3/4",
             analysis="平方关系取负；tan=sin/cos。符号由象限定。"),
        dict(qtype="选择题", difficulty=3,
             stem="函数 y=2sin(2x+π/3) 的最小正周期和振幅分别是",
             options=["A. π 和 2", "B. 2π 和 2", "C. π 和 1", "D. 4π 和 2"],
             answer="A",
             analysis="T=2π/ω=π；振幅 |A|=2。"),
    ]),
    ("mat_trig_id", [
        dict(qtype="填空题", difficulty=3,
             stem="用二倍角公式化简：cos²15° − sin²15° = ＿＿＿；sin15°·cos15° = ＿＿＿",
             answer="√3/2；1/4",
             analysis="cos²α−sin²α=cos2α=cos30°=√3/2；sinα·cosα=½sin2α=½sin30°=1/4。"),
        dict(qtype="选择题", difficulty=4,
             stem="已知 tanα=2，则 (sinα+cosα)/(sinα−cosα) = ",
             options=["A. 3", "B. 1/3", "C. −3", "D. 2"],
             answer="A",
             analysis="分子分母同除 cosα 得 (tanα+1)/(tanα−1)=3。"),
    ]),
    ("mat_vector", [
        dict(qtype="填空题", difficulty=3,
             stem="已知 a=(1,2), b=(−3,m)，若 a∥b 则 m=＿＿；若 a⊥b 则 m=＿＿",
             answer="m=−6；m=3/2",
             analysis="平行：1×m−2×(−3)=0；垂直：−3+2m=0。"),
        dict(qtype="选择题", difficulty=4,
             stem="|a|=2, |b|=1, a 与 b 夹角 60°，则 |a+2b| = ",
             options=["A. 2√3", "B. √3", "C. 12", "D. 4"],
             answer="A",
             analysis="平方展开：4+8·cos60°+4=12。先平方再开方是通法。"),
    ]),
    ("mat_vector_dec", [
        dict(qtype="填空题", difficulty=3,
             stem="力 F=(3,4) 作用在斜面上，斜面方向单位向量 e=(4/5,3/5)，则 F 沿 e 方向的分量大小为＿＿",
             answer="F·e=12/5+12/5=24/5",
             analysis="投影 = F·e。向量分解的物理原型。"),
    ]),
    ("mat_seq", [
        dict(qtype="填空题", difficulty=3,
             stem="等差数列 {aₙ} 中 a₃=7, a₇=15，则公差 d=＿＿，前 10 项和 S₁₀=＿＿",
             answer="d=2；S₁₀=110",
             analysis="4d=8；a₁=3，S=10×3+45×2。"),
        dict(qtype="选择题", difficulty=4,
             stem="等比数列 {aₙ} 中 a₂=2, a₅=16，则公比 q= ，a₈= ",
             options=["A. q=2, a₈=128", "B. q=4, a₈=512", "C. q=2, a₈=64", "D. q=1/2, a₈=1/8"],
             answer="A",
             analysis="q³=8 → q=2；a₈=a₅q³=128。"),
    ]),
    ("mat_ineq", [
        dict(qtype="填空题", difficulty=3,
             stem="已知 x>0, y>0 且 x+y=4，则 xy 的最大值为＿＿；1/x + 4/y 的最小值为＿＿",
             answer="4；9/4",
             analysis="均值不等式；第二题乘 1 法：(x+y)/4·(1/x+4/y)≥(1+2)²/4。"),
        dict(qtype="选择题", difficulty=4,
             stem="若关于 x 的不等式 x²−ax+4>0 对一切实数恒成立，则 a 的范围是",
             options=["A. −4<a<4", "B. a<−4 或 a>4", "C. −4≤a≤4", "D. 0<a<4"],
             answer="A",
             analysis="Δ=a²−16<0。恒成立问题转化为判别式。"),
    ]),
    ("mat_solid", [
        dict(qtype="填空题", difficulty=3,
             stem="棱长为 2 的正方体外接球表面积为＿＿；一个圆锥底面半径 3、母线 5，其侧面积为＿＿",
             answer="12π；15π",
             analysis="体对角线=2R=2√3；侧面积 πrl。"),
        dict(qtype="选择题", difficulty=4,
             stem="设 l, m 为两条不同直线，α, β 为两个不同平面，下列命题正确的是",
             options=["A. l∥α, m∥α ⇒ l∥m", "B. l⊥α, l⊥m ⇒ m∥α", "C. l⊥α, l∥β ⇒ α⊥β", "D. α∥β, l⊂α, m⊂β ⇒ l∥m"],
             answer="C",
             analysis="线面垂直判定与性质逐一检验；A 可异面，B 或 m⊂α，D 可异面。"),
    ]),
    ("mat_line_eq", [
        dict(qtype="填空题", difficulty=3,
             stem="过点 (1,2) 且与直线 2x−y+1=0 平行的直线方程是＿＿；点 (0,0) 到直线 3x+4y−10=0 的距离为＿＿",
             answer="2x−y=0；2",
             analysis="平行设 2x−y+c=0 代点；距离公式 |−10|/5。"),
    ]),
    ("mat_circle_eq", [
        dict(qtype="填空题", difficulty=3,
             stem="圆 x²+y²−4x+6y=0 的圆心为＿＿，半径为＿＿",
             answer="(2,−3)；√13",
             analysis="配方 (x−2)²+(y+3)²=13。"),
    ]),
    ("mat_conic", [
        dict(qtype="填空题", difficulty=4,
             stem="椭圆 x²/25 + y²/9 = 1 的焦点坐标为＿＿，离心率为＿＿",
             answer="(±4,0)；4/5",
             analysis="c²=a²−b²=16；e=c/a。"),
        dict(qtype="选择题", difficulty=4,
             stem="双曲线 x²/4 − y²/9 = 1 的渐近线方程是",
             options=["A. y=±(3/2)x", "B. y=±(2/3)x", "C. y=±(9/4)x", "D. x=±(2/3)y"],
             answer="A",
             analysis="令 x²/4=y²/9 解出 y=±(b/a)x，b/a=3/2。"),
    ]),
    ("mat_parabola", [
        dict(qtype="填空题", difficulty=3,
             stem="抛物线 y²=8x 的焦点坐标为＿＿，准线方程为＿＿",
             answer="(2,0)；x=−2",
             analysis="2p=8，p=4，焦点(p/2,0)。"),
    ]),
    ("mat_space_vec", [
        dict(qtype="填空题", difficulty=4,
             stem="正方体棱长为 2，建立空间直角坐标系后，体对角线方向向量为(2,2,2)，则它与底面所成角的余弦值为＿＿",
             answer="√6/3",
             analysis="底面法向量 (0,0,1)，sinθ=|cos<方向,法>|=√3/3，cosθ=√6/3。"),
    ]),
    ("mat_count", [
        dict(qtype="填空题", difficulty=3,
             stem="从 5 名男生 3 名女生中选 3 人，恰有 1 名女生的选法有＿＿种；(x+1/x)⁶ 展开式常数项为＿＿",
             answer="C₅¹·C₃²=30；C₆³=20",
             analysis="先选后排分清；通项 T_{r+1}=C₆ʳx^{6−2r}，令 6−2r=0。"),
    ]),
    ("mat_prob", [
        dict(qtype="填空题", difficulty=3,
             stem="袋中 3 红 2 白，不放回取两球，恰一红的概率为＿＿",
             answer="3/5",
             analysis="C₃¹C₂¹/C₅²=6/10。"),
        dict(qtype="选择题", difficulty=4,
             stem="某射手单次命中率 0.8，独立射击 3 次，恰有 2 次命中的概率是",
             options=["A. 0.384", "B. 0.512", "C. 0.192", "D. 0.96"],
             answer="A",
             analysis="C₃²·0.8²·0.2=3×0.64×0.2=0.384。二项分布公式。"),
    ]),
    ("mat_stat2", [
        dict(qtype="填空题", difficulty=2,
             stem="回归直线 ŷ=b̂x+â 必过样本点的中心，即点(＿＿, ＿＿)；相关系数 r 越接近 1 表示＿＿",
             answer="(x̄, ȳ)；正线性相关越强",
             analysis="回归方程基本性质；r 的符号与强度。"),
    ]),
    ("mat_deriv", [
        dict(qtype="填空题", difficulty=4,
             stem="f(x)=x³−3x²+1 的单调递减区间是＿＿，极大值为＿＿",
             answer="(0,2)；f(0)=1",
             analysis="f'=3x²−6x=3x(x−2)，两根之间为负。"),
        dict(qtype="选择题", difficulty=5,
             stem="曲线 y=x·lnx 在点 (1,0) 处的切线方程是",
             options=["A. y=x−1", "B. y=x+1", "C. y=0", "D. y=2x−2"],
             answer="A",
             analysis="y'=lnx+1，在 x=1 处斜率 1。"),
    ]),
    ("mat_complex", [
        dict(qtype="填空题", difficulty=2,
             stem="计算：(1+2i)/(1−i) = ＿＿＿；i²⁰²⁷ = ＿＿＿",
             answer="−1/2 + 3/2 i；−i",
             analysis="分子分母同乘 (1+i)：(1+2i)(1+i)/2=(−1+3i)/2；2027=4×506+3，i³=−i。"),
    ]),
    ("mat_solve_tri", [
        dict(qtype="填空题", difficulty=4,
             stem="△ABC 中 a=2, b=√7, ∠A=60°，则 sinB=＿＿，c=＿＿",
             answer="sinB=√21/4；c=3",
             analysis="正弦定理求 sinB；余弦定理 a²=b²+c²−2bc·cosA 解 c。"),
    ]),
    ("mat_eq_sys", [
        dict(qtype="填空题", difficulty=2,
             stem="解方程组：x+y=5, x−y=1；则 x=＿＿, y=＿＿",
             answer="x=3, y=2",
             analysis="加减消元。化学计算、电路方程都会反复用到。"),
    ]),
    # ---------------- 物理 ----------------
    ("phy_jr_mech", [
        dict(qtype="填空题", difficulty=2,
             stem="质量为 2kg 的物体所受重力为＿＿N（g 取 10N/kg）；重力的方向＿＿",
             answer="20N；竖直向下",
             analysis="G=mg。方向是“竖直向下”而非“垂直向下”——表述规范要求。"),
    ]),
    ("phy_jr_motion", [
        dict(qtype="选择题", difficulty=2,
             stem="关于惯性，下列说法正确的是",
             options=["A. 速度越大惯性越大", "B. 惯性只与质量有关", "C. 静止物体没有惯性", "D. 月球上惯性消失"],
             answer="B",
             analysis="惯性唯一量度是质量。概念题必须表述精确。"),
    ]),
    ("phy_jr_pressure", [
        dict(qtype="填空题", difficulty=3,
             stem="水深 2m 处水产生的压强为＿＿Pa（ρ=1.0×10³kg/m³, g=10）；载重汽车多轮子的目的是＿＿",
             answer="2×10⁴ Pa；增大受力面积减小压强",
             analysis="p=ρgh；压强定义的应用。"),
    ]),
    ("phy_jr_work", [
        dict(qtype="填空题", difficulty=3,
             stem="用 10N 水平力把物体沿力方向推动 2m，做功＿＿J；物体沿斜面下滑时重力做功把＿＿能转化为＿＿能",
             answer="20J；重力势；动",
             analysis="W=Fs·cosθ，力与位移同向。能量转化表述要完整。"),
    ]),
    ("phy_jr_circuit", [
        dict(qtype="选择题", difficulty=2,
             stem="两个灯泡并联接在电源上，则",
             options=["A. 通过两灯电流一定相等", "B. 两灯两端电压相等", "C. 断开一盏另一盏也不亮", "D. 并联总电阻大于任一支路"],
             answer="B",
             analysis="并联电压相等；电流取决于电阻。串联才互相影响。"),
    ]),
    ("phy_jr_ohm", [
        dict(qtype="填空题", difficulty=3,
             stem="电阻 10Ω 两端加 6V 电压，电流为＿＿A；若电压变为 0，电阻为＿＿Ω",
             answer="0.6A；仍为 10Ω",
             analysis="I=U/R；电阻由导体本身决定，与电压无关——高频概念陷阱。"),
    ]),
    ("phy_jr_power", [
        dict(qtype="填空题", difficulty=3,
             stem="标有“220V 1000W”的电热水器正常工作电流约为＿＿A，正常工作 10 分钟耗电＿＿度",
             answer="约 4.5A；1/6 度≈0.17 度",
             analysis="I=P/U；W=Pt=1kW×(1/6)h。度=kW·h。"),
    ]),
    ("phy_jr_magnet", [
        dict(qtype="选择题", difficulty=2,
             stem="关于磁场和磁感线，正确的是",
             options=["A. 磁感线是磁场中真实存在的曲线", "B. 小磁针 N 极受力方向即该点磁场方向", "C. 地磁南极在地理南极处", "D. 两条磁感线可以相交"],
             answer="B",
             analysis="磁感线是模型非真实；地磁南极在地理北极附近；磁感线不相交。"),
    ]),
    ("phy_jr_light", [
        dict(qtype="填空题", difficulty=2,
             stem="筷子在水中“折断”是光的＿＿现象；小孔成像是光的＿＿形成的；平面镜成＿＿（虚实）像",
             answer="折射；直线传播；虚",
             analysis="三类光现象区分是初中必考。"),
    ]),
    ("phy_jr_heat", [
        dict(qtype="填空题", difficulty=2,
             stem="水的比热容较大，白天海边沙子比海水热，是因为吸收相同热量时沙子＿＿更大；1kg 水升温 10℃ 吸热＿＿J（c=4.2×10³）",
             answer="温度变化（升温）；4.2×10⁴",
             analysis="Q=cmΔt；比热容应用。"),
    ]),
    ("phy_kinematics", [
        dict(qtype="填空题", difficulty=3,
             stem="汽车以 2m/s² 由静止出发，第 3s 末速度为＿＿m/s，前 3s 位移为＿＿m；刹车后 6s 内位移问题必须先判断＿＿",
             answer="6；9；刹车停止时间（是否提前停下）",
             analysis="v=at, x=½at²；刹车问题“时间陷阱”是高频错误。"),
        dict(qtype="选择题", difficulty=4,
             stem="某物体做匀加速直线运动，第 1s 内位移 2m，第 3s 内位移 6m，则加速度为",
             options=["A. 1 m/s²", "B. 2 m/s²", "C. 3 m/s²", "D. 4 m/s²"],
             answer="B",
             analysis="相邻等时间间隔位移差 aT²：x₃−x₁=2aT² → a=2。"),
    ]),
    ("phy_force", [
        dict(qtype="解答题", difficulty=3,
             stem="画出静止在粗糙斜面上物体的受力示意图（文字描述各力方向），并说明：物体所受摩擦力方向沿斜面＿＿；支持力方向＿＿",
             answer="摩擦力沿斜面向上；支持力垂直斜面向上；重力竖直向下",
             analysis="受力分析顺序：一重二弹三摩擦；方向表述必须精确。"),
    ]),
    ("phy_newton2", [
        dict(qtype="填空题", difficulty=4,
             stem="质量 2kg 物体受水平合力 F=6N，加速度为＿＿m/s²；若 2s 后撤去 F，物体因摩擦以 1m/s² 减速，还能滑行＿＿m",
             answer="3；9",
             analysis="a=F/m；撤去时 v=6m/s，x=v²/2a=36/2=9。多过程问题分阶段。"),
    ]),
    ("phy_curve", [
        dict(qtype="选择题", difficulty=4,
             stem="平抛运动水平位移由哪些因素决定",
             options=["A. 仅初速度", "B. 仅高度", "C. 初速度和高度", "D. 质量"],
             answer="C",
             analysis="x=v₀t，t 由高度决定 h=½gt²。平抛分解为水平匀速+竖直自由落体。"),
    ]),
    ("phy_gravity", [
        dict(qtype="填空题", difficulty=4,
             stem="近地卫星环绕速度约＿＿km/s（第一宇宙速度）；同步卫星轨道必须在＿＿正上方，其周期 T=＿＿",
             answer="7.9；赤道；24h（与地球自转同步）",
             analysis="GMm/r²=mv²/r；同步三定：定周期定轨道平面定高度。"),
    ]),
    ("phy_work_power", [
        dict(qtype="填空题", difficulty=3,
             stem="汽车恒定功率启动，速度增大时牵引力＿＿；达到最大速度时加速度为＿＿，此时 F＿＿f（填>、=、<）",
             answer="减小；0；=",
             analysis="P=Fv；a=0 时合力为零。机车启动双模型是必考。"),
    ]),
    ("phy_energy", [
        dict(qtype="填空题", difficulty=4,
             stem="光滑曲面高 h 处静止滑下，底端速度 v=＿＿；质量 m 的小球从桌面（高 H）以 v₀ 水平抛出，落地动能为＿＿（取地面为零势能面）",
             answer="√(2gh)；½mv₀²+mgH",
             analysis="动能定理/机械能守恒；只有重力做功时路径无关。"),
    ]),
    ("phy_momentum", [
        dict(qtype="填空题", difficulty=4,
             stem="质量 2kg、速度 3m/s 的球与静止的 1kg 球发生完全非弹性碰撞，碰后共同速度为＿＿m/s；系统损失的动能为＿＿J",
             answer="2；3",
             analysis="动量守恒 2×3=(2+1)v；ΔEk=½·2·9−½·3·4=9−6=3。碰撞三分类。"),
    ]),
    ("phy_efield", [
        dict(qtype="选择题", difficulty=4,
             stem="关于电场强度 E=F/q，下列说法正确的是",
             options=["A. E 与 F 成正比与 q 成反比", "B. E 由电场本身决定，与试探电荷无关", "C. 电场线方向就是电荷受力方向", "D. E 的方向与负电荷受力方向相同"],
             answer="B",
             analysis="比值定义法物理量与定义量无关（同密度、电阻）；电场线方向是正电荷受力方向。"),
        dict(qtype="填空题", difficulty=4,
             stem="匀强电场场强 100V/m，沿电场线方向 A、B 相距 2cm，则 U_AB=＿＿V；电子（e=1.6×10⁻¹⁹C）从 A 到 B 电场力做功＿＿J",
             answer="2V；−3.2×10⁻¹⁹",
             analysis="U=Ed；负电荷逆着电场力做负功。"),
    ]),
    ("phy_circuit", [
        dict(qtype="填空题", difficulty=3,
             stem="电源电动势 6V、内阻 1Ω，外接 2Ω 电阻，回路电流为＿＿A，路端电压为＿＿V",
             answer="2；4",
             analysis="闭合电路欧姆定律 I=E/(R+r)；U=E−Ir。"),
    ]),
    ("phy_bfield", [
        dict(qtype="选择题", difficulty=4,
             stem="带电粒子垂直进入匀强磁场，仅受洛伦兹力，则粒子做",
             options=["A. 类平抛运动", "B. 匀速圆周运动", "C. 匀加速直线运动", "D. 变加速圆周运动"],
             answer="B",
             analysis="洛伦兹力始终垂直速度，只改方向不改大小。左手定则判方向（负电荷四指反向）。"),
    ]),
    ("phy_emind", [
        dict(qtype="填空题", difficulty=4,
             stem="感应电流的方向总是阻碍引起它的＿＿的变化——这是＿＿定律；导线棒在磁场中切割磁感线产生的电动势 E=＿＿（B、L、v 互相垂直）",
             answer="磁通量；楞次；BLv",
             analysis="楞次定律“增反减同”；E=BLv 是动生电动势。"),
    ]),
    ("phy_ac", [
        dict(qtype="填空题", difficulty=3,
             stem="正弦交流电峰值 311V，有效值约＿＿V；变压器原副线圈匝数比 2:1，副线圈输出电压是输入的＿＿倍",
             answer="220；1/2",
             analysis="U=Um/√2；U₁/U₂=n₁/n₂。"),
    ]),
    ("phy_wave", [
        dict(qtype="填空题", difficulty=3,
             stem="波速 4m/s、波长 2m，周期为＿＿s；机械波传播过程中介质质点＿＿（填“随波迁移”或“不随波迁移”）",
             answer="0.5；不随波迁移",
             analysis="T=λ/v；波传的是振动形式和能量，质点只振动。"),
    ]),
    ("phy_optics", [
        dict(qtype="选择题", difficulty=3,
             stem="光从空气斜射入水中，保持不变的量是",
             options=["A. 波长", "B. 波速", "C. 频率", "D. 传播方向"],
             answer="C",
             analysis="频率由光源决定；v 变小、λ 变小、方向偏折。"),
    ]),
    ("phy_thermal", [
        dict(qtype="填空题", difficulty=3,
             stem="温度是分子＿＿动能的标志；1mol 任何理想气体在标准状况下体积约＿＿L；布朗运动是＿＿（填“分子运动”或“固体小颗粒运动”）",
             answer="平均；22.4；固体小颗粒运动",
             analysis="热学概念辨析：布朗运动反映液体分子无规则运动但不是分子本身运动。"),
    ]),
    ("phy_modern", [
        dict(qtype="填空题", difficulty=3,
             stem="光电效应现象说明光具有＿＿性；核反应 ²³⁵U+n→¹⁴⁴Ba+⁸⁹Kr+3＿＿ 是＿＿（裂变/聚变）",
             answer="粒子（量子）；中子；裂变",
             analysis="爱因斯坦光子说；重核裂变放出多个中子可发生链式反应。"),
    ]),
    # ---------------- 化学 ----------------
    ("che_jr_matter", [
        dict(qtype="选择题", difficulty=2,
             stem="下列变化属于化学变化的是",
             options=["A. 石蜡熔化", "B. 酒精挥发", "C. 铁生锈", "D. 瓷碗破碎"],
             answer="C",
             analysis="化学变化本质是有新物质生成。"),
    ]),
    ("che_jr_atom", [
        dict(qtype="填空题", difficulty=2,
             stem="钠原子质子数 11、中子数 12，则其质量数约为＿＿，核外电子数为＿＿；相对原子质量≈＿＿",
             answer="23；11；23",
             analysis="质量数=质子+中子；原子中质子数=核外电子数。"),
    ]),
    ("che_jr_formula", [
        dict(qtype="填空题", difficulty=3,
             stem="写出化学式：氧化铝＿＿；氢氧化亚铁＿＿；标出高锰酸钾中锰元素化合价：K⁺M̄nO₄（锰为＿＿价）",
             answer="Al₂O₃；Fe(OH)₂；+7",
             analysis="化合价代数和为零；KMnO₄ 中 (+1)+x+4×(−2)=0 → x=+7。"),
    ]),
    ("che_jr_equation", [
        dict(qtype="填空题", difficulty=3,
             stem="配平并写出条件：＿＿Fe + ＿＿H₂O(g) →(高温) ＿＿Fe₃O₄ + ＿＿H₂↑",
             answer="3Fe + 4H₂O(g) =(高温)= Fe₃O₄ + 4H₂↑",
             analysis="观察法配平；气体符号与条件是采分点（表述不规范扣分项）。"),
        dict(qtype="填空题", difficulty=3,
             stem="实验室制 CO₂ 的化学方程式：＿＿；不用稀硫酸与大理石反应的原因是＿＿",
             answer="CaCO₃ + 2HCl = CaCl₂ + H₂O + CO₂↑；生成微溶 CaSO₄ 覆盖固体阻止反应",
             analysis="反应原理+实验细节双考点。"),
    ]),
    ("che_jr_solution", [
        dict(qtype="填空题", difficulty=3,
             stem="20℃ 时 NaCl 溶解度 36g，该温度下饱和溶液溶质质量分数为＿＿（保留一位小数）；将 50g 10% 溶液稀释到 5% 需加水＿＿g",
             answer="26.5%；50",
             analysis="w=36/136；稀释溶质不变：50×0.1=(50+m)×0.05。"),
    ]),
    ("che_jr_acid", [
        dict(qtype="填空题", difficulty=3,
             stem="写出离子方程式：盐酸与氢氧化钠＿＿；碳酸钙与盐酸＿＿",
             answer="H⁺ + OH⁻ = H₂O；CaCO₃ + 2H⁺ = Ca²⁺ + H₂O + CO₂↑",
             analysis="强酸强碱拆，难溶物不拆——拆分规则是离子方程式核心。"),
    ]),
    ("che_jr_metal", [
        dict(qtype="选择题", difficulty=3,
             stem="把铁片放入下列溶液中，溶液质量减轻的是",
             options=["A. 稀盐酸", "B. CuSO₄ 溶液", "C. FeCl₃ 溶液", "D. ZnSO₄ 溶液"],
             answer="B",
             analysis="Fe+CuSO₄：每溶 56 份铁析出 64 份铜，溶液变轻。金属活动性顺序应用。"),
    ]),
    ("che_mole", [
        dict(qtype="填空题", difficulty=3,
             stem="4.9g H₂SO₄ 的物质的量为＿＿mol，含氧原子＿＿mol，含氢原子约＿＿个",
             answer="0.05；0.2；6.02×10²²",
             analysis="n=m/M；1mol H₂SO₄ 含 4mol O、2mol H。"),
        dict(qtype="选择题", difficulty=4,
             stem="设 N_A 为阿伏加德罗常数，下列叙述正确的是",
             options=["A. 标准状况下 22.4L H₂O 含 N_A 个分子", "B. 0.1mol/L NaCl 溶液含 0.1N_A 个 Na⁺", "C. 32g O₂ 与 O₃ 混合气含 2N_A 个氧原子", "D. 1mol Fe 与足量盐酸反应转移 3N_A 个电子"],
             answer="C",
             analysis="A 标况水非气体；B 缺体积；D Fe→Fe²⁺ 转移 2mol。NA 题六大陷阱。"),
    ]),
    ("che_ion", [
        dict(qtype="选择题", difficulty=4,
             stem="无色透明溶液中能大量共存的离子组是",
             options=["A. Cu²⁺、Na⁺、SO₄²⁻、Cl⁻", "B. K⁺、Na⁺、NO₃⁻、CO₃²⁻", "C. H⁺、K⁺、OH⁻、SO₄²⁻", "D. Ba²⁺、Na⁺、SO₄²⁻、NO₃⁻"],
             answer="B",
             analysis="A 有色（Cu²⁺蓝）；C 生成水；D 生成 BaSO₄ 沉淀。共存题：色、气、沉、弱、氧化还原五查。"),
    ]),
    ("che_redox", [
        dict(qtype="填空题", difficulty=4,
             stem="标出电子转移方向与数目：2KMnO₄ + 16HCl(浓) = 2KCl + 2MnCl₂ + 5Cl₂↑ + 8H₂O，氧化剂是＿＿，被氧化的 HCl 占全部 HCl 的＿＿（分数）",
             answer="KMnO₄；10/16=5/8",
             analysis="Mn:+7→+2 得 5e⁻×2；16 个 HCl 中 10 个升为 Cl₂（被氧化）、6 个显酸性。双线桥法。"),
    ]),
    ("che_periodic", [
        dict(qtype="选择题", difficulty=4,
             stem="同周期主族元素从左到右，递增的是",
             options=["A. 原子半径", "B. 金属性", "C. 最高正化合价", "D. 电子层数"],
             answer="C",
             analysis="半径减小、金属性减弱、最高正价升高（O、F 除外）。位构性核心规律。"),
    ]),
    ("che_bond", [
        dict(qtype="填空题", difficulty=3,
             stem="NaOH 中存在的化学键类型：＿＿键（Na⁺与OH⁻间）和＿＿键（O与H间）；用电子式表示 N₂：＿＿",
             answer="离子；（极性）共价；:N⋮⋮N:（三对共用电子对）",
             analysis="既有离子键又有共价键的化合物是高频考点；N₂ 含三键。"),
    ]),
    ("che_energy_rxn", [
        dict(qtype="选择题", difficulty=4,
             stem="已知 C(石墨,s) = C(金刚石,s) ΔH>0，则",
             options=["A. 金刚石比石墨稳定", "B. 石墨比金刚石稳定", "C. 该反应为放热反应", "D. 两者能量相同"],
             answer="B",
             analysis="吸热→产物能量高→能量越低越稳定。焓变与稳定性判断。"),
    ]),
    ("che_rate", [
        dict(qtype="填空题", difficulty=4,
             stem="2L 密闭容器中合成氨，2min 内 N₂ 由 4mol 降至 3mol，则 v(N₂)=＿＿mol/(L·min)，v(H₂)=＿＿",
             answer="0.25；0.75",
             analysis="v=Δc/Δt；速率比=系数比。"),
    ]),
    ("che_equilibrium", [
        dict(qtype="选择题", difficulty=5,
             stem="N₂(g) + 3H₂(g) ⇌ 2NH₃(g) ΔH<0，能使平衡正向移动且提高 H₂ 转化率的是",
             options=["A. 升高温度", "B. 恒容充入 He", "C. 增大压强", "D. 加入催化剂"],
             answer="C",
             analysis="放热反应升温逆移；恒容充惰气各浓度不变不移；催化剂不改平衡。勒夏特列三判断。"),
        dict(qtype="填空题", difficulty=5,
             stem="某温度下 K=1 的平衡：在 1L 容器中充入 1mol CO 与 1mol H₂O(g)，平衡时 CO 转化率为＿＿（CO+H₂O ⇌ CO₂+H₂）",
             answer="50%",
             analysis="设转化 x：x²/(1−x)²=1 → x=0.5。K 表达式与“三段式”。"),
    ]),
    ("che_ionization", [
        dict(qtype="选择题", difficulty=4,
             stem="0.1mol/L 醋酸加水稀释过程中，始终保持增大趋势的是",
             options=["A. c(H⁺)", "B. c(CH₃COO⁻)", "C. Ka", "D. c(H⁺)/c(CH₃COOH)"],
             answer="D",
             analysis="稀释促进电离但离子浓度下降；Ka 只随温度变；比值=Ka/c(CH₃COO⁻) 增大。"),
    ]),
    ("che_ph", [
        dict(qtype="填空题", difficulty=4,
             stem="25℃ 时 pH=3 的盐酸中由水电离的 c(H⁺)=＿＿mol/L；pH=10 的 NaOH 溶液中水电离的 c(OH⁻)=＿＿mol/L",
             answer="10⁻¹¹；10⁻¹⁰",
             analysis="酸中水电离 H⁺=Kw/c(H⁺)；碱中水电离 OH⁻=Kw/c(OH⁻)。水电离计算是难点。"),
    ]),
    ("che_hydrolysis", [
        dict(qtype="选择题", difficulty=5,
             stem="浓度均为 0.1mol/L 的四种溶液：①Na₂CO₃ ②CH₃COONa ③NaCl ④NH₄Cl，pH 由大到小顺序是",
             options=["A. ①②③④", "B. ④③②①", "C. ①②④③", "D. ②①③④"],
             answer="A",
             analysis="越弱越水解：碳酸酸性弱于醋酸故①碱性更强；盐类水解排序通法。"),
    ]),
    ("che_ksp", [
        dict(qtype="填空题", difficulty=4,
             stem="已知 Ksp(AgCl)=1.8×10⁻¹⁰，25℃ 时 AgCl 饱和溶液中 c(Ag⁺)=＿＿mol/L（√1.8≈1.34）",
             answer="1.34×10⁻⁵",
             analysis="c=√Ksp。沉淀转化方向：向更难溶转化。"),
    ]),
    ("che_battery", [
        dict(qtype="填空题", difficulty=4,
             stem="铜锌原电池（稀硫酸）中，负极材料是＿＿，负极反应式：＿＿；正极现象：＿＿",
             answer="Zn；Zn − 2e⁻ = Zn²⁺；铜片上有气泡（2H⁺+2e⁻=H₂↑）",
             analysis="活泼金属作负极；电极反应式书写规范。"),
    ]),
    ("che_electrolysis", [
        dict(qtype="填空题", difficulty=4,
             stem="惰性电极电解 CuCl₂ 溶液，阴极产物是＿＿，阳极产物是＿＿；总反应方程式：＿＿",
             answer="Cu；Cl₂；CuCl₂ =(电解)= Cu + Cl₂↑",
             analysis="放电顺序：阴极 Cu²⁺>H⁺；阳极 Cl⁻>OH⁻。"),
    ]),
    ("che_corrosion", [
        dict(qtype="选择题", difficulty=3,
             stem="下列方法能减缓铁闸门腐蚀的是",
             options=["A. 与铜块相连", "B. 与锌块相连", "C. 接电源正极", "D. 涂盐水"],
             answer="B",
             analysis="牺牲阳极保护法：接更活泼金属。接正极反而加速（阳极溶解）。"),
    ]),
    ("che_organic_alk", [
        dict(qtype="填空题", difficulty=3,
             stem="鉴别甲烷和乙烯的试剂是＿＿，现象：乙烯使＿＿；乙烯与溴水反应的化学方程式：CH₂=CH₂ + Br₂ → ＿＿",
             answer="溴水（或酸性 KMnO₄）；溴水褪色；CH₂BrCH₂Br",
             analysis="加成反应是烯烃特征；注意区分“褪色”与“萃取分层”。"),
    ]),
    ("che_organic_func", [
        dict(qtype="填空题", difficulty=4,
             stem="检验乙醇中是否含水用＿＿，现象＿＿；乙酸与乙醇酯化反应方程式（标出同位素示踪 O¹⁸ 在＿＿中）",
             answer="无水 CuSO₄；变蓝；CH₃COOH+C₂H₅OH⇌(浓硫酸,Δ)CH₃COOC₂H₅+H₂O；¹⁸O 在酯中",
             analysis="酸脱羟基醇脱氢；酯化是可逆反应写 ⇌。"),
    ]),
    ("che_biomol", [
        dict(qtype="填空题", difficulty=2,
             stem="淀粉遇碘变＿＿色；蛋白质遇浓硝酸变＿＿色（显色反应）；葡萄糖与新制 Cu(OH)₂ 共热生成＿＿色沉淀",
             answer="蓝；黄；砖红（Cu₂O）",
             analysis="三大有机物特征反应，全部是选择题高频选项。"),
    ]),
    ("che_experiment", [
        dict(qtype="选择题", difficulty=4,
             stem="下列实验操作正确的是",
             options=["A. 稀释浓硫酸时将水沿器壁注入酸中", "B. 过滤时液面高于滤纸边缘", "C. 分液时下层液体从下口放出、上层从上口倒出", "D. 用托盘天平称取 5.85g 食盐"],
             answer="C",
             analysis="酸入水；液面低于滤纸；托盘天平精度 0.1g。基本操作规范。"),
    ]),
    ("che_infer", [
        dict(qtype="填空题", difficulty=4,
             stem="某溶液加 KSCN 不变色，通入 Cl₂ 后变红，原溶液含＿＿离子；焰色反应呈黄色的溶液含＿＿离子（透过蓝色钴玻璃呈紫色则另含＿＿）",
             answer="Fe²⁺；Na⁺；K⁺",
             analysis="Fe²⁺ 检验两步法；焰色是元素性质。"),
    ]),
    ("che_calc", [
        dict(qtype="解答题", difficulty=4,
             stem="把 5.6g 铁粉加入 100mL 1mol/L CuSO₄ 溶液中，充分反应后（假设溶液体积不变），析出铜的质量为＿＿g，溶液中 c(Fe²⁺)=＿＿mol/L",
             answer="3.2g；1mol/L",
             analysis="Fe 0.1mol、CuSO₄ 0.1mol 恰好完全反应：Cu=0.1×64=3.2g；生成 Fe²⁺ 0.1mol，c=0.1mol÷0.1L=1mol/L。"),
    ]),
    # ---------------- 生物 ----------------
    ("bio_jr_cell", [
        dict(qtype="填空题", difficulty=2,
             stem="植物细胞有而动物细胞没有的结构：＿＿、＿＿、＿＿（写三个）；控制物质进出细胞的结构是＿＿",
             answer="细胞壁；液泡；叶绿体；细胞膜",
             analysis="动植物细胞区分是初中生物第一考点。"),
    ]),
    ("bio_jr_nerve", [
        dict(qtype="填空题", difficulty=2,
             stem="神经系统结构和功能的基本单位是＿＿；反射的结构基础是＿＿",
             answer="神经元（神经细胞）；反射弧",
             analysis="反射弧五部分：感受器→传入→神经中枢→传出→效应器。"),
    ]),
    ("bio_jr_hormone", [
        dict(qtype="选择题", difficulty=3,
             stem="幼年时期生长激素分泌不足患",
             options=["A. 甲亢", "B. 侏儒症", "C. 呆小症", "D. 糖尿病"],
             answer="B",
             analysis="甲状腺激素不足→呆小症（智力也受损）；生长激素不足→侏儒症（智力正常）。"),
    ]),
    ("bio_jr_heredity", [
        dict(qtype="填空题", difficulty=3,
             stem="基因是有遗传效应的＿＿片段；人体细胞中染色体有＿＿条，精子中有＿＿条",
             answer="DNA；46（23对）；23",
             analysis="染色体在生殖细胞中减半——为高中减数分裂铺垫。"),
    ]),
    ("bio_molecule", [
        dict(qtype="填空题", difficulty=3,
             stem="细胞中含量最多的化合物是＿＿；生命活动的主要承担者是＿＿；直接能源物质是＿＿",
             answer="水；蛋白质；ATP",
             analysis="三个“最多/主要”是选择题高频陷阱。"),
    ]),
    ("bio_protein", [
        dict(qtype="填空题", difficulty=4,
             stem="n 个氨基酸形成 2 条肽链，脱去水分子＿＿个，肽键＿＿个；蛋白质结构多样性的原因：氨基酸的＿＿、＿＿、＿＿不同及肽链盘曲折叠方式不同",
             answer="n−2；n−2；种类；数目；排列顺序",
             analysis="脱水数=肽键数=氨基酸数−肽链数。"),
    ]),
    ("bio_nucleic", [
        dict(qtype="填空题", difficulty=3,
             stem="DNA 特有的碱基是＿＿，RNA 特有的是＿＿；DNA 的基本单位是＿＿",
             answer="T（胸腺嘧啶）；U（尿嘧啶）；脱氧核糖核苷酸",
             analysis="碱基 T/U 与五碳糖双重区分。"),
    ]),
    ("bio_membrane", [
        dict(qtype="选择题", difficulty=3,
             stem="下列过程属于自由扩散（不需载体不耗能）的是",
             options=["A. 葡萄糖进入红细胞", "B. O₂ 进入线粒体", "C. K⁺ 逆浓度进入细胞", "D. 氨基酸进入小肠细胞"],
             answer="B",
             analysis="气体、水、脂溶性小分子自由扩散；A 协助扩散；C 主动运输。"),
    ]),
    ("bio_organelle", [
        dict(qtype="填空题", difficulty=3,
             stem="产生 ATP 的细胞器：＿＿（有氧呼吸主要场所）和＿＿（光合作用场所）；合成蛋白质的场所是＿＿",
             answer="线粒体；叶绿体；核糖体",
             analysis="细胞器功能“动力车间/养料制造车间/生产蛋白质机器”。"),
    ]),
    ("bio_nucleus", [
        dict(qtype="选择题", difficulty=4,
             stem="动物细胞有丝分裂区别于植物细胞的特点是",
             options=["A. 间期复制 DNA", "B. 前期中心体发出星射线形成纺锤体", "C. 后期着丝粒分裂", "D. 末期形成细胞板"],
             answer="B",
             analysis="植物：细胞板扩展成壁；动物：细胞膜缢裂。纺锤体来源也不同。"),
    ]),
    ("bio_enzyme", [
        dict(qtype="填空题", difficulty=3,
             stem="酶的本质绝大多数是＿＿，少数是＿＿；酶催化特性：高效性、＿＿、作用条件温和；过酸过高温使酶＿＿（填“变性失活”或“活性降低”）",
             answer="蛋白质；RNA；专一性；变性失活",
             analysis="低温抑制可恢复、高温变性不可恢复——高频陷阱。"),
    ]),
    ("bio_resp", [
        dict(qtype="填空题", difficulty=4,
             stem="有氧呼吸三个阶段产生 ATP 最多的是第＿＿阶段，场所＿＿；无氧呼吸产生酒精的反应式：C₆H₁₂O₆ →(酶) ＿＿",
             answer="三；线粒体内膜；2C₂H₅OH + 2CO₂ + 少量能量",
             analysis="第三阶段 [H]+O₂→H₂O 放能最多。"),
    ]),
    ("bio_photo", [
        dict(qtype="填空题", difficulty=4,
             stem="光反应为暗反应提供＿＿和＿＿；暗反应包括 CO₂ 的＿＿和 C₃ 的＿＿两个阶段；突然停止光照，C₃ 含量＿＿",
             answer="[H]（NADPH）；ATP；固定；还原；上升",
             analysis="C₃ 来源不变去路受阻→积累。动态分析是核心能力。"),
    ]),
    ("bio_meiosis", [
        dict(qtype="填空题", difficulty=4,
             stem="减数分裂中染色体数目减半发生在第＿＿次分裂；交叉互换发生在＿＿期；1 个精原细胞经减数分裂产生＿＿个精子，1 个卵原细胞产生＿＿个卵细胞",
             answer="一；减Ⅰ前（四分体）；4；1",
             analysis="减Ⅰ同源分离致减半；配子多样性来源：自由组合+交叉互换。"),
    ]),
    ("bio_dna_struct", [
        dict(qtype="填空题", difficulty=4,
             stem="DNA 双螺旋中 A 与＿＿配对、G 与＿＿配对（碱基互补配对）；若一条链 A:T=1:2，则整个 DNA 分子中 A:T=＿＿；复制方式是＿＿",
             answer="T；C；1:2；半保留复制",
             analysis="双链 A=T；单链比例传递到双链需换算。"),
    ]),
    ("bio_gene_expr", [
        dict(qtype="填空题", difficulty=4,
             stem="基因表达包括＿＿（场所主要在细胞核）和＿＿（场所核糖体）两个过程；tRNA 上的反密码子与＿＿互补配对",
             answer="转录；翻译；mRNA 上的密码子",
             analysis="中心法则：DNA→RNA→蛋白质；密码子共 64 种，终止密码 3 种不编码氨基酸。"),
    ]),
    ("bio_mendel", [
        dict(qtype="选择题", difficulty=4,
             stem="AaBb（独立遗传）自交，子代中 A_B_ 占",
             options=["A. 3/16", "B. 9/16", "C. 6/16", "D. 1/16"],
             answer="B",
             analysis="双显=3/4×3/4=9/16。分离法是自由组合的基础。"),
        dict(qtype="填空题", difficulty=5,
             stem="黄色鼠（A_）与黑色鼠（aa）交配，F₁ 黄:黑=1:1，亲本黄色鼠基因型为＿＿；F₁ 黄色鼠自由交配，F₂ 中黄色:黑色=＿＿（AA 胚胎致死时）",
             answer="Aa；2:1",
             analysis="测比 1:1→Aa；Aa×Aa 中 AA 致死剩 2Aa:1aa。致死类比例变形。"),
    ]),
    ("bio_sex_link", [
        dict(qtype="填空题", difficulty=4,
             stem="红绿色盲（X 隐性）男性发病率＿＿（高于/低于）女性；色盲女患者的儿子＿＿（填表现型）；“交叉遗传”指＿＿",
             answer="高于；必为色盲；男患者的致病基因经女儿传给外孙",
             analysis="X 隐性特点：男多于女、隔代交叉遗传、女病父子必病。"),
    ]),
    ("bio_mutation", [
        dict(qtype="选择题", difficulty=4,
             stem="光学显微镜下能观察到的变异是",
             options=["A. 基因突变", "B. 基因重组", "C. 染色体变异", "D. 都不能"],
             answer="C",
             analysis="染色体形态可见；基因突变/重组分子水平不可见。"),
    ]),
    ("bio_breeding", [
        dict(qtype="填空题", difficulty=4,
             stem="能明显缩短育种年限的方法是＿＿育种，原理是＿＿；无籽西瓜是＿＿倍体，由＿＿倍体与四倍体杂交获得",
             answer="单倍体；染色体变异；三倍；二",
             analysis="单倍体育种：花药离体培养+秋水仙素加倍，纯合子一步到位。"),
    ]),
    ("bio_evolution", [
        dict(qtype="填空题", difficulty=3,
             stem="现代生物进化理论：＿＿是生物进化的基本单位；＿＿决定进化方向；新物种形成的标志是产生＿＿",
             answer="种群；自然选择；生殖隔离",
             analysis="进化≠物种形成：基因频率改变即进化，生殖隔离才是新物种。"),
    ]),
    ("bio_homeostasis", [
        dict(qtype="填空题", difficulty=3,
             stem="内环境即＿＿液，主要包括＿＿、＿＿、＿＿；血浆 pH 稳定与 ＿＿等离子有关",
             answer="细胞外；血浆；组织液；淋巴；HCO₃⁻/HPO₄²⁻（缓冲对）",
             analysis="内环境成分辨析：血红蛋白在细胞内不属于内环境——高频陷阱。"),
    ]),
    ("bio_neuro", [
        dict(qtype="填空题", difficulty=4,
             stem="静息电位表现为＿＿，受刺激产生动作电位时 Na⁺ ＿＿（内流/外流）；兴奋在神经纤维上以＿＿形式传导，在突触处单向传递的原因是＿＿",
             answer="外正内负；内流；电信号（局部电流/神经冲动）；神经递质只存在于突触前膜泡中",
             analysis="电位机理+传递方向是神经调节两大主干。"),
    ]),
    ("bio_humoral", [
        dict(qtype="选择题", difficulty=4,
             stem="血糖浓度升高时，胰岛的调节是",
             options=["A. 胰高血糖素分泌增加", "B. 胰岛素分泌增加", "C. 两者都增加", "D. 两者都减少"],
             answer="B",
             analysis="胰岛素降糖（唯一），胰高血糖素升糖；反馈调节实例。"),
    ]),
    ("bio_immune", [
        dict(qtype="填空题", difficulty=4,
             stem="体液免疫中产生抗体的细胞是＿＿，它由＿＿细胞增殖分化而来；效应 T 细胞使靶细胞＿＿属于＿＿免疫",
             answer="浆细胞（效应B）；B（和记忆）；裂解死亡；细胞",
             analysis="二次免疫更快更强——记忆细胞。"),
    ]),
    ("bio_plant_hormone", [
        dict(qtype="选择题", difficulty=4,
             stem="植物顶端优势与生长素作用的两重性有关，正确叙述是",
             options=["A. 侧芽生长素浓度过高被抑制", "B. 顶芽生长素浓度过高被抑制", "C. 去除顶芽侧芽生长受抑", "D. 生长素高浓度促进开花"],
             answer="A",
             analysis="顶芽产素向下积累，侧芽敏感被抑；两重性：低促高抑。"),
    ]),
    ("bio_population", [
        dict(qtype="填空题", difficulty=3,
             stem="调查跳蝻（活动能力弱）密度用＿＿法；标志重捕法适用于＿＿；“J”型增长的条件：＿＿充足、空间充裕、无天敌",
             answer="样方；活动能力强、活动范围大的动物；食物",
             analysis="两种密度调查方法的适用对象是必考选择。"),
    ]),
    ("bio_ecosystem", [
        dict(qtype="填空题", difficulty=4,
             stem="能量流动特点：＿＿、＿＿；相邻营养级传递效率约＿＿；分解者属于＿＿（营养级/非生物成分之外的第三成分）",
             answer="单向流动；逐级递减；10%—20%；第三成分（生物群落一部分）",
             analysis="能量不能循环；物质循环、能量流动、信息传递三功能。"),
    ]),
    ("bio_eco_protect", [
        dict(qtype="填空题", difficulty=2,
             stem="生物多样性三个层次：＿＿多样性、＿＿多样性、＿＿多样性；就地保护最有效的措施是＿＿",
             answer="基因；物种；生态系统；建立自然保护区",
             analysis="三个层次顺序与内涵是表述题采分点。"),
    ]),
    ("bio_gene_eng", [
        dict(qtype="填空题", difficulty=4,
             stem="基因工程“分子剪刀”是＿＿酶，“分子针线”是＿＿酶；运载体条件：能自我复制、有＿＿、有标记基因；目的基因能否遗传给后代看＿＿是否插入染色体 DNA",
             answer="限制性核酸内切（限制）；DNA 连接；多个酶切位点；目的基因",
             analysis="工具酶+载体三条件是基因工程必答框架。"),
    ]),
    ("bio_cell_eng", [
        dict(qtype="填空题", difficulty=3,
             stem="植物组织培养依据的原理是＿＿；动物细胞培养用＿＿酶分散细胞；植物体细胞杂交完成的标志是＿＿",
             answer="植物细胞全能性；胰蛋白（或纤维素酶和果胶酶去壁）；再生出新的细胞壁",
             analysis="去壁用纤维素酶果胶酶；分散动物细胞用胰蛋白酶。"),
    ]),
    # ---------------- 语文 ----------------
    ("chn_wenyan_word", [
        dict(qtype="填空题", difficulty=3,
             stem="解释加点词：“素”在“吴广素爱人”中意为＿＿；“兵”在“收天下之兵”中意为＿＿；“去”在“去国怀乡”中意为＿＿",
             answer="向来、一向；兵器；离开",
             analysis="三个高频实词。“去”古今异义：古义离开，今义前往。"),
    ]),
    ("chn_wenyan_func", [
        dict(qtype="选择题", difficulty=4,
             stem="下列“之”字用法与其他三项不同类的是",
             options=["A. 蚓无爪牙之利（定语后置标志）", "B. 句读之不知（宾语前置标志）", "C. 均之二策（这）", "D. 何陋之有（宾语前置标志）"],
             answer="C",
             analysis="ABD 都是提宾/定后标志（助词），C 是指示代词。"),
    ]),
    ("chn_wenyan_sent", [
        dict(qtype="填空题", difficulty=4,
             stem="翻译：“所以遣将守关者，备他盗之出入与非常也。”（《鸿门宴》）并指出句式：＿＿句",
             answer="（我）派遣将领把守函谷关的原因，是防备其他盗贼进出和意外变故。判断句（……者，……也）",
             analysis="判断句标志；“非常”古今异义：意外变故。"),
    ]),
    ("chn_poem_image", [
        dict(qtype="填空题", difficulty=4,
             stem="“月落乌啼霜满天，江枫渔火对愁眠”中，诗人借＿＿、＿＿、霜天等意象渲染＿＿氛围，表达＿＿之情",
             answer="月落、乌啼（或江枫渔火）；凄清孤寂；羁旅愁思",
             analysis="意象→意境→情感三步答题链。"),
    ]),
    ("chn_read_argue", [
        dict(qtype="选择题", difficulty=3,
             stem="论述类文本“偷换概念”错误类型的特征是",
             options=["A. 把或然说成必然", "B. 用不同内涵的概念替换原文概念", "C. 强加因果", "D. 以偏概全"],
             answer="B",
             analysis="六大设误类型辨析是论述类阅读选择题核心能力。"),
    ]),
    ("chn_lang_word", [
        dict(qtype="填空题", difficulty=3,
             stem="写出成语中加点字：按（＿＿）兵不动、相形见（＿＿）、（＿＿）之以情",
             answer="àn；绌 chù；晓",
             analysis="字音字形与成语含义一并记。"),
    ]),
    ("chn_lang_sick", [
        dict(qtype="选择题", difficulty=4,
             stem="下列没有语病的一句是",
             options=["A. 通过这次活动，使我受到了教育", "B. 能否刻苦钻研是提高成绩的关键", "C. 他每天游泳大约一小时左右", "D. 他的家乡是云南昆明人"],
             answer="B",
             analysis="A 缺主语；C “大约…左右”重复；D 主宾搭配不当。B 两面对两面正确。"),
    ]),
    ("chn_essay_topic", [
        dict(qtype="填空题", difficulty=3,
             stem="作文题目“本手·妙手·俗手”（2022 新高考Ⅰ卷），最佳立意的核心关系是：＿＿是基础，＿＿是创造，脱离基础求＿＿则成俗手",
             answer="本手；妙手；妙手",
             analysis="三元关系型审题：先界定概念再建立逻辑链。"),
    ]),
    # ---------------- 英语 ----------------
    ("eng_grammar_base", [
        dict(qtype="填空题", difficulty=3,
             stem="用正确时态填空：By the time he arrived, the meeting ＿＿(already/begin).",
             answer="had already begun",
             analysis="过去的过去用过去完成时。时态判断先看时间参照点。"),
    ]),
    ("eng_grammar_nonp", [
        dict(qtype="填空题", difficulty=4,
             stem="填空：＿＿(walk) along the river, he picked up a stone. （主语 he 与 walk 是主动关系，用现在分词）",
             answer="Walking",
             analysis="非谓语第一步：判断与逻辑主语的主/被动关系。"),
    ]),
    ("eng_grammar_clau", [
        dict(qtype="填空题", difficulty=4,
             stem="填关系词：The factory ＿＿ we visited last year has closed. / This is the reason ＿＿ he was late.",
             answer="which/that（或不填）；why",
             analysis="先行词在从句中作宾语→which/that；reason 作状语→why。"),
    ]),
    ("eng_read", [
        dict(qtype="选择题", difficulty=3,
             stem="阅读理解中 “The underlined word ”obsolete“ most probably means ＿＿” 题型最有效的解法是",
             options=["A. 查词典", "B. 利用上下文线索（定义/对比/因果/举例）推断", "C. 凭语感", "D. 看首段"],
             answer="B",
             analysis="词义猜测题四线索：定义、反义、因果、并列举例。"),
    ]),
    ("eng_write_apply", [
        dict(qtype="填空题", difficulty=3,
             stem="应用文（邀请信）开头套句：I am ＿＿(write) to invite you to... ；结尾期待回复：I would appreciate it if you could ＿＿(reply) at your earliest convenience.",
             answer="writing；reply",
             analysis="应用文格式句必须条件反射级熟练。"),
    ]),
    ("eng_listening", [
        dict(qtype="填空题", difficulty=2,
             stem="听力预读技巧：利用试音时间划出选项中的＿＿差异（如时间、地点、数字）",
             answer="关键信息（三要素：what/when/where）",
             analysis="预读定位差异是听力提分第一步。"),
    ]),
    # ---------------- 语文（补充） ----------------
    ("chn_wenyan_punc", [
        dict(qtype="填空题", difficulty=4,
             stem="断句（用 / 标出两处）：吾 尝 为 鲍 叔 谋 事 而 愈 贫 直 见 欺 于 鲍 叔",
             answer="吾尝为鲍叔谋事 / 而愈贫 / 直见欺于鲍叔",
             analysis="断句先找虚词（而、于）与句式（见……于 表被动），再核语义。"),
        dict(qtype="填空题", difficulty=3,
             stem="文化常识：“跬步”中“跬”指＿＿；“庠序”指＿＿；“太学”始于＿＿朝",
             answer="跨出一脚（半步）；学校；汉代",
             analysis="教材注释中的文化常识是断句题的配套采分点。"),
    ]),
    ("chn_poem_tech", [
        dict(qtype="选择题", difficulty=4,
             stem="“遥想公瑾当年，小乔初嫁了，雄姿英发”运用的表现手法主要是",
             options=["A. 借景抒情", "B. 用典与衬托", "C. 直抒胸臆", "D. 托物言志"],
             answer="B",
             analysis="以美人衬英雄、借周瑜典故抒己之壮志。答题格式：手法+结合诗句+情感。"),
    ]),
    ("chn_poem_emotion", [
        dict(qtype="填空题", difficulty=4,
             stem="“万里悲秋常作客，百年多病独登台”（杜甫《登高》）中，“作客”传达的情感是＿＿；全诗情感基调可概括为＿＿",
             answer="羁旅漂泊之苦；沉郁顿挫（悲己悲国）",
             analysis="炼字题三步：释义+手法+情感。“悲秋”多层意：秋、万里、作客、百年、多病、独、登台。"),
    ]),
    ("chn_read_lit", [
        dict(qtype="选择题", difficulty=4,
             stem="小说鉴赏中，环境描写的作用一般不包括",
             options=["A. 交代背景、渲染气氛", "B. 烘托人物心情", "C. 直接论证中心论点", "D. 推动情节发展"],
             answer="C",
             analysis="“论证论点”是论述类文本概念，小说用“暗示/深化主旨”——文体术语不能混用。"),
    ]),
    ("chn_read_prac", [
        dict(qtype="填空题", difficulty=3,
             stem="图表信息题答题要点：先标＿＿（横纵轴含义），再比较＿＿（升降大小），概括结论须含趋势、＿＿与转折",
             answer="坐标含义；数据变化；极值",
             analysis="实用类文本按点给分，结论表述必须含“趋势+极值”。"),
    ]),
    ("chn_lang_cohere", [
        dict(qtype="选择题", difficulty=4,
             stem="填入横线处衔接最恰当的一句：＿＿。比如工业噪声、交通噪声，还有建筑噪声。",
             options=["A. 噪声来源广泛", "B. 噪声污染日益严重", "C. 噪声危害人体健康", "D. 噪声看不见摸不着"],
             answer="A",
             analysis="后文“比如”列举的是来源，话题必须一致——语句衔接先看后文提示词。"),
    ]),
    ("chn_essay_argue", [
        dict(qtype="填空题", difficulty=4,
             stem="议论文“引—议—联—结”结构中，“议”指＿＿；“联”指＿＿；中心论点建议在第＿＿句内提出",
             answer="对材料/观点进行分析论证；联系现实与他例；1—2",
             analysis="议论文 48 分以上的关键：结构清晰+每段有分论点句。"),
    ]),
    ("chn_essay_material", [
        dict(qtype="填空题", difficulty=3,
             stem="素材运用三步法：叙例（＿＿概括）—析例（扣住＿＿）—联例（同类并举）。论证“坚韧”可用司马迁、＿＿、＿＿",
             answer="简要；论点；史铁生；贝多芬（任选其二）",
             analysis="素材不在多而在“用”——分析句必须回扣论点，否则是“观点+例子”两张皮。"),
    ]),
    # ---------------- 英语（补充） ----------------
    ("eng_grammar_adv", [
        dict(qtype="填空题", difficulty=4,
             stem="虚拟语气：If I ＿＿(be) you, I would study harder. / 倒装：Not until yesterday ＿＿(he/return) home.",
             answer="were；did he return",
             analysis="与现在事实相反用 were；Not until 置句首主句部分倒装。"),
    ]),
    ("eng_grammar_fill", [
        dict(qtype="填空题", difficulty=4,
             stem="语法填空：The _______(discover) of the new drug was a great _______(achieve).",
             answer="discovery；achievement",
             analysis="词性转换是语法填空必考点：the+名词、a+名词。"),
    ]),
    ("eng_cloze", [
        dict(qtype="填空题", difficulty=4,
             stem="完形填空核心原则：答案线索一定出现在＿＿中（原文复现/同义/反义/上下义），不要凭主观想象选词",
             answer="上下文（语境）",
             analysis="完形考“照应”不考“辨析”——先找线索再定选项。"),
    ]),
    ("eng_write_cont", [
        dict(qtype="填空题", difficulty=4,
             stem="读后续写时态基准：情节叙述统一用＿＿时；“心跳加速”可写 My heart ＿＿＿＿(pound) wildly as I stepped forward.",
             answer="过去（was pounding 表进行画面感）",
             analysis="读后续写时态以过去时为基准；动作链用“主要动词+分词”增色。"),
    ]),
    # ---------------- 生物·初中层（补充） ----------------
    ("bio_jr_digest", [
        dict(qtype="填空题", difficulty=2,
             stem="消化吸收的主要器官是＿＿；胆汁由＿＿分泌，不含消化酶但能乳化＿＿",
             answer="小肠；肝脏；脂肪",
             analysis="小肠是消化吸收主战场（长、皱襞、绒毛）；胆汁乳化是物理性消化。"),
    ]),
    ("bio_jr_resp", [
        dict(qtype="填空题", difficulty=2,
             stem="呼吸系统主要器官是＿＿；呼出气体与吸入气体相比，＿＿含量增加、＿＿含量减少",
             answer="肺；二氧化碳；氧气",
             analysis="肺泡与血液气体交换靠扩散作用。"),
    ]),
    ("bio_jr_circ", [
        dict(qtype="填空题", difficulty=2,
             stem="血液循环动力器官是＿＿；体循环起点＿＿、终点＿＿；动脉血含氧＿＿（多/少）",
             answer="心脏；左心室；右心房；多",
             analysis="体循环：左心室→主动脉→全身→上下腔静脉→右心房。"),
    ]),
    ("bio_jr_urin", [
        dict(qtype="填空题", difficulty=2,
             stem="形成尿液的基本单位是＿＿；原尿与血浆相比不含＿＿；尿糖可能是＿＿激素不足",
             answer="肾单位；大分子蛋白质；胰岛素",
             analysis="肾小球滤过+肾小管重吸收两步；糖尿病与胰岛素关联是跨系统考点。"),
    ]),
    ("bio_jr_eco", [
        dict(qtype="填空题", difficulty=2,
             stem="生态系统的生产者是＿＿；“螳螂捕蝉，黄雀在后”食物链起点应是＿＿（植物/蝉）",
             answer="绿色植物；植物",
             analysis="食物链必须从生产者开始——以“蝉”开头是典型错误。"),
    ]),
    ("bio_jr_microbe", [
        dict(qtype="选择题", difficulty=2,
             stem="下列生物中没有成形细胞核（原核生物）的是",
             options=["A. 酵母菌", "B. 霉菌", "C. 乳酸菌", "D. 蘑菇"],
             answer="C",
             analysis="细菌（乳酸菌等）原核无核膜；真菌（酵母菌、霉菌、蘑菇）真核。"),
    ]),
    # ---------------- 补漏节点（知识面核查后新增） ----------------
    ("phy_experiment", [
        dict(qtype="填空题", difficulty=3,
             stem="电磁打点计时器使用＿＿（交流/直流）电源，工作电压约 8V，频率 50Hz 时相邻两点时间间隔为＿＿s",
             answer="交流；0.02",
             analysis="两种打点计时器均用交流电；电火花用 220V。T=1/f=0.02s。"),
        dict(qtype="选择题", difficulty=4,
             stem="用图象法测电源电动势与内阻时，由 U=E−Ir 可知",
             options=["A. U-I 图线斜率即电动势", "B. U-I 图线纵截距为电动势、斜率绝对值为内阻", "C. 横截距为内阻", "D. 图线必须过原点"],
             answer="B",
             analysis="U=E−Ir 化为 U=−rI+E：截距 E、斜率 −r。纵轴不从零开始时横截距不再是短路电流。"),
        dict(qtype="填空题", difficulty=4,
             stem="验证力的平行四边形定则中，两次拉橡皮条必须拉到＿＿（同一位置/任意位置），这体现的物理思想是＿＿",
             answer="同一位置；等效替代",
             analysis="合力与分力作用效果相同才可比，故结点必须重合。"),
    ]),
    ("che_structure", [
        dict(qtype="填空题", difficulty=3,
             stem="基态 Fe 原子的核外电子排布式为＿＿，有＿＿个未成对电子",
             answer="1s²2s²2p⁶3s²3p⁶3d⁶4s²（[Ar]3d⁶4s²）；4",
             analysis="3d⁶ 按洪特规则排 5 个轨道：↑↓ ↑ ↑ ↑ ↑，未成对 4 个。Fe 是高频考查元素。"),
        dict(qtype="选择题", difficulty=4,
             stem="下列微粒半径比较正确的是",
             options=["A. Na⁺ > Mg²⁺ > O²⁻", "B. N > O > F", "C. Cl⁻ > Na⁺ > K", "D. F⁻ > Na⁺ 且电子层结构不同"],
             answer="B",
             analysis="同周期从左到右半径减小；A 中三者电子层相同，核电荷越大半径越小（O²⁻>Na⁺>Mg²⁺）；C 中 K>Cl⁻。"),
    ]),
    ("che_crystal", [
        dict(qtype="填空题", difficulty=4,
             stem="干冰、金刚石、氯化钠、铝四种晶体中，熔点由高到低的顺序是＿＿；干冰升华时破坏的是＿＿（化学键/分子间作用力）",
             answer="金刚石>铝>氯化钠>干冰；分子间作用力",
             analysis="共价晶体>金属（一般）>离子>分子是粗略序，金刚石 C-C 键极强；分子晶体熔化只破坏范德华力。"),
        dict(qtype="解答题", difficulty=5,
             stem="铜晶体为面心立方最密堆积，晶胞边长 a cm，阿伏加德罗常数 N_A。一个晶胞含＿＿个 Cu 原子，晶体密度为＿＿g/cm³（用含 a、N_A 的式子表示，Cu 摩尔质量 64）",
             answer="4 个；ρ=4×64/(N_A·a³)=256/(N_A·a³)",
             analysis="面心立方：8×(1/8)+6×(1/2)=4。ρ=m/V=4×64/N_A÷a³。均摊法是晶胞计算第一关。"),
    ]),
    ("che_coordination", [
        dict(qtype="填空题", difficulty=4,
             stem="SO₄²⁻ 中 S 原子的杂化方式为＿＿，空间构型为＿＿；H₂O 中 O 的杂化方式为＿＿，分子构型为＿＿",
             answer="sp³；正四面形；sp³（含两对孤对电子）；V 形",
             analysis="价层电子对数=(6+2)/2=4 无孤对→正四面体；H₂O 为 4 对中有 2 对孤对→V 形。"),
        dict(qtype="选择题", difficulty=4,
             stem="配合物 [Cu(NH₃)₄]SO₄ 中",
             options=["A. 配位体是 SO₄²⁻", "B. Cu²⁺ 提供孤对电子", "C. NH₃ 中 N 提供孤对电子形成配位键", "D. 配位数为 5"],
             answer="C",
             analysis="中心离子提供空轨道、配体提供孤对电子；配位体是 NH₃，配位数 4。"),
    ]),
    ("bio_biotech", [
        dict(qtype="填空题", difficulty=3,
             stem="培养基常用的灭菌方法是＿＿法；对接种环的灭菌方法是＿＿",
             answer="高压蒸汽灭菌；灼烧灭菌",
             analysis="培养基湿热灭菌 100kPa/121℃；金属接种工具灼烧。玻璃器皿用干热灭菌。"),
        dict(qtype="选择题", difficulty=4,
             stem="用稀释涂布平板法统计菌落数目时，一般选择菌落数在＿＿范围的平板计数",
             options=["A. 10~100", "B. 30~300", "C. 500~1000", "D. 越多越好"],
             answer="B",
             analysis="30~300 统计较可靠；太少误差大、太多菌落重叠。统计值常比活菌实际数偏低（两菌连成一个菌落）。"),
    ]),
    ("eng_seven_five", [
        dict(qtype="填空题", difficulty=3,
             stem="七选五最常用的三种线索：①代词指代（this/these 前文必有对象）②＿＿③＿＿",
             answer="逻辑连接词（however/therefore/for example 等）；词汇复现（同义/原词重现）",
             analysis="七选五考语篇衔接：先看空前空后的衔接信号，再验证语义连贯。"),
    ]),
]


def seed_self_quiz(conn: sqlite3.Connection) -> dict[str, int]:
    """幂等录入自检题；返回统计。"""
    ok = dup = 0
    for kp_id, qs in SELF_QUIZ:
        row = conn.execute(
            "SELECT subject FROM knowledge_points WHERE id=?", (kp_id,)).fetchone()
        if not row:
            raise ValueError("自检题引用了不存在的知识点：%s" % kp_id)
        for q in qs:
            try:
                db.add_question(conn, source_type="自主命题练习",
                                subject=row["subject"], kp_id=kp_id, **q)
                ok += 1
            except db.DuplicateStem:
                dup += 1
    return {"inserted": ok, "duplicate": dup}


def quiz_for_node(conn: sqlite3.Connection, kp_id: str) -> list[sqlite3.Row]:
    return conn.execute(
        "SELECT * FROM questions WHERE kp_id=? ORDER BY id", (kp_id,)).fetchall()
