# -*- coding: utf-8 -*-
"""化学真题（2023—2024 新课标卷 / 全国新课标卷）。

来源与核实说明：
- 2024 年新课标卷（老高考理综，适用云南、河南、新疆、山西等）条目：
  题干与解析取自人人文库《2024年普通高等学校招生全国统一考试新课标卷化学试卷》
  (https://m.renrendoc.com/paper/447450867.html)，其每题“解析”末尾均给出答案；
  另以 zizzs 官方答案 PDF (https://cdn.zizzs.com/17187892444732024%E5%B9%B4%E9%AB%98
  %E8%80%83%E6%96%B0%E8%AF%BE%E6%A0%87%E5%8D%B7%E7%90%86%E7%BB%BC%E5%8C%96%E5%AD%A6
  %E7%AD%94%E6%A1%88.pdf) 的答案键 “1.D 2.B 3.B 4.C 5.A 6.C 7.D” 逐题比对，
  7 道选择题答案两处完全一致，非选择题（第27、28、29题）答案亦与该 PDF 对应条目吻合，
  故相关条目 verified=1。
- 2023 年新课标卷（适用云南、山西、黑龙江、吉林、安徽）条目：
  题干与解析取自 21 世纪教育网 (https://mip.21cnjy.com/P/26500678.html)，
  并以原创力文档 (https://m.book118.com/html/2025/1010/6054124012011242.shtm)
  及 bodocs 纯答案版 (http://www.bodocs.net/doc/3219287476.html) 的答案键
  “1.C 2.B 3.A ...” 交叉核对，第 7、8、9 题答案多源一致，故 verified=1。
- 2024 年第 28 题（吡咯合成实验）的“量取仪器”一题，人人文库解析答案为“20 mL 量筒”，
  而 zizzs 答案 PDF 对应条目写作“酸式滴定管”，两源在该子问上存在分歧，故该题 verified=0，
  使用前请以当年官方原卷为准核对。
- 所有含 LaTeX 反斜杠的字段均使用 Python 原始字符串（前缀 r 的普通字符串或三引号字符串），
  以保证 \\frac、\\mathrm、\\xrightarrow 等命令不被转义为乱码。
- 2024 年第 30 题（四氟咯草胺有机合成推断）：题干、小问与答案取自学科网
  《精品解析：2024年高考新课标卷理综化学高考真题解析（参考版）》
  (https://www.zxxk.com/soft/45822199.html)，以教习网同题
  (http://51jiaoxi.com/doc-16007197.html) 交叉核对，按小问拆行。
- 2025 年云南卷（新高考 3+1+2）整卷：取自 21 世纪教育网《2025年普通高中学业水平选择性考试
  （云南卷）化学（pdf版，含答案和答题卡）》(https://zy.21cnjy.com/24900045)，以教习网
  《2025年高考云南卷化学高考真题（原卷版＋解析版）》
  (https://www.51jiaoxi.com/doc-17693629.html) 交叉核对。卷别说明：云南 2025 年语数外用
  新课标Ⅱ卷，选考科目（含化学）由云南省自主命题，故 paper 记作「2025 云南卷」。
  新增条目全部 verified=0，待双源核对后统一置 1。
"""

SUBJECT = "化学"

ITEMS = [
    # ============ 一、2024 新课标卷 选择题（7 道，均 verified=1） ============
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "7",
        "source_ref": "https://m.renrendoc.com/paper/447450867.html",
        "verified": 1,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 2,
        "stem": r"文房四宝是中华传统文化的瑰宝。下列有关叙述错误的是（　　）",
        "options": [
            r"羊毛可用于制毛笔，主要成分为蛋白质",
            r"松木可用于制墨，墨的主要成分是单质碳",
            r"竹子可用于造纸，纸的主要成分是纤维素",
            r"大理石可用于制砚台，主要成分为硅酸盐",
        ],
        "answer": "D",
        "analysis": r"解析：大理石的主要成分是 $\mathrm{CaCO}_3$，不属于硅酸盐，D 项错误；羊毛主要成分为蛋白质，A 正确；松木制墨，墨含单质碳，B 正确；竹子造纸，纸的主要成分为纤维素，C 正确。",
        "points": [],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "8",
        "source_ref": "https://m.renrendoc.com/paper/447450867.html",
        "verified": 1,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"一种点击化学方法合成聚硫酸酯(W)的路线如下所示。下列说法正确的是（　　）",
        "options": [
            r"双酚 A 是苯酚的同系物，可与甲醛发生聚合反应",
            r"催化聚合也可生成 W",
            r"生成 W 的反应③为缩聚反应，同时生成小分子",
            r"在碱性条件下，W 比聚苯乙烯更难降解",
        ],
        "answer": "B",
        "analysis": r"解析：同系物要求官能团种类与数目相同，双酚 A 含两个酚羟基而苯酚只含一个，二者不互为同系物，A 错；由 W 的结构简式可推知 W 可由催化聚合得到，B 正确；反应③生成的小分子为甲醇，C 错；W 含酯基，碱性条件下易水解，比聚苯乙烯更易降解，D 错。",
        "points": [],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "9",
        "source_ref": "https://m.renrendoc.com/paper/447450867.html",
        "verified": 1,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 2,
        "stem": r"实验室中利用下图装置验证铁与水蒸气反应。下列说法错误的是（　　）",
        "options": [
            r"反应为 $3\mathrm{Fe}+4\mathrm{H}_2\mathrm{O(g)}\xrightarrow{\text{高温}}\mathrm{Fe}_3\mathrm{O}_4+4\mathrm{H}_2$",
            r"酒精灯移至湿棉花下方实验效果更好",
            r"用火柴点燃肥皂泡检验生成的氢气",
            r"使用硬质玻璃试管盛装还原铁粉",
        ],
        "answer": "B",
        "analysis": r"解析：铁与水蒸气在高温下反应生成 $\mathrm{Fe}_3\mathrm{O}_4$ 和 $\mathrm{H}_2$，A 正确；该反应需高温，将酒精灯移至湿棉花下方，铁粉处不能达到高温，B 错误；生成的 $\mathrm{H}_2$ 可吹出肥皂泡，点燃可闻尖锐爆鸣声，C 正确；反应需高温，故使用耐高温的硬质玻璃试管，D 正确。",
        "points": [],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "10",
        "source_ref": "https://m.renrendoc.com/paper/447450867.html",
        "verified": 1,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"对于下列过程中发生的化学反应，相应离子方程式正确的是（　　）",
        "options": [
            r"试管壁上的银镜用稀硝酸清洗：$\mathrm{Ag}+2\mathrm{H}^++\mathrm{NO}_3^-=\mathrm{Ag}^++\mathrm{NO}_2\uparrow+\mathrm{H}_2\mathrm{O}$",
            r"工业废水中的 $\mathrm{Pb}^{2+}$ 用 FeS 去除：$\mathrm{Pb}^{2+}+\mathrm{S}^{2-}=\mathrm{PbS}\downarrow$",
            r"海水提溴过程中将溴吹入 $\mathrm{SO}_2$ 吸收塔：$\mathrm{Br}_2+\mathrm{SO}_2+2\mathrm{H}_2\mathrm{O}=2\mathrm{Br}^-+\mathrm{SO}_4^{2-}+4\mathrm{H}^+$",
            r"用草酸标准溶液测定高锰酸钾溶液的浓度：$2\mathrm{MnO}_4^-+5\mathrm{C}_2\mathrm{O}_4^{2-}+16\mathrm{H}^+=2\mathrm{Mn}^{2+}+10\mathrm{CO}_2\uparrow+8\mathrm{H}_2\mathrm{O}$",
        ],
        "answer": "C",
        "analysis": r"解析：银与稀硝酸反应为 $3\mathrm{Ag}+4\mathrm{H}^++\mathrm{NO}_3^-=3\mathrm{Ag}^++\mathrm{NO}\uparrow+2\mathrm{H}_2\mathrm{O}$，A 错；FeS 为难溶物不能拆，正确应为 $\mathrm{Pb}^{2+}+\mathrm{FeS}=\mathrm{Fe}^{2+}+\mathrm{PbS}\downarrow$，B 错；海水提溴中 $\mathrm{Br}_2$ 与 $\mathrm{SO}_2$ 发生氧化还原生成 HBr 与 $\mathrm{H}_2\mathrm{SO}_4$，C 正确；草酸为弱酸不能拆，正确应为 $2\mathrm{MnO}_4^-+5\mathrm{H}_2\mathrm{C}_2\mathrm{O}_4+6\mathrm{H}^+=2\mathrm{Mn}^{2+}+10\mathrm{CO}_2\uparrow+8\mathrm{H}_2\mathrm{O}$，D 错。",
        "points": [],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "11",
        "source_ref": "https://m.renrendoc.com/paper/447450867.html",
        "verified": 1,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"我国科学家最近研究的一种无机盐 $\mathrm{Y}_3[\mathrm{Z}(\mathrm{WX})_6]_2$ 纳米药物具有高效的细胞内亚铁离子捕获和抗氧化能力。W、X、Y、Z 的原子序数依次增加，且 W、X、Y 属于不同族的短周期元素。W 的外层电子数是其内层电子数的 2 倍，X 和 Y 的第一电离能都比左右相邻元素的高。Z 的 M 层未成对电子数为 4。下列叙述错误的是（　　）",
        "options": [
            r"W、X、Y、Z 四种元素的单质中 Z 的熔点最高",
            r"在 X 的简单氢化物中 X 原子轨道杂化类型为 $\mathrm{sp}^3$",
            r"Y 的氢氧化物难溶于 NaCl 溶液，可以溶于 $\mathrm{NH}_4\mathrm{Cl}$ 溶液",
            r"$\mathrm{Y}_3[\mathrm{Z}(\mathrm{WX})_6]_2$ 中 $\mathrm{WX}^-$ 提供电子对与 $\mathrm{Z}^{3+}$ 形成配位键",
        ],
        "answer": "A",
        "analysis": r"解析：W 外层电子数是内层 2 倍⇒W 为 C；X、Y 第一电离能比相邻高⇒处于第ⅡA 或ⅤA 族，结合原子序数推得 X 为 N、Y 为 Mg；Z 的 M 层未成对电子数为 4⇒Z 为 Fe。四种单质中金刚石（共价晶体）熔点最高，A 错；$\mathrm{NH}_3$ 中 N 价层电子对数为 4，杂化类型为 $\mathrm{sp}^3$，B 对；$\mathrm{Mg(OH)}_2$ 难溶于 NaCl，可与 $\mathrm{NH}_4\mathrm{Cl}$ 反应溶解，C 对；$\mathrm{Fe}^{3+}$ 有空轨道、$\mathrm{CN}^-$ 提供孤电子对形成配位键，D 对。",
        "points": [],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "12",
        "source_ref": "https://m.renrendoc.com/paper/447450867.html",
        "verified": 1,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"一种可植入体内的微型电池工作原理如图所示，通过 CuO 催化消耗血糖发电，从而控制血糖浓度。电池工作时，下列叙述错误的是（　　）",
        "options": [
            r"电池总反应为 $2\mathrm{C}_6\mathrm{H}_{12}\mathrm{O}_6+\mathrm{O}_2=2\mathrm{C}_6\mathrm{H}_{12}\mathrm{O}_7$",
            r"b 电极上 CuO 通过 Cu(Ⅱ)和 Cu(Ⅰ)相互转变起催化作用",
            r"消耗 18 mg 葡萄糖，理论上 a 电极有 0.4 mmol 电子流入",
            r"两电极间血液中的 $\mathrm{Na}^+$ 在电场驱动下的迁移方向为 b→a",
        ],
        "answer": "C",
        "analysis": r"解析：由图知总反应为 $2\mathrm{C}_6\mathrm{H}_{12}\mathrm{O}_6+\mathrm{O}_2=2\mathrm{C}_6\mathrm{H}_{12}\mathrm{O}_7$，A 对；b 极发生 $\mathrm{CuO}\to\mathrm{Cu}_2\mathrm{O}\to\mathrm{CuO}$，CuO 反应前后不变起催化作用，B 对；消耗 18 mg（0.1 mmol）葡萄糖转移 0.2 mmol 电子，故 a 极有 0.2 mmol 电子流入，C 错；阳离子向正极迁移，b 为负极、a 为正极，故 $\mathrm{Na}^+$ 由 b→a，D 对。",
        "points": [],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "13",
        "source_ref": "https://m.renrendoc.com/paper/447450867.html",
        "verified": 1,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"常温下 $\mathrm{CH}_2\mathrm{ClCOOH}$ 和 $\mathrm{CHCl}_2\mathrm{COOH}$ 的两种溶液中，分布系数 $\delta$ 与 pH 的变化关系如图所示。下列叙述正确的是（　　）",
        "options": [
            r"曲线 M 表示 $\delta(\mathrm{CHCl}_2\mathrm{COO}^-)$～pH 的变化关系",
            r"若酸的初始浓度为 $0.10\ \mathrm{mol\cdot L^{-1}}$，则 a 点对应的溶液中有 $c(\mathrm{H}^+)=c(\mathrm{CHCl}_2\mathrm{COO}^-)+c(\mathrm{OH}^-)$",
            r"$\mathrm{CH}_2\mathrm{ClCOOH}$ 的电离常数 $K_\mathrm{a}=10^{-1.3}$",
            r"pH=2.08 时，$\dfrac{\alpha(\mathrm{CH}_2\mathrm{ClCOOH})}{\alpha(\mathrm{CHCl}_2\mathrm{COOH})}=\dfrac{0.15}{0.85}$",
        ],
        "answer": "D",
        "analysis": r"解析：—$\mathrm{CHCl}_2$ 极性大于 —$\mathrm{CH}_2\mathrm{Cl}$，$\mathrm{CHCl}_2\mathrm{COOH}$ 酸性更强，其 $\delta(\mathrm{CHCl}_2\mathrm{COO}^-)$ 更大，曲线 M 表示它，A 错；初始浓度 0.10 mol·L⁻¹ 时 pH>1，而 a 点 pH=1 需外加酸，B 错；由 d 点 pH=2.8 时 $c(\mathrm{CH}_2\mathrm{ClCOOH})=c(\mathrm{CH}_2\mathrm{ClCOO}^-)$ 得 $K_\mathrm{a}=10^{-2.8}$，C 错；pH=2.08 时 $\delta(\mathrm{CH}_2\mathrm{ClCOO}^-)=0.15$、$\delta(\mathrm{CHCl}_2\mathrm{COO}^-)=0.85$，电离度之比为 0.15∶0.85，D 对。",
        "points": [],
    },

    # ============ 二、2023 新课标卷 选择题（3 道，均 verified=1） ============
    {
        "year": 2023,
        "paper": "新课标卷",
        "question_no": "7",
        "source_ref": "https://mip.21cnjy.com/P/26500678.html",
        "verified": 1,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 2,
        "stem": r"化学在文物的研究和修复中有重要作用。下列说法错误的是（　　）",
        "options": [
            r"竹简的成分之一纤维素属于天然高分子",
            r"龟甲的成分之一羟基磷灰石属于无机物",
            r"古陶瓷修复所用的熟石膏，其成分为 $\mathrm{Ca(OH)}_2$",
            r"古壁画颜料中所用的铁红，其成分为 $\mathrm{Fe}_2\mathrm{O}_3$",
        ],
        "answer": "C",
        "analysis": r"解析：熟石膏的主要成分为 $2\mathrm{CaSO}_4\cdot\mathrm{H}_2\mathrm{O}$，不是 $\mathrm{Ca(OH)}_2$，C 错；纤维素是天然高分子，A 对；羟基磷灰石 $\mathrm{Ca}_5(\mathrm{PO}_4)_3\mathrm{OH}$ 为无机物，B 对；$\mathrm{Fe}_2\mathrm{O}_3$ 俗称铁红，D 对。",
        "points": [],
    },
    {
        "year": 2023,
        "paper": "新课标卷",
        "question_no": "8",
        "source_ref": "https://mip.21cnjy.com/P/26500678.html",
        "verified": 1,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"光学性能优良的高分子材料聚碳酸异山梨醇酯可由如下反应制备。下列说法错误的是（　　）",
        "options": [
            r"该高分子材料可降解",
            r"异山梨醇分子中有 3 个手性碳",
            r"反应式中化合物 X 为甲醇",
            r"该聚合反应为缩聚反应",
        ],
        "answer": "B",
        "analysis": r"解析：该高分子含酯基，可水解降解，A 对；异山梨醇分子中有 4 个手性碳，B 错；由元素守恒推得 X 为 $\mathrm{CH}_3\mathrm{OH}$，C 对；反应除生成高分子外还生成小分子甲醇，属缩聚反应，D 对。",
        "points": [],
    },
    {
        "year": 2023,
        "paper": "新课标卷",
        "question_no": "9",
        "source_ref": "https://mip.21cnjy.com/P/26500678.html",
        "verified": 1,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"一种可吸附甲醇的材料，其化学式为 $[\mathrm{C}(\mathrm{NH}_2)_3]_4[\mathrm{B}(\mathrm{OCH}_3)_4]_3\mathrm{Cl}$，部分晶体结构如下图所示，其中 $[\mathrm{C}(\mathrm{NH}_2)_3]^+$ 为平面结构。下列说法正确的是（　　）",
        "options": [
            r"该晶体中存在 N—H…O 氢键",
            r"基态原子的第一电离能：$\mathrm{C}<\mathrm{N}<\mathrm{O}$",
            r"基态原子未成对电子数：$\mathrm{B}<\mathrm{C}<\mathrm{O}<\mathrm{N}$",
            r"晶体中 B、N 和 O 原子轨道的杂化类型相同",
        ],
        "answer": "A",
        "analysis": r"解析：由结构图可知存在 N—H…O 氢键，A 对；N 的 2p 轨道半充满，第一电离能 $\mathrm{N}>\mathrm{O}$，B 错；B、C、O、N 未成对电子数分别为 1、2、2、3，C 错；B、O 为 $\mathrm{sp}^3$ 杂化，而 $[\mathrm{C}(\mathrm{NH}_2)_3]^+$ 为平面结构，其中 N 为 $\mathrm{sp}^2$ 杂化，D 错。",
        "points": [],
    },

    # ============ 三、非选择题（实验题 / 填空题，含真实换行，使用 r"""..."""） ============
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "27",
        "source_ref": "https://m.renrendoc.com/paper/447450867.html",
        "verified": 1,
        "qtype": "实验题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"""钴及其化合物在制造合金、磁性材料、催化剂及陶瓷釉等方面有着广泛应用。一种从湿法炼锌废渣（主要含 Co、Zn、Pb、Fe 的单质或氧化物）中富集回收得到含锰高钴成品的工艺如下。

已知溶液中相关离子开始沉淀和沉淀完全（$c\le 1.0\times10^{-5}\ \mathrm{mol\cdot L^{-1}}$）时的 pH：
$\mathrm{Fe^{3+}}$　$\mathrm{Fe^{2+}}$　$\mathrm{Co^{3+}}$　$\mathrm{Co^{2+}}$　$\mathrm{Zn^{2+}}$
开始沉淀的 pH：1.5　6.9　—　7.4　6.2
沉淀完全的 pH：2.8　8.4　1.1　9.4　8.2

回答下列问题：
(1) “酸浸”前废渣需粉碎处理，目的是______________；“滤渣1”中金属元素主要为__________。
(2) “过滤1”后的溶液中加入 $\mathrm{MnO_2}$ 的作用是________________________。取少量反应后的溶液，加入化学试剂__________检验__________，若出现蓝色沉淀，需补加 $\mathrm{MnO_2}$。
(3) “氧化沉钴”中氧化还原反应的离子方程式为__________________、__________________。
(4) “除钴液”中主要的盐有__________（写化学式），残留的 $\mathrm{Co^{3+}}$ 浓度为__________ $\mathrm{mol\cdot L^{-1}}$。""",
        "options": [],
        "answer": r"(1) 增大固液接触面积，加快酸浸速率，提高浸取效率；Pb　(2) 将 $\mathrm{Fe^{2+}}$ 氧化为 $\mathrm{Fe^{3+}}$，便于后续调 pH 除去 Fe；铁氰化钾（$\mathrm{K_3[Fe(CN)_6]}$）溶液；$\mathrm{Fe^{2+}}$　(3) $\mathrm{MnO_4^-}+3\mathrm{Co^{2+}}+7\mathrm{H_2O}=\mathrm{MnO_2}\downarrow+3\mathrm{Co(OH)_3}\downarrow+5\mathrm{H^+}$、$3\mathrm{Mn^{2+}}+2\mathrm{MnO_4^-}+2\mathrm{H_2O}=5\mathrm{MnO_2}\downarrow+4\mathrm{H^+}$　(4) $\mathrm{ZnSO_4}$、$\mathrm{K_2SO_4}$；$1.0\times10^{-16.7}$",
        "analysis": r"解析：(1) 粉碎可增大废渣与硫酸的接触面积，提高酸浸速率；Pb 及其氧化物与硫酸生成的硫酸铅难溶，故滤渣1中金属元素主要为 Pb。(2) 加入 $\mathrm{MnO_2}$ 将 $\mathrm{Fe^{2+}}$ 氧化为 $\mathrm{Fe^{3+}}$，以便调 pH 时除去 Fe；用铁氰化钾溶液检验 $\mathrm{Fe^{2+}}$，出现蓝色沉淀（滕氏蓝）说明仍有 $\mathrm{Fe^{2+}}$。(3) “氧化沉钴”发生 $\mathrm{MnO_4^-}+3\mathrm{Co^{2+}}+7\mathrm{H_2O}=\mathrm{MnO_2}\downarrow+3\mathrm{Co(OH)_3}\downarrow+5\mathrm{H^+}$，以及 $\mathrm{Mn^{2+}}$ 与 $\mathrm{MnO_4^-}$ 的反应 $3\mathrm{Mn^{2+}}+2\mathrm{MnO_4^-}+2\mathrm{H_2O}=5\mathrm{MnO_2}\downarrow+4\mathrm{H^+}$。(4) 除钴液中主要盐为 $\mathrm{ZnSO_4}$ 和 $\mathrm{K_2SO_4}$；由 $\mathrm{Co^{3+}}$ 沉淀完全 pH=1.1 得 $K_\mathrm{sp}[\mathrm{Co(OH)_3}]=1.0\times10^{-16.7}$，pH=5 时 $c(\mathrm{OH^-})=10^{-9}$，残留 $c(\mathrm{Co^{3+}})=1.0\times10^{-16.7}\ \mathrm{mol\cdot L^{-1}}$。",
        "points": [
            r"第(1)问：答出“增大接触面积、加快酸浸速率”得 2 分；“滤渣1”金属元素为 Pb 得 1 分",
            r"第(2)问：$\mathrm{MnO_2}$ 作用为氧化 $\mathrm{Fe^{2+}}$ 为 $\mathrm{Fe^{3+}}$ 得 2 分；检验试剂为铁氰化钾溶液、检验对象为 $\mathrm{Fe^{2+}}$ 各 1 分",
            r"第(3)问：写出两个离子方程式各 2 分（共 4 分）",
            r"第(4)问：除钴液主要盐为 $\mathrm{ZnSO_4}$、$\mathrm{K_2SO_4}$ 得 2 分；残留 $\mathrm{Co^{3+}}$ 浓度为 $1.0\times10^{-16.7}\ \mathrm{mol\cdot L^{-1}}$ 得 2 分",
        ],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "29",
        "source_ref": "https://m.renrendoc.com/paper/447450867.html",
        "verified": 1,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 5,
        "stem": r"""$\mathrm{Ni(CO)_4}$（四羰合镍，沸点 43 ℃）可用于制备高纯镍，也是有机化合物羰基化反应的催化剂。回答下列问题：
(1) Ni 基态原子价电子的轨道表示式为__________。镍的晶胞结构类型与铜的相同，晶胞体积为 $a^3$，镍原子半径为__________。
(2) $\mathrm{Ni(CO)_4}$ 结构如图所示，其中含有 $\sigma$ 键的数目为__________，$\mathrm{Ni(CO)_4}$ 晶体的类型为__________。
(3) 在总压分别为 0.10、0.50、1.0、2.0 MPa 下，$\mathrm{Ni(s)}$ 和 $\mathrm{CO(g)}$ 反应达平衡时，$\mathrm{Ni(CO)_4}$ 体积分数 $x$ 与温度的关系如图所示。反应 $\mathrm{Ni(s)}+4\mathrm{CO(g)}=\mathrm{Ni(CO)_4(g)}$ 的 $\Delta H$__________0（填“大于”或“小于”），从热力学角度考虑，__________有利于 $\mathrm{Ni(CO)_4}$ 的生成（写出两点），$p_3$、100 ℃ 时 CO 的平衡转化率 $\alpha=$__________，该温度下平衡常数 $K_p=$__________ $(\mathrm{MPa})^{-3}$。
(4) 对于同位素交换反应 $\mathrm{Ni(C^{16}O)_4}+\mathrm{C^{18}O}\to\mathrm{Ni(C^{16}O)_3C^{18}O}+\mathrm{C^{16}O}$，$20\ \mathrm{^\circ C}$ 时反应物浓度随时间变化关系为 $c_t[\mathrm{Ni(C^{16}O)_4}]=c_0[\mathrm{Ni(C^{16}O)_4}]\mathrm{e}^{-kt}$（$k$ 为速率常数），则 $\mathrm{Ni(C^{16}O)_4}$ 反应一半所需时间 $t_{1/2}=$__________（用 $k$ 表示）。""",
        "options": [],
        "answer": r"(1) $\mathrm{3d^8 4s^2}$ 的轨道表示式（略）；$\dfrac{\sqrt{2}}{4}a$　(2) 8；分子晶体　(3) 小于；降低温度、增大压强；$97.3\%$；$9\times10^3$　(4) $\dfrac{\ln 2}{k}$",
        "analysis": r"解析：(1) Ni 为 28 号元素，价电子排布 $\mathrm{3d^8 4s^2}$；镍为面心立方最密堆积，晶胞棱长 $a$，$4r=\sqrt{2}a$，故 $r=\dfrac{\sqrt{2}}{4}a$。(2) 单键为 $\sigma$ 键，4 个 CO 各含 1 个 C—O $\sigma$ 键共 4 个，加上 4 个 Ni—C $\sigma$ 键，共 8 个 $\sigma$ 键；沸点低，属分子晶体。(3) 升温使 $\mathrm{Ni(CO)_4}$ 体积分数减小，平衡逆向，故 $\Delta H<0$；该反应气体分子数减小且放热，降温、增压有利；由图 $p_3=1.0\ \mathrm{MPa}$、$x=0.9$，列三段式解得转化率约 $97.3\%$，$K_p=\dfrac{0.9}{(0.1)^4}=9\times10^3\ (\mathrm{MPa})^{-3}$。(4) 由 $\dfrac{1}{2}c_0=c_0\mathrm{e}^{-kt}$ 得 $t_{1/2}=\dfrac{\ln 2}{k}$。",
        "points": [
            r"第(1)问：写出 $\mathrm{3d^8 4s^2}$ 轨道表示式得 2 分；镍原子半径 $\dfrac{\sqrt{2}}{4}a$ 得 1 分",
            r"第(2)问：$\sigma$ 键数目为 8 得 2 分；晶体类型为分子晶体得 1 分",
            r"第(3)问：判断 $\Delta H<0$ 得 1 分；答出“降温、增压”两点得 2 分；转化率 $97.3\%$ 得 1 分；$K_p=9\times10^3$ 得 1 分",
            r"第(4)问：由指数衰减式推导 $t_{1/2}=\dfrac{\ln 2}{k}$ 得 2 分",
        ],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "28",
        "source_ref": "https://static-gkcx.gaokao.cn/upload/zhenti/20240622/1719052401_9823.pdf",
        "verified": 1,
        "qtype": "实验题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"""吡咯类化合物在导电聚合物、化学传感器及药物制剂上有着广泛应用。一种合成 1-(4-甲氧基苯基)-2,5-二甲基吡咯（用吡咯 X 表示）的反应和方法如下：实验装置如图所示，将 100 mmol 己-2,5-二酮（熔点 −5.5 ℃，密度 0.737 g·cm⁻³）与 100 mmol 4-甲氧基苯胺（熔点 57 ℃）放入①中，搅拌。待反应完成后，加入 50% 的乙醇溶液，析出浅棕色固体。加热至 65 ℃至固体溶解，加入脱色剂，回流 20 min，趁热过滤。滤液静置至室温，冰水浴冷却，有大量白色固体析出。经过滤、洗涤、干燥得到产品。回答下列问题：
(1) 量取己-2,5-二酮应使用的仪器为__________（填名称）。
(2) 仪器①用铁夹固定在仪器③上，③的名称是__________；仪器②的名称是__________。
(3) “搅拌”的作用是____________________。
(4) “加热”方式为______________________。
(5) 使用的“脱色剂”是___________________。
(6) “趁热过滤”的目的是______________________________；用__________洗涤白色固体。
(7) 若需进一步提纯产品，可采用的方法是______________________________。""",
        "options": [],
        "answer": r"(1) 酸式滴定管　(2) 铁架台；球形冷凝管　(3) 使固液充分接触，加快反应速率　(4) 水浴加热　(5) 活性炭　(6) 防止产品结晶损失，提高产率；50% 乙醇溶液　(7) 重结晶",
        "analysis": r"解析：(1) 己-2,5-二酮摩尔质量 114 g·mol⁻¹，100 mmol 约 11.4 g，体积约 15.47 mL；酮类物质对橡胶有腐蚀性，不能用碱式滴定管，应选用酸式滴定管（官方参考答案；个别资料作“量筒”，以官方答案为准）。(2) ③为铁架台，②为球形冷凝管。(3) 搅拌使固液反应物充分接触、加快反应速率。(4) 控温 65 ℃，采用水浴加热。(5) 活性炭可吸附有色物质，作脱色剂。(6) 趁热过滤使产品尽可能多地进入滤液，防止产品结晶损失，提高产率；常温下产品在 50% 乙醇中溶解度小，用其洗涤以减少溶解损失。(7) 产品溶解度随温度变化较大，用重结晶进一步提纯。已双源核对（掌上高考官方真题 PDF、21世纪教育网真题解析）。",
        "points": [
            r"第(1)问：仪器为酸式滴定管得 1 分",
            r"第(2)问：③为铁架台、②为球形冷凝管各 1 分",
            r"第(3)问：答出“加快反应速率 / 使混合均匀”得 1 分",
            r"第(4)问：水浴加热得 1 分",
            r"第(5)问：活性炭得 1 分",
            r"第(6)问：趁热过滤目的、洗涤试剂各 1 分",
            r"第(7)问：重结晶得 1 分",
        ],
    },

    # ============ 四、2024 新课标卷 第30题 有机合成推断（四氟咯草胺） ============
    # 来源：学科网《精品解析：2024年高考新课标卷理综化学高考真题解析（参考版）》
    # https://www.zxxk.com/soft/45822199.html
    # 教习网同题：http://51jiaoxi.com/doc-16007197.html
    # 说明：合成路线与各物质结构简式在原卷中为图，本文件用文字转述；需写结构简式的子问，
    # 答案栏注明「原卷为结构简式图」并给出可核验的推导依据，核对请以来源原卷为准。
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "30",
        "source_ref": "https://www.zxxk.com/soft/45822199.html",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（第30题 第(1)问：反应类型与碳酸钾的作用）四氟咯草胺（化合物 G）是一种新型除草剂，可有效控制稻田杂草。G 的一条合成路线如下（略去部分试剂和条件，忽略立体化学；合成路线图为文字转述，做题请对照原卷）：A（含 C—Br 键）与化合物 B 在 $\mathrm{K_2CO_3}$ 存在下发生反应①生成 C。已知反应Ⅰ：$\mathrm{ROH}\xrightarrow[\text{(C}_2\text{H}_5)_3\text{N}]{\mathrm{CH_3SO_2Cl}}\mathrm{ROSO_2CH_3}+(\mathrm{C_2H_5})_3\mathrm{N\cdot HCl}$。反应①的反应类型为__________；反应中加入 $\mathrm{K_2CO_3}$ 的作用是__________。",
        "options": [],
        "answer": r"取代反应；消耗（与）反应生成的 HBr 反应，促进反应正向进行",
        "analysis": r"解析：由 A、C 的结构简式和 B 的分子式可知 B 为含 N—H 的杂环胺（结构简式见原卷图）。A 中的 C—Br σ 键断裂、与 B 中 N—H 形成 C—N σ 键，生成 C 和小分子 HBr，属取代反应；加入的 $\mathrm{K_2CO_3}$ 与生成的 HBr 反应，降低产物浓度，使平衡正向移动，提高原料转化率。来源：学科网 2024 新课标卷理综化学真题解析（https://www.zxxk.com/soft/45822199.html）。",
        "points": [
            r"第(1)问：答出「取代反应」得 1 分；答出「与生成的 HBr 反应，促进反应正向进行」得 1 分",
        ],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "30",
        "source_ref": "https://www.zxxk.com/soft/45822199.html",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（第30题 第(2)问：杂化方式计数）四氟咯草胺（化合物 G）的合成路线中，C 经羰基加氢还原得到 D（D 的结构简式见原卷图）。D 分子中采用 $\mathrm{sp}^3$ 杂化的碳原子数是__________。",
        "options": [],
        "answer": "5",
        "analysis": r"解析：C→D 为羰基的加氢还原，D 中新生成醇羟基碳；结合原卷 D 的结构简式，采取 $\mathrm{sp}^3$ 杂化的饱和碳原子共 5 个（原卷图中标注「*」的 5 个碳原子）。来源：学科网 2024 新课标卷理综化学真题解析（https://www.zxxk.com/soft/45822199.html）。",
        "points": [
            r"第(2)问：答「5」得 2 分",
        ],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "30",
        "source_ref": "http://51jiaoxi.com/doc-16007197.html",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（第30题 第(3)问：反应条件分析）四氟咯草胺合成路线中，反应③与已知反应Ⅰ（$\mathrm{ROH}\to\mathrm{ROSO_2CH_3}$，用 $(\mathrm{C_2H_5})_3\mathrm{N}$ 结合生成的 HCl）类似。对照已知反应Ⅰ，反应③不使用 $(\mathrm{C_2H_5})_3\mathrm{N}$ 也能进行，原因是__________。",
        "options": [],
        "answer": r"D 分子中同时存在 —OH 和叔氨基（分子内的叔氨基可代替 $(\mathrm{C_2H_5})_3\mathrm{N}$ 结合生成的 HCl，促进反应正向进行）",
        "analysis": r"解析：已知反应Ⅰ中 $(\mathrm{C_2H_5})_3\mathrm{N}$ 的作用是结合生成的小分子 HCl 生成铵盐，促进反应正向进行。由 D 的结构简式可知，D 分子中同时存在 —OH 和叔氨基（—$\mathrm{NR_2}$，见原卷 D 的结构图），其叔氨基即可结合 HCl 生成铵盐，因此反应③不加 $(\mathrm{C_2H_5})_3\mathrm{N}$ 也能进行。来源：教习网《专题16 有机化学基础综合题》（http://51jiaoxi.com/doc-16007197.html）。",
        "points": [
            r"第(3)问：答出「D 分子中同时存在 —OH 和叔氨基」得 2 分；说明「叔氨基可结合 HCl」得 1 分",
        ],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "30",
        "source_ref": "https://www.zxxk.com/soft/45822199.html",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（第30题 第(4)问：官能团名称）四氟咯草胺（化合物 G）的合成路线中，D 依次经反应③（类似已知反应Ⅰ）与反应④（取代反应）生成 E。E 中含氧官能团名称是__________。",
        "options": [],
        "answer": "酯基",
        "analysis": r"解析：由原卷 E 的结构简式可知，其含氧官能团为酯基（—COO—）。来源：学科网 2024 新课标卷理综化学真题解析（https://www.zxxk.com/soft/45822199.html）。",
        "points": [
            r"第(4)问：答「酯基」得 1 分",
        ],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "30",
        "source_ref": "https://www.zxxk.com/soft/45822199.html",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 5,
        "stem": r"（第30题 第(5)问①：推结构简式）四氟咯草胺（化合物 G）的合成路线中，E 经反应⑤生成 F，F 再经反应⑥生成 G。已知反应Ⅱ为原卷图中的转化（$\mathrm{R_1}$ 为烃基或 H，R、$\mathrm{R_2}$、$\mathrm{R_3}$、$\mathrm{R_4}$ 为烃基）。F 的结构简式是__________。",
        "options": [],
        "answer": r"（原卷答案为结构简式图，文字无法完整转述，请对照原卷或学科网解析中的 F 结构图核对）推导依据：由 E、G 的结构简式及反应⑤、⑥所用试剂，结合 F 的分子式（见原卷）可确定 F 为含 —$\mathrm{CF_3}$ 的酯类中间体",
        "analysis": r"解析：根据 E、G 的结构简式和反应⑤、反应⑥的反应试剂，结合 F 的分子式可推出 F 的结构简式为原卷图。本题答案以结构图形式给出，文字转述易失真，核对请以学科网原卷解析（https://www.zxxk.com/soft/45822199.html）中的 F 结构简式为准。",
        "points": [
            r"第(5)问①：写出 F 的结构简式得 2 分（原卷为图）",
        ],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "30",
        "source_ref": "https://www.zxxk.com/soft/45822199.html",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 5,
        "stem": r"（第30题 第(5)问②：推第一步产物结构简式）四氟咯草胺（化合物 G）的合成路线中，反应⑤分两步进行，第一步产物的分子式为 $\mathrm{C_{15}H_{18}F_3NO_4}$，其结构简式是__________。",
        "options": [],
        "answer": r"（原卷答案为结构简式图，文字无法完整转述，请对照原卷或学科网解析核对）推导依据：由分子式 $\mathrm{C_{15}H_{18}F_3NO_4}$ 得不饱和度 $\Omega=6$，对比 E 的结构简式，该产物比 E 少一个苯环和一个饱和碳原子",
        "analysis": r"解析：已知反应⑤分两步进行，结合 F 的结构简式知第二步为第一步产物发生已知反应Ⅱ。由第一步产物分子式 $\mathrm{C_{15}H_{18}F_3NO_4}$ 算得不饱和度为 6，与 E 的结构简式对比，该产物比 E 少了一个苯环和一个饱和碳原子，据此写出原卷图中的结构简式。核对请以学科网原卷解析（https://www.zxxk.com/soft/45822199.html）为准。",
        "points": [
            r"第(5)问②：写出第一步产物的结构简式得 2 分（原卷为图）",
        ],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "30",
        "source_ref": "http://51jiaoxi.com/doc-16007197.html",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（第30题 第(6)问：手性碳原子）四氟咯草胺（化合物 G）的结构简式见原卷图（图中碳原子已编号）。G 中手性碳原子是__________（写出序号）。",
        "options": [],
        "answer": "3 和 4（即 3、4 号碳原子）",
        "analysis": r"解析：手性碳原子指连有四个各不相同原子或原子团的饱和碳原子。由原卷 G 的结构简式（碳原子已编号）逐一检查，只有 3 号与 4 号碳原子连有四个不同的原子或原子团，故 G 中的手性碳原子为 3 和 4。来源：教习网《专题16 有机化学基础综合题》（http://51jiaoxi.com/doc-16007197.html）。",
        "points": [
            r"第(6)问：答出「3 和 4」得 2 分",
        ],
    },
    {
        "year": 2024,
        "paper": "新课标卷",
        "question_no": "30",
        "source_ref": "https://www.zxxk.com/soft/45822199.html",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 5,
        "stem": r"（第30题 第(7)问：同分异构体）化合物 H 是 B 的同分异构体，具有苯环结构，核磁共振氢谱中显示为四组峰，且可以发生已知反应Ⅱ。则 H 的可能结构是__________。",
        "options": [],
        "answer": r"（原卷答案为两种结构简式图，文字无法完整转述，请对照原卷或学科网解析核对）推导依据：H 能发生已知反应Ⅱ，说明具有已知反应Ⅱ所需的结构单元；含苯环且核磁共振氢谱只有四组峰，说明分子高度对称",
        "analysis": r"解析：由思路分析知 B 的结构简式为原卷图，其同分异构体 H 能发生已知反应Ⅱ，说明其具有已知反应Ⅱ所需的结构单元；H 具有苯环结构且核磁共振氢谱显示四组峰，说明结构对称，据此写出原卷图中的两种可能结构简式。核对请以学科网原卷解析（https://www.zxxk.com/soft/45822199.html）为准。",
        "points": [
            r"第(7)问：写出两种符合条件的结构简式各 1 分（原卷为图）",
        ],
    },

    # ============ 五、2025 云南卷（新高考 3+1+2，化学为云南省自主命题）整套 ============
    # 来源：21 世纪教育网《2025年普通高中学业水平选择性考试（云南卷）化学（pdf版，含答案和答题卡）》
    # https://zy.21cnjy.com/24900045
    # 辅助核对：教习网《2025年高考云南卷化学高考真题（原卷版＋解析版）》
    # https://www.51jiaoxi.com/doc-17693629.html
    # 说明：化学为云南自主命题（云南省招生考试院《云南省2025年普通高校招生考试安排和录取
    # 工作实施方案》：全国统考科目全国统一命题，选择性考试科目由云南省自主命题），
    # 故 paper 记作「2025 云南卷」。全部新条目 verified=0，待双源核对后统一置 1。
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "1",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 2,
        "stem": r"（2025 云南卷 第1题）画中有“化”，多彩中华。下列叙述正确的是（　　）",
        "options": [
            r"岩彩壁画颜料所用贝壳粉，主要成分属于硅酸盐",
            r"油画颜料调和剂所用核桃油，属于有机高分子",
            r"竹胎漆画颜料赭石的主要成分氧化铁，耐酸、碱",
            r"水墨画墨汁的主要成分碳，常温不易被氧化",
        ],
        "answer": "D",
        "analysis": r"解析：贝壳粉的主要成分为 $\mathrm{CaCO_3}$，属碳酸盐，不是硅酸盐，A 错；核桃油属油脂，相对分子质量仅几百，不是有机高分子，B 错；赭石的主要成分 $\mathrm{Fe_2O_3}$ 是碱性氧化物，能与酸反应（$\mathrm{Fe_2O_3}+6\mathrm{H}^+=2\mathrm{Fe}^{3+}+3\mathrm{H_2O}$），不耐酸，C 错；墨汁的主要成分是碳单质，常温下化学性质稳定，不易被氧化，D 对。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "2",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 2,
        "stem": r"（2025 云南卷 第2题）下列化学用语或图示表示正确的是（　　）",
        "options": [
            r"$\mathrm{NH_3}$ 的 VSEPR 模型：（原卷选项图为四面体形）",
            r"$\mathrm{Na_2S}$ 的电子式：$\mathrm{Na_2}[\colon\ddot{\mathrm{S}}\colon]$",
            r"Cl 的原子结构示意图：（原卷选项图为核电荷数 +17、核外电子排布 2、8、8）",
            r"$\mathrm{Al_2(SO_4)_3}$ 溶于水的电离方程式：$\mathrm{Al_2(SO_4)_3}\rightleftharpoons 2\mathrm{Al}^{3+}+3\mathrm{SO_4}^{2-}$",
        ],
        "answer": "A",
        "analysis": r"解析：$\mathrm{NH_3}$ 中心 N 原子价层电子对数 $=3+\dfrac{5-3\times1}{2}=4$，含 1 对孤电子对，VSEPR 模型为四面体形，A 对；$\mathrm{Na_2S}$ 为离子化合物，相同离子不能合并，正确电子式为 $\mathrm{Na}^+[\colon\ddot{\mathrm{S}}\colon]^{2-}\mathrm{Na}^+$，B 错；Cl 原子核外电子排布为 2、8、7，原卷选项图的 2、8、8 是 $\mathrm{Cl}^-$ 的结构示意图，C 错；$\mathrm{Al_2(SO_4)_3}$ 是强电解质，在水中完全电离，应用「$=$」不用可逆号，D 错。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "3",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 2,
        "stem": r"（2025 云南卷 第3题）下列化学方程式错误的是（　　）",
        "options": [
            r"煤制水煤气：$\mathrm{C}+\mathrm{H_2O(g)}\xrightarrow{\text{高温}}\mathrm{CO}+\mathrm{H_2}$",
            r"$\mathrm{Na_2O_2}$ 供氧：$2\mathrm{Na_2O_2}+2\mathrm{CO_2}=2\mathrm{Na_2CO_3}+\mathrm{O_2}$",
            r"覆铜板制作印刷电路板：$2\mathrm{FeCl_3}+3\mathrm{Cu}=3\mathrm{CuCl_2}+2\mathrm{Fe}$",
            r"铅酸蓄电池放电：$\mathrm{Pb}+\mathrm{PbO_2}+2\mathrm{H_2SO_4}=2\mathrm{PbSO_4}+2\mathrm{H_2O}$",
        ],
        "answer": "C",
        "analysis": r"解析：$\mathrm{FeCl_3}$ 与 Cu 反应时 $\mathrm{Fe}^{3+}$ 只被还原为 $\mathrm{Fe}^{2+}$，不可能生成单质 Fe（Cu 的还原性弱于 Fe），正确方程式为 $2\mathrm{FeCl_3}+\mathrm{Cu}=2\mathrm{FeCl_2}+\mathrm{CuCl_2}$，C 错；A、B、D 均符合反应事实。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "4",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第4题）$N_\mathrm{A}$ 为阿伏加德罗常数的值。下列说法正确的是（　　）",
        "options": [
            r"22.4 L $\mathrm{CH_4}$ 中原子的数目为 $5N_\mathrm{A}$",
            r"1 mol $^{18}\mathrm{O}$ 所含中子的数目为 $10N_\mathrm{A}$",
            r"28 g Fe 粉和足量 S 完全反应，转移电子的数目为 $1.5N_\mathrm{A}$",
            r"0.1 L 12 $\mathrm{mol\cdot L^{-1}}$ 盐酸与足量 $\mathrm{MnO_2}$ 反应，生成 $\mathrm{Cl_2}$ 的数目为 $0.3N_\mathrm{A}$",
        ],
        "answer": "B",
        "analysis": r"解析：未指明标准状况，22.4 L $\mathrm{CH_4}$ 的物质的量不能确定为 1 mol，原子数无法确定，A 错；$^{18}\mathrm{O}$ 质子数 8、质量数 18，中子数 $=18-8=10$，1 mol 含 $10N_\mathrm{A}$ 个中子，B 对；Fe 与 S 反应只生成 FeS，28 g（0.5 mol）Fe 转移 1.0 mol 电子即 $1.0N_\mathrm{A}$，C 错；随反应进行浓盐酸变稀后不再与 $\mathrm{MnO_2}$ 反应，生成 $\mathrm{Cl_2}$ 小于 0.3 mol，D 错。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "5",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第5题）下列装置（省略部分夹持装置）或操作正确的是（　　）",
        "options": [
            r"A．用 $\mathrm{NH_4Cl}$ 与 $\mathrm{Ca(OH)_2}$ 固体加热制备 $\mathrm{NH_3}$（原卷图中试管口向上倾斜）",
            r"B．直接在容量瓶中溶解 KCl 固体，配制 100 mL 1.00 $\mathrm{mol\cdot L^{-1}}$ KCl 溶液",
            r"C．在试管中加水探究 Na 与 $\mathrm{H_2O}$ 的反应",
            r"D．用两个连通的烧瓶（$2\mathrm{NO_2}\rightleftharpoons\mathrm{N_2O_4}$）分别置于冷、热水中，探究温度对化学平衡的影响",
        ],
        "answer": "D",
        "analysis": r"解析：固+固加热制 $\mathrm{NH_3}$ 会生成水，试管口应略向下倾斜以防冷凝水倒流炸裂试管，A 错；容量瓶不能用于溶解固体，应在烧杯中溶解、冷却后再转移定容，B 错；Na 与水反应剧烈，试管太细易造成液体飞溅甚至爆炸，应在烧杯中进行，C 错；$2\mathrm{NO_2}$（红棕色）$\rightleftharpoons\mathrm{N_2O_4}$（无色）受温度影响明显，用冷、热水对比可探究温度对化学平衡的影响，D 对。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "6",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第6题）化合物 Z 是某真菌的成分之一，结构如图（图为文字转述：分子中含羟基、羧基和 2 个碳碳双键，做题请对照原卷）。下列有关该物质说法错误的是（　　）",
        "options": [
            r"可形成分子间氢键",
            r"与乙酸、乙醇均能发生酯化反应",
            r"能与 $\mathrm{NaHCO_3}$ 溶液反应生成 $\mathrm{CO_2}$",
            r"1 mol Z 与 $\mathrm{Br_2}$ 的 $\mathrm{CCl_4}$ 溶液反应消耗 5 mol $\mathrm{Br_2}$",
        ],
        "answer": "D",
        "analysis": r"解析：Z 分子中含羟基和羧基，分子间可形成氢键，A 对；羟基可与乙酸酯化，羧基可与乙醇酯化，B 对；含羧基，能与 $\mathrm{NaHCO_3}$ 反应放出 $\mathrm{CO_2}$，C 对；分子中含 2 个碳碳双键，1 mol Z 只与 2 mol $\mathrm{Br_2}$ 发生加成，D 错。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "7",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第7题）稻壳制备纳米 Si 的流程图如下（流程图为文字转述：稻壳→$\mathrm{SiO_2}$→盐酸处理→Mg、650 ℃→纳米 Si，做题请对照原卷）。下列说法错误的是（　　）",
        "options": [
            r"$\mathrm{SiO_2}$ 可与 NaOH 溶液反应",
            r"盐酸在该工艺中体现了还原性",
            r"高纯 Si 可用于制造硅太阳能电池",
            r"制备纳米 Si：$\mathrm{SiO_2}+2\mathrm{Mg}\xrightarrow{650\ \mathrm{^\circ C}}\mathrm{Si}+2\mathrm{MgO}$",
        ],
        "answer": "B",
        "analysis": r"解析：$\mathrm{SiO_2}$ 是酸性氧化物，可与 NaOH 溶液反应生成 $\mathrm{Na_2SiO_3}$ 和水，A 对；盐酸用于溶解金属氧化物杂质（如 $\mathrm{MgO}+2\mathrm{HCl}=\mathrm{MgCl_2}+\mathrm{H_2O}$），化合价不变，属非氧化还原反应，只表现酸性，B 错；高纯 Si 是制造硅太阳能电池的原料，C 对；650 ℃ 下 Mg 还原 $\mathrm{SiO_2}$：$\mathrm{SiO_2}+2\mathrm{Mg}=\mathrm{Si}+2\mathrm{MgO}$，D 对。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "8",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第8题）某化学兴趣小组设计如下实验装置，通过测定反应前后质量的变化，验证 $\mathrm{NaNO_3}$ 固体在酒精灯加热条件下受热分解的气态产物。实验步骤：先缓慢通入 Ar 气排尽装置内空气；关闭Ⅰ左侧阀门，点燃酒精灯；一段时间后Ⅱ中灼热的铜网变黑，熄灭酒精灯甲；再次缓慢通入 Ar 气……（Ⅰ为加热 $\mathrm{NaNO_3}$ 的硬质玻璃管，Ⅱ、Ⅲ为灼热铜网，甲、乙、丙为三处酒精灯）下列说法错误的是（　　）",
        "options": [
            r"实验步骤中，点燃酒精灯的顺序为甲、乙、丙",
            r"整个过程中，若Ⅲ中灼热的铜网未变黑，则说明生成的 $\mathrm{O_2}$ 在Ⅱ中反应完全",
            r"实验结束后，若Ⅰ中减少的质量等于Ⅱ中增加的质量，则分解的气态产物只有 $\mathrm{O_2}$",
            r"$\mathrm{NaNO_3}$ 应远离热源、可燃物，并与还原性物质分开存放",
        ],
        "answer": "A",
        "analysis": r"解析：应先点燃乙、丙处酒精灯使Ⅱ、Ⅲ中铜网灼热，再点燃甲处酒精灯加热 $\mathrm{NaNO_3}$，否则分解产生的 $\mathrm{O_2}$ 来不及与铜网反应就被气流带走而损耗，A 错；若Ⅲ中铜网未变黑说明 $\mathrm{O_2}$ 已在Ⅱ中被完全吸收，B 对；Ⅰ减少的质量等于Ⅱ增加的质量（即 $\mathrm{O_2}$ 的质量）说明气态产物只有 $\mathrm{O_2}$（$2\mathrm{NaNO_3}\xrightarrow{\Delta}2\mathrm{NaNO_2}+\mathrm{O_2}\uparrow$），C 对；$\mathrm{NaNO_3}$ 受热分解放氧、具氧化性，应远离热源与还原性物质，D 对。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "9",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第9题）钙霞石是一种生产玻璃陶瓷的原料，所含 M、Q、R、T、X、Y、Z 为原子序数依次增大的前 20 号主族元素，M 是原子半径最小的元素，Q 是形成物质种类最多的元素，R 是地壳中含量最高的元素，T、X、Y 同周期，Q、X 均与 Y 相邻，Z 的原子序数等于 M、R 和 T 的原子序数之和。下列说法正确的是（　　）",
        "options": [
            r"M 与 Z 可形成离子化合物",
            r"原子半径：$\mathrm{R}<\mathrm{T}<\mathrm{X}$",
            r"$\mathrm{QR_2}$ 是极性分子",
            r"电负性：$\mathrm{Y}<\mathrm{R}<\mathrm{Q}$",
        ],
        "answer": "A",
        "analysis": r"解析：M 原子半径最小⇒H；Q 形成物质种类最多⇒C；R 地壳中含量最高⇒O；Q(C) 与 Y 同主族相邻⇒Y 为 Si，X 与 Y 相邻且与 T 同周期⇒X 为 Al；Z 的原子序数 $=1+8+T\le20$⇒T 为 11 号 Na、Z 为 20 号 Ca。H 与 Ca 形成 $\mathrm{CaH_2}$，属活泼金属氢化物，为离子化合物，A 对；原子半径 $\mathrm{Na}>\mathrm{Al}>\mathrm{O}$，即 $\mathrm{T}>\mathrm{X}>\mathrm{R}$，B 错；$\mathrm{QR_2}$ 为 $\mathrm{CO_2}$，直线形非极性分子，C 错；电负性 $\mathrm{O}>\mathrm{C}>\mathrm{Si}$，即 $\mathrm{R}>\mathrm{Q}>\mathrm{Y}$，D 错。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "10",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第10题）铜催化下，由 $\mathrm{CO_2}$ 电合成正丙醇的关键步骤如图（原卷图为反应机理循环图，做题请对照原卷）。下列说法正确的是（　　）",
        "options": [
            r"Ⅰ到Ⅱ的过程中发生氧化反应",
            r"Ⅱ到Ⅲ的过程中有非极性键生成",
            r"Ⅳ的示意图为（原卷选项图中对应的中间体示意图）",
            r"催化剂 Cu 可降低反应热",
        ],
        "answer": "C",
        "analysis": r"解析：Ⅰ→Ⅱ 过程中反应物得到 $\mathrm{H}^+$ 与电子，元素化合价降低，属还原反应，A 错；Ⅱ→Ⅲ 只生成 C—H 键，C 与 H 电负性不同，属极性键，无非极性键生成，B 错；由机理循环图可知Ⅲ→Ⅳ 继续结合 $\mathrm{H}^+$ 和电子再生成 1 个 C—H 键，Ⅳ 的结构与选项 C 的示意图一致，C 对；催化剂只能降低活化能、改变反应历程，不能改变反应热（$\Delta H$ 由反应物与生成物的能量差决定），D 错。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "11",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第11题）一种用双极膜电渗析法卤水除硼的装置如图所示，双极膜中 $\mathrm{H_2O}$ 解离的 $\mathrm{H}^+$ 和 $\mathrm{OH}^-$ 在电场作用下向两极迁移。除硼原理：$\mathrm{B(OH)_4^-}+\mathrm{H}^+=\mathrm{B(OH)_3}+\mathrm{H_2O}$。下列说法错误的是（　　）",
        "options": [
            r"Pt 电极反应：$4\mathrm{OH}^--4\mathrm{e}^-=\mathrm{O_2}\uparrow+2\mathrm{H_2O}$",
            r"外加电场可促进双极膜中水的电离",
            r"Ⅲ室中，X 膜、Y 膜分别为阳离子交换膜和阴离子交换膜",
            r"Ⅳ室每生成 1 mol NaOH，同时Ⅱ室最多生成 1 mol $\mathrm{B(OH)_3}$",
        ],
        "answer": "C",
        "analysis": r"解析：由 $\mathrm{H}^+$ 向阴极迁移知 Pt 电极为阳极，阳极 $\mathrm{OH}^-$ 放电：$4\mathrm{OH}^--4\mathrm{e}^-=\mathrm{O_2}\uparrow+2\mathrm{H_2O}$，A 对；外加电场使 $\mathrm{H}^+$、$\mathrm{OH}^-$ 不断迁出双极膜，降低其浓度，促进水的电离，B 对；Ⅲ室 NaCl 浓溶液变稀，说明 $\mathrm{Cl}^-$ 向阳极（Pt）迁移、$\mathrm{Na}^+$ 向阴极（石墨）迁移，故 X 为阴离子交换膜、Y 为阳离子交换膜，C 错；Ⅳ室每生成 1 mol NaOH 转移 1 mol 电子，同时有 1 mol $\mathrm{H}^+$ 迁入Ⅱ室生成 1 mol $\mathrm{B(OH)_3}$，D 对。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "12",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第12题）Be 及其化合物的转化关系如图（原卷图为转化关系图）。下列说法错误的是（　　）",
        "options": [
            r"$\mathrm{Be(OH)_2}$ 是两性氢氧化物",
            r"$\mathrm{Be_2C}$ 和 $\mathrm{BeCl_2}$ 的晶体类型相同",
            r"$\mathrm{Na_2[Be(OH)_4]}$ 中 Be 原子的杂化方式为 $\mathrm{sp}^3$",
            r"$\mathrm{Be_2C}$ 与 $\mathrm{H_2O}$ 反应：$\mathrm{Be_2C}+4\mathrm{H_2O}=2\mathrm{Be(OH)_2}+\mathrm{CH_4}\uparrow$",
        ],
        "answer": "B",
        "analysis": r"解析：$\mathrm{Be(OH)_2}$ 既能与盐酸反应（$\mathrm{Be(OH)_2}+2\mathrm{HCl}=\mathrm{BeCl_2}+2\mathrm{H_2O}$），又能与 NaOH 反应（$\mathrm{Be(OH)_2}+2\mathrm{NaOH}=\mathrm{Na_2[Be(OH)_4]}$），属两性氢氧化物，A 对；$\mathrm{Be_2C}$ 熔点高达 2200 ℃，属共价晶体；$\mathrm{BeCl_2}$ 熔点 405 ℃、沸点 488 ℃，属分子晶体，两者晶体类型不同，B 错；$[\mathrm{Be(OH)_4}]^{2-}$ 中 Be 形成 4 个 σ 键、无孤电子对，价层电子对数 4，为 $\mathrm{sp}^3$ 杂化，C 对；$\mathrm{Be_2C}$ 水解生成 $\mathrm{Be(OH)_2}$ 与 $\mathrm{CH_4}$，D 对。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "13",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 5,
        "stem": r"（2025 云南卷 第13题）$(\mathrm{Li}_{0.45}\mathrm{La}_{0.85})\mathrm{ScO_3}$ 是优良的固态电解质材料，$\mathrm{Ce}^{4+}$ 取代部分 $\mathrm{La}^{3+}$ 后产生空位，可提升 $\mathrm{Li}^+$ 传导性能。取代后材料的晶胞结构示意图（$\mathrm{O}^{2-}$ 未画出）及其作为电解质的电池装置如下（图见原卷）。下列说法错误的是（　　）",
        "options": [
            r"每个晶胞中 $\mathrm{O}^{2-}$ 个数为 12",
            r"该晶胞在 yz 平面的投影为（原卷选项投影图）",
            r"$\mathrm{Ce}^{4+}$ 取代后，该电解质的化学式为 $(\mathrm{Li}_{0.45}\mathrm{La}_{0.85-y}\mathrm{Ce}_y)\mathrm{ScO_3}$",
            r"若只有 $\mathrm{Li}^+$ 发生迁移，外电路转移的电子数与通过截面 MNPQ 的 $\mathrm{Li}^+$ 数目相等",
        ],
        "answer": "C",
        "analysis": r"解析：由晶胞图，$\mathrm{Sc}^{3+}$ 位于 8 个棱心和 4 个面心，$8\times\dfrac14+4\times\dfrac12=4$；化学式中 $\mathrm{O}^{2-}$ 个数为 Sc 的 3 倍，即 12，A 对；晶胞在 yz 平面的投影与选项图一致，B 对；$\mathrm{Ce}^{4+}$ 取代 $\mathrm{La}^{3+}$ 后正电荷增多，为保持电中性 $\mathrm{Li}^+$ 数目减少并产生空位，La 与 Ce 的数目之和不再是 0.85，故不能写成 $(\mathrm{Li}_{0.45}\mathrm{La}_{0.85-y}\mathrm{Ce}_y)\mathrm{ScO_3}$，C 错；$\mathrm{Li}^+$ 带 1 个单位电荷，按电量守恒，外电路转移电子数与通过截面的 $\mathrm{Li}^+$ 数目相等，D 对。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "14",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "选择题",
        "kp_id": None,
        "difficulty": 5,
        "stem": r"（2025 云南卷 第14题）甲醛法测定 $\mathrm{NH_4^+}$ 的反应原理为 $4\mathrm{NH_4^+}+6\mathrm{HCHO}=(\mathrm{CH_2})_6\mathrm{N_4H^+}+3\mathrm{H^+}+6\mathrm{H_2O}$。取含 $\mathrm{NH_4Cl}$ 的废水浓缩至原体积的 $\dfrac{1}{10}$ 后，移取 20.00 mL，加入足量甲醛反应后，用 0.01000 $\mathrm{mol\cdot L^{-1}}$ 的 NaOH 标准溶液滴定。滴定曲线如图 1，含氮微粒的分布分数 $\delta$ 与 pH 关系如图 2［比如：$\delta[(\mathrm{CH_2})_6\mathrm{N_4H^+}]=\dfrac{c[(\mathrm{CH_2})_6\mathrm{N_4H^+}]}{c[(\mathrm{CH_2})_6\mathrm{N_4H^+}]+c[(\mathrm{CH_2})_6\mathrm{N_4}]}$］。下列说法正确的是（　　）",
        "options": [
            r"废水中 $\mathrm{NH_4^+}$ 的含量为 20.00 $\mathrm{mg\cdot L^{-1}}$",
            r"c 点：$c[(\mathrm{CH_2})_6\mathrm{N_4H^+}]+c(\mathrm{H}^+)=c(\mathrm{OH}^-)$",
            r"a 点：$c[(\mathrm{CH_2})_6\mathrm{N_4H^+}]>c(\mathrm{H}^+)>c(\mathrm{OH}^-)>c[(\mathrm{CH_2})_6\mathrm{N_4}]$",
            r"$(\mathrm{CH_2})_6\mathrm{N_4H^+}\rightleftharpoons(\mathrm{CH_2})_6\mathrm{N_4}+\mathrm{H}^+$ 的平衡常数 $K\approx7.3\times10^{-6}$",
        ],
        "answer": "D",
        "analysis": r"解析：滴定出现两次 pH 突跃，结合反应原理知 1 mol $(\mathrm{CH_2})_6\mathrm{N_4H^+}$ 相当于 1 mol $\mathrm{H}^+$；因未给出废水的原始体积，无法计算废水中 $\mathrm{NH_4^+}$ 的含量，A 错；c 点 NaOH 过量，由电荷守恒 $c(\mathrm{Na}^+)+c(\mathrm{H}^+)+c[(\mathrm{CH_2})_6\mathrm{N_4H^+}]=c(\mathrm{Cl}^-)+c(\mathrm{OH}^-)$ 且 $c(\mathrm{Na}^+)>c(\mathrm{Cl}^-)$，推不出选项中的等式，B 错；a 点各微粒浓度大小关系与选项不符，C 错；由图 2，pH=6 时 $\delta[(\mathrm{CH_2})_6\mathrm{N_4}]=0.88$，则 $\delta[(\mathrm{CH_2})_6\mathrm{N_4H^+}]=0.12$，$K=\dfrac{c[(\mathrm{CH_2})_6\mathrm{N_4}]\cdot c(\mathrm{H}^+)}{c[(\mathrm{CH_2})_6\mathrm{N_4H^+}]}=\dfrac{0.88}{0.12}\times10^{-6}\approx7.3\times10^{-6}$，D 对。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [],
    },

    # ---------- 2025 云南卷 第15题（工艺流程 + 晶胞，14 分，按小问拆行） ----------
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "15(1)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 2,
        "stem": r"（2025 云南卷 第15题 第(1)问）从褐铁矿型金-银矿（含 Au、Ag、$\mathrm{Fe_2O_3}$、$\mathrm{MnO_2}$、CuO、$\mathrm{SiO_2}$ 等）中提取 Au、Ag，并回收其它有价金属的一种工艺如下（工艺流程图为文字转述，做题请对照原卷）。基态 Cu 原子的价层电子排布式为__________。",
        "options": [],
        "answer": r"$3\mathrm{d}^{10}4\mathrm{s}^1$",
        "analysis": r"解析：Cu 为 29 号元素，按洪特规则特例（全满稳定），基态价层电子排布式为 $3\mathrm{d}^{10}4\mathrm{s}^1$，而不是 $3\mathrm{d}^94\mathrm{s}^2$。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(1)问：写出 $3\mathrm{d}^{10}4\mathrm{s}^1$ 得 1 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "15(2)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第15题 第(2)问）褐铁矿型金-银矿提 Au、Ag 工艺中，「还原酸浸」时加入 $\mathrm{Na_2SO_3}$ 与硫酸，$\mathrm{MnO_2}$ 被还原为 $\mathrm{Mn}^{2+}$。写出「还原酸浸」时 $\mathrm{MnO_2}$ 反应的离子方程式：__________。",
        "options": [],
        "answer": r"$\mathrm{MnO_2}+\mathrm{SO_3^{2-}}+2\mathrm{H}^+=\mathrm{Mn}^{2+}+\mathrm{SO_4^{2-}}+\mathrm{H_2O}$",
        "analysis": r"解析：「还原酸浸」中 $\mathrm{SO_3^{2-}}$ 作还原剂被氧化为 $\mathrm{SO_4^{2-}}$，$\mathrm{MnO_2}$ 中 Mn 由 +4 降为 +2。配平检验：Mn、S 各 1；电荷左边 $-2+2=0$，右边 $+2-2=0$；O 左边 $2+3=5$，右边 $4+1=5$；H 左边 2、右边 2。同一工序中 $\mathrm{SO_3^{2-}}$ 还将 $\mathrm{Fe}^{3+}$ 还原为 $\mathrm{Fe}^{2+}$。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(2)问：离子方程式书写正确得 2 分（化学式错不得分，不配平扣 1 分）"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "15(3)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"""（2025 云南卷 第15题 第(3)问）褐铁矿型金-银矿工艺「浸金银」时，Au 溶解涉及的主要反应如下：
① $\mathrm{Au}+5\mathrm{S_2O_3^{2-}}+[\mathrm{Cu(NH_3)_4}]^{2+}=[\mathrm{Au(S_2O_3)_2}]^{3-}+[\mathrm{Cu(S_2O_3)_3}]^{5-}+4\mathrm{NH_3}$
② $4[\mathrm{Cu(S_2O_3)_3}]^{5-}+16\mathrm{NH_3}+\mathrm{O_2}+2\mathrm{H_2O}=4[\mathrm{Cu(NH_3)_4}]^{2+}+4\mathrm{OH}^-+12\mathrm{S_2O_3^{2-}}$
上述过程中的催化剂为__________。""",
        "options": [],
        "answer": r"$[\mathrm{Cu(NH_3)_4}]^{2+}$",
        "analysis": r"解析：反应①中 $[\mathrm{Cu(NH_3)_4}]^{2+}$ 被消耗，反应②中又重新生成，且反应前后其量不变，符合催化剂「参与反应但反应前后质量和化学性质不变」的特征，故催化剂为 $[\mathrm{Cu(NH_3)_4}]^{2+}$。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(3)问：答 $[\mathrm{Cu(NH_3)_4}]^{2+}$ 得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "15(4)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第15题 第(4)问）褐铁矿型金-银矿工艺中，「沉铜」前「滤液1」多次循环的目的为__________。",
        "options": [],
        "answer": r"提高原料 $\mathrm{H_2SO_4}$、$\mathrm{Na_2SO_3}$ 的利用率（循环返回的浸出液中仍含未反应的硫酸和亚硫酸钠，可继续用于「还原酸浸」，同时提高金属浸出率）",
        "analysis": r"解析：浸出后的「滤液1」中仍剩余未反应的 $\mathrm{H_2SO_4}$ 与 $\mathrm{Na_2SO_3}$，多次循环可使其继续参与「还原酸浸」，从而提高原料利用率、降低试剂消耗。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(4)问：答出「提高原料（硫酸、亚硫酸钠）利用率」得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "15(5)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第15题 第(5)问）根据「还原酸浸」「氧化」两步，推断 $\mathrm{Fe}^{3+}$、$\mathrm{Cu}^{2+}$、$\mathrm{MnO_2}$ 的氧化性由强到弱的顺序为__________。",
        "options": [],
        "answer": r"$\mathrm{MnO_2}>\mathrm{Fe}^{3+}>\mathrm{Cu}^{2+}$",
        "analysis": r"解析：「还原酸浸」时 $\mathrm{SO_3^{2-}}$ 将 $\mathrm{Fe}^{3+}$ 还原为 $\mathrm{Fe}^{2+}$，而 $\mathrm{Cu}^{2+}$ 未被还原，说明氧化性 $\mathrm{Fe}^{3+}>\mathrm{Cu}^{2+}$；「氧化」步骤中 $\mathrm{MnO_2}$ 又把 $\mathrm{Fe}^{2+}$ 氧化回 $\mathrm{Fe}^{3+}$，说明氧化性 $\mathrm{MnO_2}>\mathrm{Fe}^{3+}$。综上 $\mathrm{MnO_2}>\mathrm{Fe}^{3+}>\mathrm{Cu}^{2+}$。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(5)问：顺序写对得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "15(6)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第15题 第(6)问）已知 25 ℃ 时 $\mathrm{Mn(OH)_2}$ 的 $K_\mathrm{sp}=1.9\times10^{-13}$。「沉铁」后调节「滤液4」的 pH 至 8.0，无 $\mathrm{Mn(OH)_2}$ 析出，则 $c(\mathrm{Mn}^{2+})\le$ __________ $\mathrm{mol\cdot L^{-1}}$。",
        "options": [],
        "answer": "0.19",
        "analysis": r"解析：pH $=8.0$⇒$c(\mathrm{H}^+)=10^{-8}\ \mathrm{mol\cdot L^{-1}}$，$c(\mathrm{OH}^-)=\dfrac{10^{-14}}{10^{-8}}=10^{-6}\ \mathrm{mol\cdot L^{-1}}$。无沉淀析出要求 $Q\le K_\mathrm{sp}$，即 $c(\mathrm{Mn}^{2+})\cdot c^2(\mathrm{OH}^-)\le1.9\times10^{-13}$，代入得 $c(\mathrm{Mn}^{2+})\le\dfrac{1.9\times10^{-13}}{(10^{-6})^2}=0.19\ \mathrm{mol\cdot L^{-1}}$。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [
            r"第(6)问：算出 $c(\mathrm{OH}^-)=10^{-6}\ \mathrm{mol\cdot L^{-1}}$ 得 1 分",
            r"第(6)问：由 $K_\mathrm{sp}$ 算得 0.19 得 1 分",
        ],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "15(7)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 5,
        "stem": r"（2025 云南卷 第15题 第(7)问）一种锑锰（$\mathrm{Mn_3Sb}$）合金的立方晶胞结构如图（Sb 位于顶点，Mn 位于面心）。①该晶胞中，每个 Sb 周围与它最近且等距离的 Mn 有__________ 个。②$N_\mathrm{A}$ 为阿伏加德罗常数的值，晶胞边长为 $a$ nm，则晶体的密度为__________ $\mathrm{g\cdot cm^{-3}}$（列出计算式即可）。",
        "options": [],
        "answer": r"①12　②$\dfrac{122+3\times55}{N_\mathrm{A}\times(a\times10^{-7})^3}$（即 $\dfrac{287}{N_\mathrm{A}\cdot a^3\times10^{-21}}$）",
        "analysis": r"解析：①该晶胞为面心立方，Sb 处于顶点、Mn 处于面心。以某一顶点 Sb 为中心，与之最近且等距的 Mn 是相邻 3 个面的面心，合计 $3\times4=12$ 个。②均摊法：Sb 数 $=8\times\dfrac18=1$，Mn 数 $=6\times\dfrac12=3$，化学式为 $\mathrm{Mn_3Sb}$；晶胞质量 $=\dfrac{3\times55+122}{N_\mathrm{A}}=\dfrac{287}{N_\mathrm{A}}\ \mathrm{g}$，晶胞体积 $=(a\times10^{-7}\ \mathrm{cm})^3$，故 $\rho=\dfrac{287}{N_\mathrm{A}\times(a\times10^{-7})^3}\ \mathrm{g\cdot cm^{-3}}$。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [
            r"第(7)问①：答 12 得 1 分",
            r"第(7)问②：均摊法算出 $\mathrm{Mn_3Sb}$ 得 1 分；密度计算式正确得 1 分",
        ],
    },

    # ---------- 2025 云南卷 第16题（有机制备实验，14 分，按小问拆行） ----------
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "16(1)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "实验题",
        "kp_id": None,
        "difficulty": 2,
        "stem": r"（2025 云南卷 第16题 第(1)问）三氟甲基亚磺酸锂（$M_\mathrm{r}=140$）是我国科学家通过人工智能设计开发的一种锂离子电池补锂剂，其合成路线为：三氟甲磺酰氯 $\xrightarrow[\text{80 ℃}]{\mathrm{Na_2SO_3},\ \mathrm{NaHCO_3}}$ 三氟甲基亚磺酸钠 $\xrightarrow{\mathrm{HCl}}$ 三氟甲基亚磺酸 $\xrightarrow{\mathrm{LiOH}}$ 三氟甲基亚磺酸锂（装置如图，夹持及加热装置省略）。实验步骤Ⅰ：向仪器 A 中加入 3.5 g $\mathrm{NaHCO_3}$、5.2 g $\mathrm{Na_2SO_3}$ 和 20.0 mL 蒸馏水。仪器 A 的名称为__________，冷凝管中冷却水应从__________（填「b」或「c」）口通入。",
        "options": [],
        "answer": r"三颈烧瓶（三口烧瓶）；b",
        "analysis": r"解析：由装置图（三口、带搅拌与冷凝回流）知仪器 A 为三颈烧瓶；冷凝管冷却水应「下进上出」，即从下口 b 通入、上口 c 流出，使冷凝管充满冷却水，提高冷凝效果。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(1)问：仪器名称 1 分；b 口 1 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "16(2)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "实验题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第16题 第(2)问）三氟甲基亚磺酸锂合成实验步骤Ⅰ：向 A 中加入 $\mathrm{NaHCO_3}$、$\mathrm{Na_2SO_3}$ 和蒸馏水，搅拌下逐滴加入 2.1 mL（3.3 g）三氟甲磺酰氯，有气泡产生，80 ℃ 下反应 3 h。步骤Ⅰ反应中有气泡产生，其主要成分为__________。",
        "options": [],
        "answer": r"$\mathrm{CO_2}$（二氧化碳）",
        "analysis": r"解析：$\mathrm{Na_2SO_3}$ 将三氟甲磺酰氯还原为三氟甲基亚磺酸钠，同时生成 HCl；$\mathrm{NaHCO_3}$ 作中和剂与 HCl 反应：$\mathrm{NaHCO_3}+\mathrm{HCl}=\mathrm{NaCl}+\mathrm{CO_2}\uparrow+\mathrm{H_2O}$，故气泡主要成分为 $\mathrm{CO_2}$。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(2)问：答 $\mathrm{CO_2}$ 得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "16(3)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "实验题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第16题 第(3)问）三氟甲基亚磺酸锂合成实验步骤Ⅱ：向步骤Ⅰ所得固体中加入 10.0 mL 四氢呋喃（THF），充分搅拌后加入无水 $\mathrm{Na_2SO_4}$，振荡，抽滤、洗涤。步骤Ⅱ中第一次洗涤的目的是__________。",
        "options": [],
        "answer": r"将吸附在滤渣上的产品（三氟甲基亚磺酸钠）尽可能全部转入滤液中，减少产品损失，提高（三氟甲基亚磺酸锂的）产率",
        "analysis": r"解析：加入无水 $\mathrm{Na_2SO_4}$ 的目的是吸水、促进无机盐结晶析出；抽滤后滤渣表面吸附有产物三氟甲基亚磺酸钠，洗涤可将其转移至滤液中，减少损失，提高最终产品三氟甲基亚磺酸锂的产率。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(3)问：答出「减少产品损失、提高产率」得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "16(4)",
        "source_ref": "https://www.51jiaoxi.com/doc-17693629.html",
        "verified": 0,
        "qtype": "实验题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第16题 第(4)问）三氟甲基亚磺酸锂合成实验步骤Ⅲ：将所得三氟甲基亚磺酸钠和 3.0 mL THF 加入圆底烧瓶中，搅拌溶解后逐滴加入足量浓盐酸，析出白色固体。步骤Ⅲ中发生反应的化学方程式为__________，判断加入浓盐酸已足量的方法为__________。",
        "options": [],
        "answer": r"$\mathrm{CF_3SO_2Na}+\mathrm{HCl}=\mathrm{CF_3SO_2H}+\mathrm{NaCl}$；将液体静置，取少量上层清液于小试管中继续滴加浓盐酸，若不再产生白色沉淀，说明浓盐酸已足量（或：析出的白色固体质量不再增加）",
        "analysis": r"解析：三氟甲基亚磺酸钠（$\mathrm{CF_3SO_2Na}$）与浓盐酸发生复分解（强酸制弱酸），生成三氟甲基亚磺酸（$\mathrm{CF_3SO_2H}$，白色固体）和 NaCl：$\mathrm{CF_3SO_2Na}+\mathrm{HCl}=\mathrm{CF_3SO_2H}+\mathrm{NaCl}$。若盐酸不足，上层清液中仍含 $\mathrm{CF_3SO_2Na}$，滴加盐酸会继续生成白色沉淀；静置后取上层清液滴加浓盐酸，无白色沉淀（或沉淀质量不再增加）即说明盐酸已足量。来源：教习网 2025 年高考云南卷化学真题解析版（https://www.51jiaoxi.com/doc-17693629.html）。",
        "points": [
            r"第(4)问：化学方程式正确得 2 分",
            r"第(4)问：检验方法表述正确得 2 分",
        ],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "16(5)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "实验题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第16题 第(5)问）三氟甲基亚磺酸锂合成实验步骤Ⅳ：将滤液转入圆底烧瓶中，加入 2.0 mL 蒸馏水和过量 LiOH，室温搅拌反应 1 h 后，减压蒸除溶剂得粗产品。步骤Ⅳ中加入蒸馏水的作用是__________。",
        "options": [],
        "answer": r"作溶剂，使三氟甲基亚磺酸充分溶解（并电离），同时溶解 LiOH，增大反应物浓度，加快生成三氟甲基亚磺酸锂的反应",
        "analysis": r"解析：LiOH 易溶于水，加入蒸馏水可溶解 LiOH 并使三氟甲基亚磺酸充分溶解电离，二者在溶液中发生复分解反应生成产品三氟甲基亚磺酸锂；水作溶剂可增大反应物浓度与接触面积、加快反应速率。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(5)问：答出「作溶剂、促进溶解并加快反应」得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "16(6)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "实验题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第16题 第(6)问）三氟甲基亚磺酸锂（$M_\mathrm{r}=140$）合成实验中，三氟甲磺酰氯（$M_\mathrm{r}=168.5$）投料 2.1 mL（3.3 g），最终得产品 1.1 g。三氟甲基亚磺酸锂的产率为__________（列出计算式即可）。",
        "options": [],
        "answer": r"$\dfrac{1.1}{\dfrac{3.3}{168.5}\times140}\times100\%\approx40.1\%$（原卷参考答案约 40%，保留两位小数为 40.12%）",
        "analysis": r"解析：三氟甲磺酰氯的物质的量 $n=\dfrac{3.3\ \mathrm{g}}{168.5\ \mathrm{g\cdot mol^{-1}}}\approx0.0196\ \mathrm{mol}$，按 1∶1 转化，三氟甲基亚磺酸锂的理论物质的量同为 0.0196 mol，理论质量 $=0.0196\times140\ \mathrm{g}\approx2.74\ \mathrm{g}$。产率 $=\dfrac{1.1}{2.74}\times100\%\approx40.1\%$（保留两位小数约 40.12%）。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）、教习网解析版（https://www.51jiaoxi.com/doc-17693629.html）。",
        "points": [
            r"第(6)问：算出理论产量约 2.74 g 得 1 分",
            r"第(6)问：产率计算式与结果正确得 2 分",
        ],
    },

    # ---------- 2025 云南卷 第17题（反应原理综合，15 分，按小问拆行） ----------
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "17(1)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 2,
        "stem": r"（2025 云南卷 第17题 第(1)问）我国科学家研发出一种乙醇（沸点 78.5 ℃）绿色制氢新途径，并实现高附加值乙酸（沸点 118 ℃）的生产。乙醇可由秸秆生产，主要过程为：秸秆 →（预处理）→ 纤维素 →（水解）→ __________ →（发酵）→ 乙醇。",
        "options": [],
        "answer": r"葡萄糖（$\mathrm{C_6H_{12}O_6}$）",
        "analysis": r"解析：秸秆中的纤维素属多糖，水解的最终产物是葡萄糖（$\mathrm{C_6H_{12}O_6}$），葡萄糖在酒化酶作用下发酵生成乙醇和 $\mathrm{CO_2}$。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(1)问：答葡萄糖得 1 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "17(2)①",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"""（2025 云南卷 第17题 第(2)问①）乙醇绿色制氢的主要反应为：
Ⅰ．$\mathrm{C_2H_5OH(g)}+\mathrm{H_2O(g)}\rightleftharpoons 2\mathrm{H_2(g)}+\mathrm{CH_3COOH(g)}\quad \Delta H_1$
Ⅱ．$\mathrm{C_2H_5OH(g)}\rightleftharpoons \mathrm{CH_3CHO(g)}+\mathrm{H_2(g)}\quad \Delta H_2=+68.7\ \mathrm{kJ\cdot mol^{-1}}$
已知 $\mathrm{CH_3CHO(g)}+\mathrm{H_2O(g)}\rightleftharpoons \mathrm{H_2(g)}+\mathrm{CH_3COOH(g)}\quad \Delta H=-24.3\ \mathrm{kJ\cdot mol^{-1}}$，则 $\Delta H_1=$ __________ $\mathrm{kJ\cdot mol^{-1}}$。""",
        "options": [],
        "answer": r"$+44.4$",
        "analysis": r"解析：由盖斯定律，反应Ⅰ $=$ 反应Ⅱ $+$ 已知反应：$\mathrm{C_2H_5OH}\to\mathrm{CH_3CHO}+\mathrm{H_2}$（$\Delta H_2=+68.7$）与 $\mathrm{CH_3CHO}+\mathrm{H_2O}\to\mathrm{H_2}+\mathrm{CH_3COOH}$（$\Delta H=-24.3$）相加即得 $\mathrm{C_2H_5OH}+\mathrm{H_2O}\to2\mathrm{H_2}+\mathrm{CH_3COOH}$。故 $\Delta H_1=+68.7+(-24.3)=+44.4\ \mathrm{kJ\cdot mol^{-1}}$。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(2)①：盖斯定律关系式正确得 1 分；结果 $+44.4$ 得 1 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "17(2)②",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第17题 第(2)问②）对于反应Ⅰ $\mathrm{C_2H_5OH(g)}+\mathrm{H_2O(g)}\rightleftharpoons 2\mathrm{H_2(g)}+\mathrm{CH_3COOH(g)}$，一定温度下，下列叙述能说明恒容密闭容器中反应达到平衡状态的是__________（填标号）。A．容器内的压强不再变化　B．混合气体的密度不再变化　C．$\mathrm{CH_3COOH}$ 的体积分数不再变化　D．单位时间内生成 1 mol $\mathrm{H_2O}$，同时消耗 2 mol $\mathrm{H_2}$",
        "options": [],
        "answer": "AC",
        "analysis": r"解析：反应Ⅰ气体分子数由 2 变为 3，恒容下压强不再变化说明已达平衡，A 对；反应物与生成物全为气体、容器体积不变，气体总质量不变，密度始终不变，不能作平衡标志，B 错；$\mathrm{CH_3COOH}$ 的体积分数不再变化说明其生成速率与消耗速率相等，C 对；生成 1 mol $\mathrm{H_2O}$ 与消耗 2 mol $\mathrm{H_2}$ 描述的都是逆反应，任何时刻该比例都成立，D 错。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(2)②：选 AC 得 2 分（漏选得 1 分，错选不得分）"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "17(2)③",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第17题 第(2)问③）乙醇绿色制氢反应后，从混合气体中分离得到 $\mathrm{H_2}$，最适宜的方法为__________。",
        "options": [],
        "answer": r"降温冷凝（液化）分离：将混合气体冷却，乙醇（沸点 78.5 ℃）、乙酸（沸点 118 ℃）等冷凝为液体，剩余气体即为 $\mathrm{H_2}$",
        "analysis": r"解析：$\mathrm{H_2}$ 沸点极低（约 $-253\ \mathrm{^\circ C}$），而乙醇 78.5 ℃、乙酸 118 ℃，沸点相差很大，采用降温冷凝（液化）即可使有机物冷凝为液体而分离出 $\mathrm{H_2}$。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(2)③：答出「冷凝液化分离」得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "17(3)①",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第17题 第(3)问①）恒压 100 kPa 下，向密闭容器中按 $n(\mathrm{H_2O}):n(\mathrm{C_2H_5OH})=9:1$ 投料，产氢速率和产物的选择性随温度变化关系如图 1。由图 1 可知，反应Ⅰ最适宜的温度为 270 ℃，原因为__________。",
        "options": [],
        "answer": r"270 ℃ 时目标产物乙酸的选择性最高（副产物、乙醛的选择性低），且此时产氢速率较大；继续升高温度，产氢速率变化不大而乙酸选择性下降",
        "analysis": r"解析：选择最适宜温度要同时兼顾选择性与速率。由图 1，270 ℃ 时乙酸的选择性达到最大，副产物选择性及乙醛选择性低，同时 $\mathrm{H_2}$ 生成速率已较大；继续升温，产氢速率提升不明显而乙酸选择性降低，故 270 ℃ 最适宜。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(3)①：答出「乙酸选择性最高」得 1 分；答出「速率较快」得 1 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "17(3)②",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第17题 第(3)问②）关键步骤中间体的能量变化如图 2。由图中信息可知，乙酸可能是__________（填「产物1」「产物2」或「产物3」）。",
        "options": [],
        "answer": "产物1",
        "analysis": r"解析：乙酸是主要目标产物，应对应活化能最低、反应速率最快的路径；由图 2，生成产物 1 的活化能最低，故乙酸对应产物 1。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(3)②：答产物1 得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "17(3)③",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 5,
        "stem": r"（2025 云南卷 第17题 第(3)问③）恒压 100 kPa 下按 $n(\mathrm{H_2O}):n(\mathrm{C_2H_5OH})=9:1$ 投料，270 ℃ 时若容器中只发生反应Ⅰ、Ⅱ，平衡时乙醇的转化率为 90%，乙酸的选择性为 80%，则 $\dfrac{p(\mathrm{CH_3COOH})}{p(\mathrm{C_2H_5OH})}=$ __________，反应Ⅰ的平衡常数 $K_{p1}=$ __________ kPa（列出计算式即可；用平衡分压代替平衡浓度计算，分压 $=$ 总压×物质的量分数）。",
        "options": [],
        "answer": r"$\dfrac{p(\mathrm{CH_3COOH})}{p(\mathrm{C_2H_5OH})}=7.2$；$K_{p1}=\dfrac{\left(\dfrac{1.62}{10.9}\times100\right)^2\times\left(\dfrac{0.72}{10.9}\times100\right)}{\left(\dfrac{0.1}{10.9}\times100\right)\times\left(\dfrac{8.28}{10.9}\times100\right)}\ \mathrm{kPa}$（数值约 21 kPa）",
        "analysis": r"""解析：设起始 $n(\mathrm{H_2O})=9$ mol、$n(\mathrm{C_2H_5OH})=1$ mol。
Ⅰ．$\mathrm{C_2H_5OH}+\mathrm{H_2O}\rightleftharpoons 2\mathrm{H_2}+\mathrm{CH_3COOH}$，转化量为 $x$ mol；
Ⅱ．$\mathrm{C_2H_5OH}\rightleftharpoons \mathrm{CH_3CHO}+\mathrm{H_2}$，转化量为 $y$ mol。
乙醇转化率 90%⇒$x+y=0.9$；乙酸选择性 80%⇒$\dfrac{x}{x+y}=0.8$⇒$x=0.72$，$y=0.18$。
平衡时：$n(\mathrm{C_2H_5OH})=1-0.9=0.1$ mol，$n(\mathrm{H_2O})=9-0.72=8.28$ mol，
$n(\mathrm{H_2})=2x+y=1.62$ mol，$n(\mathrm{CH_3COOH})=0.72$ mol，$n(\mathrm{CH_3CHO})=0.18$ mol，
$n_\text{总}=0.1+8.28+1.62+0.72+0.18=10.9$ mol。
恒温恒压下分压之比等于物质的量之比：$\dfrac{p(\mathrm{CH_3COOH})}{p(\mathrm{C_2H_5OH})}=\dfrac{0.72}{0.1}=7.2$。
$K_{p1}=\dfrac{p^2(\mathrm{H_2})\cdot p(\mathrm{CH_3COOH})}{p(\mathrm{C_2H_5OH})\cdot p(\mathrm{H_2O})}$，各分压 $=$ 100 kPa×物质的量分数，代入即得上述计算式（数值约 21 kPa）。
来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。""",
        "points": [
            r"第(3)③：三段式求出各组分平衡物质的量得 2 分",
            r"第(3)③：比值 7.2 得 1 分；$K_{p1}$ 计算式正确得 2 分",
        ],
    },

    # ---------- 2025 云南卷 第18题（有机合成推断，15 分，按小问拆行） ----------
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "18(1)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 2,
        "stem": r"（2025 云南卷 第18题 第(1)问）化合物 L 是某中药的活性成分。一种合成路线如下（略去部分试剂与反应条件，忽略立体化学；合成路线图为文字转述，做题请对照原卷）。已知：在 Ru(Ⅱ) 的催化下，端烯烃与另一烯烃发生复分解反应得到产物。A 中含氧官能团的名称为__________。",
        "options": [],
        "answer": r"醛基（—CHO）",
        "analysis": r"解析：由原卷合成路线中 A 的结构简式可知，其含氧官能团为醛基（—CHO）。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(1)问：答醛基得 1 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "18(2)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第18题 第(2)问）化合物 L 的合成路线中，对比 C 和 D 的结构（二者互为同分异构体，结构见原卷图），可以推知 C 和 D 的__________（填标号）不相同。a．分子式　b．质谱图中的碎片峰　c．官能团",
        "options": [],
        "answer": "b",
        "analysis": r"解析：C 和 D 互为同分异构体，分子式相同，a 不符；二者均含碳碳双键、酯基和碳溴键，官能团种类相同，c 不符；结构不同，质谱中断裂方式不同，碎片峰的种类和强度不同，b 符合。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(2)问：选 b 得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "18(3)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第18题 第(3)问）化合物 L 的合成路线中，D 与 E 在 Ru(Ⅱ) 催化下发生已知信息中的端烯烃复分解反应（D→F）。D→F 中另一产物的化学名称为__________。",
        "options": [],
        "answer": r"乙烯（$\mathrm{CH_2=CH_2}$）",
        "analysis": r"解析：按烯烃复分解反应的规律（双键两端基团互换），两端烯烃反应时脱下的小分子烯烃为乙烯 $\mathrm{CH_2=CH_2}$，故另一产物的化学名称为乙烯。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(3)问：答乙烯得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "18(4)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第18题 第(4)问）化合物 L 的合成路线中，E 分子中含有碳碳双键（结构见原卷图）。E 发生加聚反应，产物的结构简式为__________。",
        "options": [],
        "answer": r"（原卷答案为结构简式图，文字无法完整转述，请对照原卷核对）产物为 E 中碳碳双键打开相互连接而成的高分子，重复单元骨架与 E 相同、双键变为单键",
        "analysis": r"解析：E 分子结构中含 $\mathrm{C=C}$，发生加聚反应时双键打开相互连接，产物为以 E 的碳骨架为重复单元的高分子（结构简式见原卷答案图）。核对请以 21 世纪教育网 2025 云南卷真题原卷答案（https://zy.21cnjy.com/24900045）为准。",
        "points": [r"第(4)问：写出加聚产物结构简式得 2 分（原卷为图）"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "18(5)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 3,
        "stem": r"（2025 云南卷 第18题 第(5)问）化合物 L 的合成路线中，F 在 $\mathrm{SeO_2}$ 条件下转化为 G，G 再与 $\mathrm{H_2}$ 加成得到 H。F→G 的反应类型为__________。",
        "options": [],
        "answer": "氧化反应",
        "analysis": r"解析：对比 F、G、H 的结构简式与分子式可知，F→G 过程中分子增加了 1 个氧原子（$\mathrm{SeO_2}$ 条件下的氧化），属氧化反应；G→H 为与 $\mathrm{H_2}$ 的加成（还原）反应。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(5)问：答氧化反应得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "18(6)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第18题 第(6)问）羰基具有较强的极性。化合物 L 的合成路线中，I→J 经历了加成和消去的过程，其中间体的结构简式为__________（填字母 a、b、c、d，四个候选结构见原卷图）。",
        "options": [],
        "answer": "c",
        "analysis": r"解析：I→J 时，I 中 —$\mathrm{NH_2}$ 的 N 原子与 H 原子分别与酮羰基的 C、O 发生加成，生成含羟基（—OH）和氨基的七元环中间体；随后 N 去 H、C 去 —OH，消去一分子 $\mathrm{H_2O}$ 得到 J，与选项 c 的结构一致。来源：21世纪教育网 2025 云南卷化学真题（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(6)问：选 c 得 2 分"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "18(7)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 4,
        "stem": r"（2025 云南卷 第18题 第(7)问）化合物 L 的合成路线最后一步为 K→L（K、L 的结构见原卷图）。写出 K→L 的化学方程式：__________。",
        "options": [],
        "answer": r"（原卷答案为带结构简式的化学方程式图，文字无法完整转述，请对照原卷核对）反应本质：K 与甲醇（$\mathrm{CH_3OH}$）发生酯交换反应，K 中的酯基与甲醇的 —OH 交换，生成 L 并脱去小分子 $\mathrm{CH_3OH}$",
        "analysis": r"解析：K→L 为酯交换（取代）反应，K 分子中的酯基与甲醇发生交换，生成目标产物 L，同时脱去小分子甲醇（$\mathrm{CH_3OH}$）。完整化学方程式含结构简式，见 21 世纪教育网 2025 云南卷真题原卷答案（https://zy.21cnjy.com/24900045）。",
        "points": [r"第(7)问：方程式（含结构简式）书写正确得 2 分（原卷为图）"],
    },
    {
        "year": 2025,
        "paper": "2025 云南卷",
        "question_no": "18(8)",
        "source_ref": "https://zy.21cnjy.com/24900045",
        "verified": 0,
        "qtype": "填空题",
        "kp_id": None,
        "difficulty": 5,
        "stem": r"""（2025 云南卷 第18题 第(8)问）写出一种满足下列条件的 L 的同分异构体的结构简式（不考虑立体异构）：
①能与 $\mathrm{FeCl_3}$ 发生显色反应；1 mol 该物质与足量 NaOH 溶液反应，消耗 3 mol NaOH。
②核磁共振氢谱显示 6 组峰，且峰面积比为 $9:2:2:2:1:1$。
③含有酯基和氨基（或取代的氨基 —$\mathrm{NR'R''}$，$\mathrm{R'}$ 和 $\mathrm{R''}$ 可以是 H 或烃基）。""",
        "options": [],
        "answer": r"（原卷答案为结构简式图，文字无法完整转述，请对照原卷核对）推导依据：L 的分子式为 $\mathrm{C_{12}H_{17}NO_3}$；含酚羟基（与 $\mathrm{FeCl_3}$ 显色）和一个酚酯基（酚羟基 1 mol + 酚酯水解后共消耗 3 mol NaOH）；氢谱 6 组峰、峰面积比 9∶2∶2∶2∶1∶1 说明含 —$\mathrm{C(CH_3)_3}$（9 个等效氢），苯环上羟基位于对位",
        "analysis": r"解析：①能与 $\mathrm{FeCl_3}$ 显色⇒含酚羟基；1 mol 消耗 3 mol NaOH⇒1 个酚羟基（1 mol）+ 1 个酚酯基（水解生成酚羟基和羧基共 2 mol），且分子只有 3 个氧原子，与 $\mathrm{C_{12}H_{17}NO_3}$ 相符。②氢谱 6 组峰、其中一组为 9 个氢⇒存在 —$\mathrm{C(CH_3)_3}$。③含酯基和氨基。据此可写出原卷答案给出的两种结构简式（酚羟基位于 —$\mathrm{C(CH_3)_3}$ 的对位）。核对请以 21 世纪教育网 2025 云南卷真题原卷答案（https://zy.21cnjy.com/24900045）为准。",
        "points": [r"第(8)问：写出一种符合条件的结构简式得 2 分（原卷为图）"],
    },
]
